#!/bin/bash
#SBATCH --partition prodshared
#SBATCH --time=12:00:00 
#SBATCH --nodes=1 --ntasks-per-node=36
#SBATCH --job-name=EGR
#SBATCH --output=ssb_output_prodshare02.o       ## Name of the output report file
#SBATCH --error=ssb_error_prodshare02.e        ## Name of the error report file
#SBATCH --mail-user theot@cerfacs.fr
#SBATCH --mail-type=ALL

cd ${SLURM_SUBMIT_DIR}
source /home/cfd/theot/.bashrc
source activate can230

python3 /home/cfd/theot/EGR0D/src/lib_egr_260.py > log_allEGR1D_prodshare02.out
#mpirun -np 64 python3 /home/cfd/theot/EGR0D/lib_egr_260.py > log_EGR1D.out
