#!/bin/bash
#SBATCH --partition debug
#SBATCH --time=00:10:00 
#SBATCH --nodes=1 --ntasks-per-node=36
#SBATCH --job-name=EGR1D
#SBATCH --output=ssb_output_debug.o       ## Name of the output report file
#SBATCH --error=ssb_error_debug.e        ## Name of the error report file
#SBATCH --mail-user theot@cerfacs.fr
#SBATCH --mail-type=ALL

cd ${SLURM_SUBMIT_DIR}
source /home/cfd/theot/.bashrc
source activate can230

python3 /home/cfd/theot/EGR0D/lib_egr_260.py > log_debug.out
