!--------------------------------------------------------------------------------------------------
!     Copyright (c) CERFACS (all rights reserved)
!--------------------------------------------------------------------------------------------------
!     FILE ./database/S16R93QSS6_0/S16R93QSS6_0.f90
!>    @file ./database/S16R93QSS6_0/S16R93QSS6_0.f90
!!    Module for calculating the analytical source terms in Cantera
!!    @details 
!!    @authors 
!!    @date    2023/08/22
!!    @since   
!!    @note    
!--------------------------------------------------------------------------------------------------

!--------------------------------------------------------------------------------------------------
!     MODULE mod_customkinetics
!>    @details Generated by ARCANE custom kinetics routine to compute the chemical source terms.
!!    @authors Q. Cazères, P. Pepiot
!!    @date    2019/01/24
!--------------------------------------------------------------------------------------------------
module mod_customkinetics
  implicit none

  integer, parameter :: pr = selected_real_kind(15,307)

  ! Ideal gas constant
  real(pr), parameter :: Rcst = 8.3144621_pr
  
  ! Use semi-implicit formulation for select species
  logical, parameter :: semiImplicit = .False.
  
  ! Number of elements in the chemical system 
  integer, parameter :: ne = 3
  
  ! Number of non-qss and qss species and reactions
  integer, parameter :: nspec = 16
  integer, parameter :: nqss = 6
  integer, parameter :: nreac = 93
  integer, parameter :: nreac_reverse = 93
  
  ! Actual expression of each reaction
  character(len=65), dimension(nreac + nreac_reverse) :: reacexp
  
  ! Number of thirdbodies
  integer, parameter :: nTB = 6
  integer, parameter :: nFO = 11
  integer, parameter :: nTB_reverse = 6
  integer, parameter :: nFO_reverse = 11
  
  ! Index of elements
  integer, parameter :: eH = 1
  integer, parameter :: eO = 2
  integer, parameter :: eC = 3

  ! Index of species
  integer, parameter :: sH2 = 1
  integer, parameter :: sH = 2
  integer, parameter :: sO2 = 3
  integer, parameter :: sOH = 4
  integer, parameter :: sH2O = 5
  integer, parameter :: sHO2 = 6
  integer, parameter :: sCH3 = 7
  integer, parameter :: sCH4 = 8
  integer, parameter :: sCO = 9
  integer, parameter :: sCO2 = 10
  integer, parameter :: sHCO = 11
  integer, parameter :: sCH2O = 12
  integer, parameter :: sCH3O = 13
  integer, parameter :: sC2H4 = 14
  integer, parameter :: sC2H6 = 15
  integer, parameter :: sN2 = 16

  integer, parameter :: sqssO = 1
  integer, parameter :: sqssCH2 = 2
  integer, parameter :: sqssCH2GSG = 3
  integer, parameter :: sqssCH3OH = 4
  integer, parameter :: sqssC2H = 5
  integer, parameter :: sqssC2H5 = 6

  ! Index of reactions
  integer, parameter :: r1f = 1
  integer, parameter :: r2f = 2
  integer, parameter :: r3f = 3
  integer, parameter :: r4f = 4
  integer, parameter :: r5f = 5
  integer, parameter :: r6f = 6
  integer, parameter :: r7f = 7
  integer, parameter :: r8f = 8
  integer, parameter :: r9f = 9
  integer, parameter :: r10f = 10
  integer, parameter :: r11f = 11
  integer, parameter :: r12f = 12
  integer, parameter :: r13f = 13
  integer, parameter :: r14f = 14
  integer, parameter :: r15f = 15
  integer, parameter :: r16f = 16
  integer, parameter :: r17f = 17
  integer, parameter :: r18f = 18
  integer, parameter :: r19f = 19
  integer, parameter :: r20f = 20
  integer, parameter :: r21f = 21
  integer, parameter :: r22f = 22
  integer, parameter :: r23f = 23
  integer, parameter :: r24f = 24
  integer, parameter :: r25f = 25
  integer, parameter :: r26f = 26
  integer, parameter :: r27f = 27
  integer, parameter :: r28f = 28
  integer, parameter :: r29f = 29
  integer, parameter :: r30f = 30
  integer, parameter :: r31f = 31
  integer, parameter :: r32f = 32
  integer, parameter :: r33f = 33
  integer, parameter :: r34f = 34
  integer, parameter :: r35f = 35
  integer, parameter :: r36f = 36
  integer, parameter :: r37f = 37
  integer, parameter :: r38f = 38
  integer, parameter :: r39f = 39
  integer, parameter :: r40f = 40
  integer, parameter :: r41f = 41
  integer, parameter :: r42f = 42
  integer, parameter :: r43f = 43
  integer, parameter :: r44f = 44
  integer, parameter :: r45f = 45
  integer, parameter :: r46f = 46
  integer, parameter :: r47f = 47
  integer, parameter :: r48f = 48
  integer, parameter :: r49f = 49
  integer, parameter :: r50f = 50
  integer, parameter :: r51f = 51
  integer, parameter :: r52f = 52
  integer, parameter :: r53f = 53
  integer, parameter :: r54f = 54
  integer, parameter :: r55f = 55
  integer, parameter :: r56f = 56
  integer, parameter :: r57f = 57
  integer, parameter :: r58f = 58
  integer, parameter :: r59f = 59
  integer, parameter :: r60f = 60
  integer, parameter :: r61f = 61
  integer, parameter :: r62f = 62
  integer, parameter :: r63f = 63
  integer, parameter :: r64f = 64
  integer, parameter :: r65f = 65
  integer, parameter :: r66f = 66
  integer, parameter :: r67f = 67
  integer, parameter :: r68f = 68
  integer, parameter :: r69f = 69
  integer, parameter :: r70f = 70
  integer, parameter :: r71f = 71
  integer, parameter :: r72f = 72
  integer, parameter :: r73f = 73
  integer, parameter :: r74f = 74
  integer, parameter :: r75f = 75
  integer, parameter :: r76f = 76
  integer, parameter :: r77f = 77
  integer, parameter :: r78f = 78
  integer, parameter :: r79f = 79
  integer, parameter :: r80f = 80
  integer, parameter :: r81f = 81
  integer, parameter :: r82f = 82
  integer, parameter :: r83f = 83
  integer, parameter :: r84f = 84
  integer, parameter :: r85f = 85
  integer, parameter :: r86f = 86
  integer, parameter :: r87f = 87
  integer, parameter :: r88f = 88
  integer, parameter :: r89f = 89
  integer, parameter :: r90f = 90
  integer, parameter :: r91f = 91
  integer, parameter :: r92f = 92
  integer, parameter :: r93f = 93
  integer, parameter :: r1b = 94
  integer, parameter :: r2b = 95
  integer, parameter :: r3b = 96
  integer, parameter :: r4b = 97
  integer, parameter :: r5b = 98
  integer, parameter :: r6b = 99
  integer, parameter :: r7b = 100
  integer, parameter :: r8b = 101
  integer, parameter :: r9b = 102
  integer, parameter :: r10b = 103
  integer, parameter :: r11b = 104
  integer, parameter :: r12b = 105
  integer, parameter :: r13b = 106
  integer, parameter :: r14b = 107
  integer, parameter :: r15b = 108
  integer, parameter :: r16b = 109
  integer, parameter :: r17b = 110
  integer, parameter :: r18b = 111
  integer, parameter :: r19b = 112
  integer, parameter :: r20b = 113
  integer, parameter :: r21b = 114
  integer, parameter :: r22b = 115
  integer, parameter :: r23b = 116
  integer, parameter :: r24b = 117
  integer, parameter :: r25b = 118
  integer, parameter :: r26b = 119
  integer, parameter :: r27b = 120
  integer, parameter :: r28b = 121
  integer, parameter :: r29b = 122
  integer, parameter :: r30b = 123
  integer, parameter :: r31b = 124
  integer, parameter :: r32b = 125
  integer, parameter :: r33b = 126
  integer, parameter :: r34b = 127
  integer, parameter :: r35b = 128
  integer, parameter :: r36b = 129
  integer, parameter :: r37b = 130
  integer, parameter :: r38b = 131
  integer, parameter :: r39b = 132
  integer, parameter :: r40b = 133
  integer, parameter :: r41b = 134
  integer, parameter :: r42b = 135
  integer, parameter :: r43b = 136
  integer, parameter :: r44b = 137
  integer, parameter :: r45b = 138
  integer, parameter :: r46b = 139
  integer, parameter :: r47b = 140
  integer, parameter :: r48b = 141
  integer, parameter :: r49b = 142
  integer, parameter :: r50b = 143
  integer, parameter :: r51b = 144
  integer, parameter :: r52b = 145
  integer, parameter :: r53b = 146
  integer, parameter :: r54b = 147
  integer, parameter :: r55b = 148
  integer, parameter :: r56b = 149
  integer, parameter :: r57b = 150
  integer, parameter :: r58b = 151
  integer, parameter :: r59b = 152
  integer, parameter :: r60b = 153
  integer, parameter :: r61b = 154
  integer, parameter :: r62b = 155
  integer, parameter :: r63b = 156
  integer, parameter :: r64b = 157
  integer, parameter :: r65b = 158
  integer, parameter :: r66b = 159
  integer, parameter :: r67b = 160
  integer, parameter :: r68b = 161
  integer, parameter :: r69b = 162
  integer, parameter :: r70b = 163
  integer, parameter :: r71b = 164
  integer, parameter :: r72b = 165
  integer, parameter :: r73b = 166
  integer, parameter :: r74b = 167
  integer, parameter :: r75b = 168
  integer, parameter :: r76b = 169
  integer, parameter :: r77b = 170
  integer, parameter :: r78b = 171
  integer, parameter :: r79b = 172
  integer, parameter :: r80b = 173
  integer, parameter :: r81b = 174
  integer, parameter :: r82b = 175
  integer, parameter :: r83b = 176
  integer, parameter :: r84b = 177
  integer, parameter :: r85b = 178
  integer, parameter :: r86b = 179
  integer, parameter :: r87b = 180
  integer, parameter :: r88b = 181
  integer, parameter :: r89b = 182
  integer, parameter :: r90b = 183
  integer, parameter :: r91b = 184
  integer, parameter :: r92b = 185
  integer, parameter :: r93b = 186
  
  ! Index of third body species
  integer, parameter :: mM1 = 1
  integer, parameter :: mM6 = 2
  integer, parameter :: mM15 = 3
  integer, parameter :: mM20 = 4
  integer, parameter :: mM24 = 5
  integer, parameter :: mM89 = 6
  
  integer, parameter :: mM28 = 7
  integer, parameter :: mM29 = 8
  integer, parameter :: mM31 = 9
  integer, parameter :: mM33 = 10
  integer, parameter :: mM35 = 11
  integer, parameter :: mM40 = 12
  integer, parameter :: mM41 = 13
  integer, parameter :: mM44 = 14
  integer, parameter :: mM50 = 15
  integer, parameter :: mM72 = 16
  integer, parameter :: mM82 = 17
  
  ! Index of third body reactions
  integer, parameter :: TBr1f = 1
  integer, parameter :: TBr6f = 2
  integer, parameter :: TBr15f = 3
  integer, parameter :: TBr20f = 4
  integer, parameter :: TBr24f = 5
  integer, parameter :: TBr89f = 6
  integer, parameter :: TBr1b = 7
  integer, parameter :: TBr6b = 8
  integer, parameter :: TBr15b = 9
  integer, parameter :: TBr20b = 10
  integer, parameter :: TBr24b = 11
  integer, parameter :: TBr89b = 12
  
  ! Index of fall off reactions
  integer, parameter :: FOr28f = 1
  integer, parameter :: FOr29f = 2
  integer, parameter :: FOr31f = 3
  integer, parameter :: FOr33f = 4
  integer, parameter :: FOr35f = 5
  integer, parameter :: FOr40f = 6
  integer, parameter :: FOr41f = 7
  integer, parameter :: FOr44f = 8
  integer, parameter :: FOr50f = 9
  integer, parameter :: FOr72f = 10
  integer, parameter :: FOr82f = 11
  integer, parameter :: FOr28b = 12
  integer, parameter :: FOr29b = 13
  integer, parameter :: FOr31b = 14
  integer, parameter :: FOr33b = 15
  integer, parameter :: FOr35b = 16
  integer, parameter :: FOr40b = 17
  integer, parameter :: FOr41b = 18
  integer, parameter :: FOr44b = 19
  integer, parameter :: FOr50b = 20
  integer, parameter :: FOr72b = 21
  integer, parameter :: FOr82b = 22
  
  ! Molar mass
  real(pr), parameter, dimension(nspec) :: W_sp =(/ &
       2.015880e-03_pr, & ! H2
       1.007940e-03_pr, & ! H
       3.199880e-02_pr, & ! O2
       1.700734e-02_pr, & ! OH
       1.801528e-02_pr, & ! H2O
       3.300674e-02_pr, & ! HO2
       1.503482e-02_pr, & ! CH3
       1.604276e-02_pr, & ! CH4
       2.801040e-02_pr, & ! CO
       4.400980e-02_pr, & ! CO2
       2.901834e-02_pr, & ! HCO
       3.002628e-02_pr, & ! CH2O
       3.103422e-02_pr, & ! CH3O
       2.805376e-02_pr, & ! C2H4
       3.006964e-02_pr, & ! C2H6
       2.801348e-02_pr & ! N2
      !1.599940e-02_pr, & ! O
      !1.402688e-02_pr, & ! CH2
      !1.402688e-02_pr, & ! CH2GSG
      !3.204216e-02_pr, & ! CH3OH
      !2.502994e-02_pr, & ! C2H
      !2.906170e-02_pr & ! C2H5
       /)
  
contains

  ! ----------------------------------------------- !
  ! Subroutine for pressure dependent coefficients  !
  ! ----------------------------------------------- !
  real(pr) function getlindratecoeff(Tloc,k0,kinf,fc,concin,Ploc)
    implicit none

    real(pr) ::  Tloc,k0,kinf,fc,redP,Ploc
    real(pr) :: ntmp,ccoeff,dcoeff,lgknull
    real(pr) :: f
    real(pr) :: conc, concin

    if (concin.gt.0.0_pr) then
       conc = concin
    else
       conc = Ploc / ( Rcst * Tloc )
    end if
    
    redP = abs(k0) * conc / max(abs(kinf), tiny(1.0_pr)) + tiny(1.0_pr)

    ntmp = 0.75_pr - 1.27_pr * log10( fc )
    ccoeff = - 0.4_pr - 0.67_pr * log10( fc )
    dcoeff = 0.14_pr
    lgknull = log10(redP)
    f = (lgknull+ccoeff)/(ntmp-dcoeff*(lgknull+ccoeff))
    f = fc**(1.0_pr / ( f * f + 1.0_pr ))
    
    getlindratecoeff = kinf * f * redP / ( 1.0_pr + redP )

  end function getlindratecoeff

  ! ----------------------------------------------- !
  ! Evaluate thirdbodies                            !
  ! ----------------------------------------------- !
  subroutine get_thirdbodies(M,c)
    implicit none

    real(pr), dimension(nspec) :: c
    real(pr), dimension(nTB + nFO) :: M

    M(mM1) = (1.000000e+00_pr)*c(sCH4) &
         + (5.000000e-01_pr)*c(sCO) &
         + (1.000000e+00_pr)*c(sCO2) &
         + (5.000000e+00_pr)*c(sH2O) &
         + sum(c)

    M(mM6) = (1.000000e+00_pr)*c(sCH4) &
         + (5.000000e-01_pr)*c(sCO) &
         + (2.500000e+00_pr)*c(sCO2) &
         + (5.000000e+00_pr)*c(sH2O) &
         + (5.000000e+00_pr)*c(sO2) &
         + sum(c)

    M(mM15) = (-2.500000e-01_pr)*c(sCO) &
         + (5.000000e-01_pr)*c(sCO2) &
         + (-1.000000e+00_pr)*c(sH2O) &
         + (-1.000000e+00_pr)*c(sN2) &
         + (-1.000000e+00_pr)*c(sO2) &
         + sum(c)

    M(mM20) = (1.000000e+00_pr)*c(sCH4) &
         + (-1.000000e+00_pr)*c(sCO2) &
         + (-1.000000e+00_pr)*c(sH2O) &
         + sum(c)

    M(mM24) = (1.000000e+00_pr)*c(sCH4) &
         + (2.650000e+00_pr)*c(sH2O) &
         + sum(c)

    M(mM89) = (1.000000e+00_pr)*c(sCH4) &
         + (5.000000e-01_pr)*c(sCO) &
         + (1.000000e+00_pr)*c(sCO2) &
         + (-1.000000e+00_pr)*c(sH2O) &
         + sum(c)

    M(mM28) = (1.000000e+00_pr)*c(sCH4) &
         + (5.000000e-01_pr)*c(sCO) &
         + (1.000000e+00_pr)*c(sCO2) &
         + (5.000000e+00_pr)*c(sH2O) &
         + sum(c)

    M(mM29) = (1.000000e+00_pr)*c(sCH4) &
         + (5.000000e-01_pr)*c(sCO) &
         + (1.000000e+00_pr)*c(sCO2) &
         + (5.000000e+00_pr)*c(sH2O) &
         + sum(c)

    M(mM31) = (1.000000e+00_pr)*c(sCH4) &
         + (5.000000e-01_pr)*c(sCO) &
         + (1.000000e+00_pr)*c(sCO2) &
         + (5.000000e+00_pr)*c(sH2O) &
         + sum(c)

    M(mM33) = (1.000000e+00_pr)*c(sCH4) &
         + (5.000000e-01_pr)*c(sCO) &
         + (1.000000e+00_pr)*c(sCO2) &
         + (5.000000e+00_pr)*c(sH2O) &
         + sum(c)

    M(mM35) = (1.000000e+00_pr)*c(sCH4) &
         + (5.000000e-01_pr)*c(sCO) &
         + (1.000000e+00_pr)*c(sCO2) &
         + (5.000000e+00_pr)*c(sH2O) &
         + sum(c)

    M(mM40) = (1.000000e+00_pr)*c(sCH4) &
         + (5.000000e-01_pr)*c(sCO) &
         + (1.000000e+00_pr)*c(sCO2) &
         + (5.000000e+00_pr)*c(sH2O) &
         + sum(c)

    M(mM41) = (1.000000e+00_pr)*c(sCH4) &
         + (5.000000e-01_pr)*c(sCO) &
         + (1.000000e+00_pr)*c(sCO2) &
         + (5.000000e+00_pr)*c(sH2O) &
         + sum(c)

    M(mM44) = (1.000000e+00_pr)*c(sCH4) &
         + (5.000000e-01_pr)*c(sCO) &
         + (1.000000e+00_pr)*c(sCO2) &
         + (5.000000e+00_pr)*c(sH2O) &
         + sum(c)

    M(mM50) = (1.000000e+00_pr)*c(sCH4) &
         + (5.000000e-01_pr)*c(sCO) &
         + (1.000000e+00_pr)*c(sCO2) &
         + (5.000000e+00_pr)*c(sH2O) &
         + sum(c)

    M(mM72) = (1.000000e+00_pr)*c(sCH4) &
         + (5.000000e-01_pr)*c(sCO) &
         + (1.000000e+00_pr)*c(sCO2) &
         + (5.000000e+00_pr)*c(sH2O) &
         + sum(c)

    M(mM82) = (1.000000e+00_pr)*c(sCH4) &
         + (5.000000e-01_pr)*c(sCO) &
         + (1.000000e+00_pr)*c(sCO2) &
         + (5.000000e+00_pr)*c(sH2O) &
         + sum(c)

  end subroutine get_thirdbodies
  
  ! ----------------------------------------------- !
  ! Evaluate rate coefficients                      !
  ! ----------------------------------------------- !
  subroutine get_rate_coefficients(k,M,Tloc,Ploc)
    implicit none

    real(pr), dimension(nreac + nreac_reverse) :: k
    real(pr), dimension(nFO + nFO_reverse) :: k_0
    real(pr), dimension(nFO + nFO_reverse) :: k_inf
    real(pr), dimension(nFO + nFO_reverse) :: FC
    real(pr), dimension(nTB + nFO) :: M
    real(pr) :: Tloc,Ploc,R_T_inv,T_log,redP

    ! Rate coefficients
    R_T_inv = 1.0_pr/(Rcst*Tloc)
    T_log = log(Tloc)

    k(r1f) = (5.000000e+05_pr)*exp((-1.000000e+00_pr)*T_log )
    k(r2f) = (5.000000e-02_pr)*exp((-2.631736e+04_pr)*R_T_inv + (2.670000e+00_pr)*T_log )
    k(r3f) = (2.000000e+07_pr)
    k(r4f) = (8.430000e+07_pr)
    k(r5f) = (1.020000e+03_pr)*exp((-3.598240e+04_pr)*R_T_inv + (1.500000e+00_pr)*T_log )
    k(r6f) = (6.020000e+02_pr)*exp((-1.255200e+04_pr)*R_T_inv )
    k(r7f) = (3.000000e+07_pr)
    k(r8f) = (3.000000e+07_pr)
    k(r9f) = (3.900000e+07_pr)*exp((-1.481136e+04_pr)*R_T_inv )
    k(r10f) = (1.000000e+07_pr)
    k(r11f) = (1.920000e+01_pr)*exp((-9.204800e+02_pr)*R_T_inv + (1.830000e+00_pr)*T_log )
    k(r12f) = (8.980000e+01_pr)*exp((-2.380696e+04_pr)*R_T_inv + (1.920000e+00_pr)*T_log )
    k(r13f) = (2.500000e+06_pr)*exp((-1.999952e+05_pr)*R_T_inv )
    k(r14f) = (1.000000e+08_pr)*exp((-1.673600e+05_pr)*R_T_inv )
    k(r15f) = (2.800000e+06_pr)*exp((-8.600000e-01_pr)*T_log )
    k(r16f) = (3.000000e+08_pr)*exp((-1.720000e+00_pr)*T_log )
    k(r17f) = (9.380000e+06_pr)*exp((-7.600000e-01_pr)*T_log )
    k(r18f) = (3.750000e+08_pr)*exp((-1.720000e+00_pr)*T_log )
    k(r19f) = (8.300000e+07_pr)*exp((-6.030399e+04_pr)*R_T_inv )
    k(r20f) = (1.000000e+06_pr)*exp((-1.000000e+00_pr)*T_log )
    k(r21f) = (9.000000e+04_pr)*exp((-6.000000e-01_pr)*T_log )
    k(r22f) = (6.000000e+07_pr)*exp((-1.250000e+00_pr)*T_log )
    k(r23f) = (5.500000e+08_pr)*exp((-2.000000e+00_pr)*T_log )
    k(r24f) = (2.200000e+10_pr)*exp((-2.000000e+00_pr)*T_log )
    k(r25f) = (3.970000e+06_pr)*exp((-2.807464e+03_pr)*R_T_inv )
    k(r26f) = (2.800000e+07_pr)*exp((-4.468512e+03_pr)*R_T_inv )
    k(r27f) = (1.340000e+08_pr)*exp((-2.656840e+03_pr)*R_T_inv )
    k_0(FOr28f) =(3.200000e+15_pr)*exp((-5.146320e+03_pr)*R_T_inv + (-3.140000e+00_pr)*T_log )
    k_inf(FOr28f) =(2.500000e+10_pr)*exp((-8.000000e-01_pr)*T_log )
    FC(FOr28f) = ((1.0_pr - 6.800000e-01_pr)*exp(-Tloc/(7.800000e+01_pr)) + (6.800000e-01_pr)*exp(-Tloc/(1.995000e+03_pr)))&
              + exp(-(5.590000e+03_pr)/Tloc)
    k(r28f) = getlindratecoeff(Tloc, k_0(FOr28f), k_inf(FOr28f),FC(FOr28f), M(mM28),Ploc)
    k_0(FOr29f) =(2.477000e+21_pr)*exp((-1.020896e+04_pr)*R_T_inv + (-4.760000e+00_pr)*T_log )
    k_inf(FOr29f) =(1.270000e+10_pr)*exp((-1.602472e+03_pr)*R_T_inv + (-6.300000e-01_pr)*T_log )
    FC(FOr29f) = ((1.0_pr - 7.830000e-01_pr)*exp(-Tloc/(7.400000e+01_pr)) + (7.830000e-01_pr)*exp(-Tloc/(2.941000e+03_pr)))&
              + exp(-(6.964000e+03_pr)/Tloc)
    k(r29f) = getlindratecoeff(Tloc, k_0(FOr29f), k_inf(FOr29f),FC(FOr29f), M(mM29),Ploc)
    k(r30f) = (6.600000e+02_pr)*exp((-4.535456e+04_pr)*R_T_inv + (1.620000e+00_pr)*T_log )
    k_0(FOr31f) =(1.350000e+12_pr)*exp((-5.962200e+03_pr)*R_T_inv + (-2.570000e+00_pr)*T_log )
    k_inf(FOr31f) =(1.090000e+06_pr)*exp((1.087840e+03_pr)*R_T_inv + (4.800000e-01_pr)*T_log )
    FC(FOr31f) = ((1.0_pr - 7.824000e-01_pr)*exp(-Tloc/(2.710000e+02_pr)) + (7.824000e-01_pr)*exp(-Tloc/(2.755000e+03_pr)))&
              + exp(-(6.570000e+03_pr)/Tloc)
    k(r31f) = getlindratecoeff(Tloc, k_0(FOr31f), k_inf(FOr31f),FC(FOr31f), M(mM31),Ploc)
    k(r32f) = (7.340000e+07_pr)
    k_0(FOr33f) =(2.200000e+18_pr)*exp((-2.326304e+04_pr)*R_T_inv + (-4.800000e+00_pr)*T_log )
    k_inf(FOr33f) =(5.400000e+05_pr)*exp((-1.087840e+04_pr)*R_T_inv + (4.540000e-01_pr)*T_log )
    FC(FOr33f) = ((1.0_pr - 7.580000e-01_pr)*exp(-Tloc/(9.400000e+01_pr)) + (7.580000e-01_pr)*exp(-Tloc/(1.555000e+03_pr)))&
              + exp(-(4.200000e+03_pr)/Tloc)
    k(r33f) = getlindratecoeff(Tloc, k_0(FOr33f), k_inf(FOr33f),FC(FOr33f), M(mM33),Ploc)
    k(r34f) = (2.300000e+04_pr)*exp((-1.370260e+04_pr)*R_T_inv + (1.050000e+00_pr)*T_log )
    k_0(FOr35f) =(8.600000e+16_pr)*exp((-1.265660e+04_pr)*R_T_inv + (-4.000000e+00_pr)*T_log )
    k_inf(FOr35f) =(5.000000e+07_pr)
    FC(FOr35f) = ((1.0_pr - 8.902000e-01_pr)*exp(-Tloc/(1.440000e+02_pr)) + (8.902000e-01_pr)*exp(-Tloc/(2.838000e+03_pr)))&
              + exp(-(4.556900e+04_pr)/Tloc)
    k(r35f) = getlindratecoeff(Tloc, k_0(FOr35f), k_inf(FOr35f),FC(FOr35f), M(mM35),Ploc)
    k(r36f) = (2.000000e+07_pr)
    k(r37f) = (3.200000e+07_pr)
    k(r38f) = (1.600000e+07_pr)
    k(r39f) = (4.200000e+00_pr)*exp((-2.037608e+04_pr)*R_T_inv + (2.100000e+00_pr)*T_log )
    k_0(FOr40f) =(1.200000e+30_pr)*exp((-2.916248e+04_pr)*R_T_inv + (-7.620000e+00_pr)*T_log )
    k_inf(FOr40f) =(1.080000e+06_pr)*exp((-7.614880e+03_pr)*R_T_inv + (4.540000e-01_pr)*T_log )
    FC(FOr40f) = ((1.0_pr - 9.753000e-01_pr)*exp(-Tloc/(2.100000e+02_pr)) + (9.753000e-01_pr)*exp(-Tloc/(9.840000e+02_pr)))&
              + exp(-(4.374000e+03_pr)/Tloc)
    k(r40f) = getlindratecoeff(Tloc, k_0(FOr40f), k_inf(FOr40f),FC(FOr40f), M(mM40),Ploc)
    k_0(FOr41f) =(1.990000e+29_pr)*exp((-2.797004e+04_pr)*R_T_inv + (-7.080000e+00_pr)*T_log )
    k_inf(FOr41f) =(5.210000e+11_pr)*exp((-6.610720e+03_pr)*R_T_inv + (-9.900000e-01_pr)*T_log )
    FC(FOr41f) = ((1.0_pr - 8.422000e-01_pr)*exp(-Tloc/(1.250000e+02_pr)) + (8.422000e-01_pr)*exp(-Tloc/(2.219000e+03_pr)))&
              + exp(-(6.882000e+03_pr)/Tloc)
    k(r41f) = getlindratecoeff(Tloc, k_0(FOr41f), k_inf(FOr41f),FC(FOr41f), M(mM41),Ploc)
    k(r42f) = (2.000000e+06_pr)
    k(r43f) = (1.150000e+02_pr)*exp((-3.150552e+04_pr)*R_T_inv + (1.900000e+00_pr)*T_log )
    k_0(FOr44f) =(5.070000e+15_pr)*exp((-3.529204e+05_pr)*R_T_inv + (-3.420000e+00_pr)*T_log )
    k_inf(FOr44f) =(4.300000e+01_pr)*exp((-3.330464e+05_pr)*R_T_inv + (1.500000e+00_pr)*T_log )
    FC(FOr44f) = ((1.0_pr - 9.320000e-01_pr)*exp(-Tloc/(1.970000e+02_pr)) + (9.320000e-01_pr)*exp(-Tloc/(1.540000e+03_pr)))&
              + exp(-(1.030000e+04_pr)/Tloc)
    k(r44f) = getlindratecoeff(Tloc, k_0(FOr44f), k_inf(FOr44f),FC(FOr44f), M(mM44),Ploc)
    k(r45f) = (2.160000e+02_pr)*exp((-1.435112e+04_pr)*R_T_inv + (1.510000e+00_pr)*T_log )
    k(r46f) = (3.570000e-02_pr)*exp((8.828240e+03_pr)*R_T_inv + (2.400000e+00_pr)*T_log )
    k(r47f) = (2.900000e+07_pr)*exp((2.092000e+03_pr)*R_T_inv )
    k(r48f) = (2.000000e+07_pr)
    k(r49f) = (3.000000e+07_pr)
    k_0(FOr50f) =(2.700000e+26_pr)*exp((-1.297040e+04_pr)*R_T_inv + (-6.300000e+00_pr)*T_log )
    k_inf(FOr50f) =(6.300000e+07_pr)
    FC(FOr50f) = ((1.0_pr - 2.105000e-01_pr)*exp(-Tloc/(8.350000e+01_pr)) + (2.105000e-01_pr)*exp(-Tloc/(5.398000e+03_pr)))&
              + exp(-(8.370000e+03_pr)/Tloc)
    k(r50f) = getlindratecoeff(Tloc, k_0(FOr50f), k_inf(FOr50f),FC(FOr50f), M(mM50),Ploc)
    k(r51f) = (5.600000e+01_pr)*exp((-2.267728e+04_pr)*R_T_inv + (1.600000e+00_pr)*T_log )
    k(r52f) = (2.501000e+07_pr)
    k(r53f) = (1.000000e+02_pr)*exp((-1.305408e+04_pr)*R_T_inv + (1.600000e+00_pr)*T_log )
    k(r54f) = (4.760000e+01_pr)*exp((-2.928800e+02_pr)*R_T_inv + (1.228000e+00_pr)*T_log )
    k(r55f) = (5.000000e+07_pr)
    k(r56f) = (3.430000e+03_pr)*exp((1.870248e+03_pr)*R_T_inv + (1.180000e+00_pr)*T_log )
    k(r57f) = (5.000000e+06_pr)
    k(r58f) = (6.300000e+00_pr)*exp((-6.276000e+03_pr)*R_T_inv + (2.000000e+00_pr)*T_log )
    k(r59f) = (3.540000e+00_pr)*exp((-3.640080e+03_pr)*R_T_inv + (2.120000e+00_pr)*T_log )
    k(r60f) = (2.000000e+07_pr)
    k(r61f) = (1.000000e+06_pr)
    k(r62f) = (2.000000e+07_pr)
    k(r63f) = (1.500000e+08_pr)*exp((-9.874240e+04_pr)*R_T_inv )
    k(r64f) = (1.320000e+07_pr)*exp((-6.276000e+03_pr)*R_T_inv )
    k(r65f) = (5.000000e-01_pr)*exp((-3.025032e+04_pr)*R_T_inv + (2.000000e+00_pr)*T_log )
    k(r66f) = (4.000000e+07_pr)
    k(r67f) = (2.460000e+00_pr)*exp((-3.460168e+04_pr)*R_T_inv + (2.000000e+00_pr)*T_log )
    k(r68f) = (1.500000e+07_pr)*exp((-2.510400e+03_pr)*R_T_inv )
    k(r69f) = (2.800000e+07_pr)
    k(r70f) = (1.200000e+07_pr)
    k(r71f) = (7.000000e+07_pr)
    k_0(FOr72f) =(2.700000e+26_pr)*exp((-1.297040e+04_pr)*R_T_inv + (-6.300000e+00_pr)*T_log )
    k_inf(FOr72f) =(2.000000e+07_pr)
    FC(FOr72f) = ((1.0_pr - 1.507000e-01_pr)*exp(-Tloc/(1.340000e+02_pr)) + (1.507000e-01_pr)*exp(-Tloc/(2.383000e+03_pr)))&
              + exp(-(7.265000e+03_pr)/Tloc)
    k(r72f) = getlindratecoeff(Tloc, k_0(FOr72f), k_inf(FOr72f),FC(FOr72f), M(mM72),Ploc)
    k(r73f) = (3.000000e+07_pr)
    k(r74f) = (1.200000e+07_pr)*exp((2.384880e+03_pr)*R_T_inv )
    k(r75f) = (1.600000e+07_pr)*exp((2.384880e+03_pr)*R_T_inv )
    k(r76f) = (9.000000e+06_pr)
    k(r77f) = (7.000000e+06_pr)
    k(r78f) = (1.400000e+07_pr)
    k(r79f) = (4.000000e+07_pr)*exp((2.301200e+03_pr)*R_T_inv )
    k(r80f) = (2.675000e+07_pr)*exp((-1.204992e+05_pr)*R_T_inv )
    k(r81f) = (3.600000e+04_pr)*exp((-3.740496e+04_pr)*R_T_inv )
    k_0(FOr82f) =(1.770000e+38_pr)*exp((-2.602448e+04_pr)*R_T_inv + (-9.670000e+00_pr)*T_log )
    k_inf(FOr82f) =(2.120000e+10_pr)*exp((-2.594080e+03_pr)*R_T_inv + (-9.700000e-01_pr)*T_log )
    FC(FOr82f) = ((1.0_pr - 5.325000e-01_pr)*exp(-Tloc/(1.510000e+02_pr)) + (5.325000e-01_pr)*exp(-Tloc/(1.038000e+03_pr)))&
              + exp(-(4.970000e+03_pr)/Tloc)
    k(r82f) = getlindratecoeff(Tloc, k_0(FOr82f), k_inf(FOr82f),FC(FOr82f), M(mM82),Ploc)
    k(r83f) = (4.990000e+06_pr)*exp((-4.435040e+04_pr)*R_T_inv + (1.000000e-01_pr)*T_log )
    k(r84f) = (2.648000e+07_pr)
    k(r85f) = (3.320000e-03_pr)*exp((-2.451824e+04_pr)*R_T_inv + (2.810000e+00_pr)*T_log )
    k(r86f) = (1.000000e+01_pr)*exp((-4.158896e+04_pr)*R_T_inv + (1.500000e+00_pr)*T_log )
    k(r87f) = (6.140000e+00_pr)*exp((-4.372280e+04_pr)*R_T_inv + (1.740000e+00_pr)*T_log )
    k(r88f) = (2.244000e+12_pr)*exp((-7.112800e+04_pr)*R_T_inv + (-1.000000e+00_pr)*T_log )
    k(r89f) = (1.870000e+11_pr)*exp((-7.112800e+04_pr)*R_T_inv + (-1.000000e+00_pr)*T_log )
    k(r90f) = (7.600000e+06_pr)*exp((-1.673600e+03_pr)*R_T_inv )
    k(r91f) = (4.280000e-19_pr)*exp((1.476952e+04_pr)*R_T_inv + (7.600000e+00_pr)*T_log )
    k(r92f) = (5.000000e+07_pr)*exp((-6.276000e+03_pr)*R_T_inv )
    k(r93f) = (8.400000e+05_pr)*exp((-1.621300e+04_pr)*R_T_inv )
    k(r1b) = (4.394989e+10_pr)*exp((-4.264723e+05_pr)*R_T_inv + (-6.291977e-01_pr)*T_log )
    k(r2b) = (2.541986e-02_pr)*exp((-2.005684e+04_pr)*R_T_inv + (2.654354e+00_pr)*T_log )
    k(r3b) = (4.099964e+06_pr)*exp((-2.230965e+05_pr)*R_T_inv + (2.329348e-01_pr)*T_log )
    k(r4b) = (3.207234e+09_pr)*exp((-2.876387e+05_pr)*R_T_inv + (-1.192092e-01_pr)*T_log )
    k(r5b) = (8.749333e+00_pr)*exp((-2.421029e+04_pr)*R_T_inv + (1.576585e+00_pr)*T_log )
    k(r6b) = (6.765763e+13_pr)*exp((-5.452929e+05_pr)*R_T_inv + (-7.240914e-01_pr)*T_log )
    k(r7b) = (2.700668e+06_pr)*exp((-3.624646e+05_pr)*R_T_inv + (3.935862e-01_pr)*T_log )
    k(r8b) = (3.453057e+12_pr)*exp((-4.687332e+05_pr)*R_T_inv + (-7.013075e-01_pr)*T_log )
    k(r9b) = (3.009553e+05_pr)*exp((-7.431952e+04_pr)*R_T_inv + (1.587588e-01_pr)*T_log )
    k(r10b) = (2.946285e+03_pr)*exp((-3.378143e+05_pr)*R_T_inv + (1.035779e+00_pr)*T_log )
    k(r11b) = (2.178102e-03_pr)*exp((-1.107041e+05_pr)*R_T_inv + (2.423801e+00_pr)*T_log )
    k(r12b) = (7.067659e-02_pr)*exp((-3.113761e+04_pr)*R_T_inv + (2.201157e+00_pr)*T_log )
    k(r13b) = (1.403150e+10_pr)*exp((-2.362145e+05_pr)*R_T_inv + (-7.580509e-01_pr)*T_log )
    k(r14b) = (3.764327e+06_pr)*exp((-3.771708e+03_pr)*R_T_inv + (-7.417601e-02_pr)*T_log )
    k(r15b) = (1.200593e+12_pr)*exp((-2.033759e+05_pr)*R_T_inv + (-7.221325e-01_pr)*T_log )
    k(r16b) = (1.286350e+14_pr)*exp((-2.033759e+05_pr)*R_T_inv + (-1.582132e+00_pr)*T_log )
    k(r17b) = (4.021986e+12_pr)*exp((-2.033759e+05_pr)*R_T_inv + (-6.221325e-01_pr)*T_log )
    k(r18b) = (1.607937e+14_pr)*exp((-2.033759e+05_pr)*R_T_inv + (-1.582132e+00_pr)*T_log )
    k(r19b) = (3.643423e+05_pr)*exp((9.745283e+03_pr)*R_T_inv + (3.368428e-01_pr)*T_log )
    k(r20b) = (1.728959e+11_pr)*exp((-4.327329e+05_pr)*R_T_inv + (-6.135520e-01_pr)*T_log )
    k(r21b) = (1.556063e+10_pr)*exp((-4.327329e+05_pr)*R_T_inv + (-2.135520e-01_pr)*T_log )
    k(r22b) = (1.037375e+13_pr)*exp((-4.327329e+05_pr)*R_T_inv + (-8.635520e-01_pr)*T_log )
    k(r23b) = (9.509275e+13_pr)*exp((-4.327329e+05_pr)*R_T_inv + (-1.613552e+00_pr)*T_log )
    k(r24b) = (1.387886e+16_pr)*exp((-4.946246e+05_pr)*R_T_inv + (-1.580279e+00_pr)*T_log )
    k(r25b) = (2.563985e+04_pr)*exp((-2.240069e+05_pr)*R_T_inv + (6.186966e-01_pr)*T_log )
    k(r26b) = (1.129029e+07_pr)*exp((-2.338255e+05_pr)*R_T_inv + (2.485805e-01_pr)*T_log )
    k(r27b) = (1.205831e+05_pr)*exp((-1.557040e+05_pr)*R_T_inv + (5.697777e-01_pr)*T_log )
    k_0(FOr28b) =(4.097478e+22_pr)*exp((-4.670319e+05_pr)*R_T_inv + (-3.050625e+00_pr)*T_log )
    k_inf(FOr28b) =(3.201154e+17_pr)*exp((-4.618856e+05_pr)*R_T_inv + (-7.106245e-01_pr)*T_log )
    FC(FOr28b) = ((1.0_pr - 6.800000e-01_pr)*exp(-Tloc/(7.800000e+01_pr)) + (6.800000e-01_pr)*exp(-Tloc/(1.995000e+03_pr)))&
              + exp(-(5.590000e+03_pr)/Tloc)
    k(r28b) = getlindratecoeff(Tloc, k_0(FOr28b), k_inf(FOr28b),FC(FOr28b), M(mM28),Ploc)
    k_0(FOr29b) =(2.538277e+28_pr)*exp((-4.484534e+05_pr)*R_T_inv + (-4.465783e+00_pr)*T_log )
    k_inf(FOr29b) =(1.301418e+17_pr)*exp((-4.398469e+05_pr)*R_T_inv + (-3.357831e-01_pr)*T_log )
    FC(FOr29b) = ((1.0_pr - 7.830000e-01_pr)*exp(-Tloc/(7.400000e+01_pr)) + (7.830000e-01_pr)*exp(-Tloc/(2.941000e+03_pr)))&
              + exp(-(6.964000e+03_pr)/Tloc)
    k(r29b) = getlindratecoeff(Tloc, k_0(FOr29b), k_inf(FOr29b),FC(FOr29b), M(mM29),Ploc)
    k(r30b) = (1.113565e+01_pr)*exp((-3.984297e+04_pr)*R_T_inv + (1.712231e+00_pr)*T_log )
    k_0(FOr31b) =(1.537744e+19_pr)*exp((-3.729264e+05_pr)*R_T_inv + (-2.357956e+00_pr)*T_log )
    k_inf(FOr31b) =(1.241586e+13_pr)*exp((-3.658763e+05_pr)*R_T_inv + (6.920436e-01_pr)*T_log )
    FC(FOr31b) = ((1.0_pr - 7.824000e-01_pr)*exp(-Tloc/(2.710000e+02_pr)) + (7.824000e-01_pr)*exp(-Tloc/(2.755000e+03_pr)))&
              + exp(-(6.570000e+03_pr)/Tloc)
    k(r31b) = getlindratecoeff(Tloc, k_0(FOr31b), k_inf(FOr31b),FC(FOr31b), M(mM31),Ploc)
    k(r32b) = (1.299700e+07_pr)*exp((-3.687251e+05_pr)*R_T_inv + (4.092319e-01_pr)*T_log )
    k_0(FOr33b) =(6.563503e+26_pr)*exp((-1.119211e+05_pr)*R_T_inv + (-5.464977e+00_pr)*T_log )
    k_inf(FOr33b) =(1.611042e+14_pr)*exp((-9.953645e+04_pr)*R_T_inv + (-2.109765e-01_pr)*T_log )
    FC(FOr33b) = ((1.0_pr - 7.580000e-01_pr)*exp(-Tloc/(9.400000e+01_pr)) + (7.580000e-01_pr)*exp(-Tloc/(1.555000e+03_pr)))&
              + exp(-(4.200000e+03_pr)/Tloc)
    k(r33b) = getlindratecoeff(Tloc, k_0(FOr33b), k_inf(FOr33b),FC(FOr33b), M(mM33),Ploc)
    k(r34b) = (3.491099e+02_pr)*exp((-7.947128e+04_pr)*R_T_inv + (1.224404e+00_pr)*T_log )
    k_0(FOr35b) =(3.123351e+21_pr)*exp((-4.489322e+05_pr)*R_T_inv + (-3.160930e+00_pr)*T_log )
    k_inf(FOr35b) =(1.815901e+12_pr)*exp((-4.362756e+05_pr)*R_T_inv + (8.390696e-01_pr)*T_log )
    FC(FOr35b) = ((1.0_pr - 8.902000e-01_pr)*exp(-Tloc/(1.440000e+02_pr)) + (8.902000e-01_pr)*exp(-Tloc/(2.838000e+03_pr)))&
              + exp(-(4.556900e+04_pr)/Tloc)
    k(r35b) = getlindratecoeff(Tloc, k_0(FOr35b), k_inf(FOr35b),FC(FOr35b), M(mM35),Ploc)
    k(r36b) = (1.159049e+04_pr)*exp((-3.440748e+05_pr)*R_T_inv + (1.051425e+00_pr)*T_log )
    k(r37b) = (2.478116e+02_pr)*exp((-5.017563e+04_pr)*R_T_inv + (1.154988e+00_pr)*T_log )
    k(r38b) = (5.794089e+00_pr)*exp((-4.522323e+04_pr)*R_T_inv + (1.593293e+00_pr)*T_log )
    k(r39b) = (1.999456e+01_pr)*exp((-1.683337e+04_pr)*R_T_inv + (1.647378e+00_pr)*T_log )
    k_0(FOr40b) =(6.038157e+35_pr)*exp((-1.790985e+05_pr)*R_T_inv + (-7.579194e+00_pr)*T_log )
    k_inf(FOr40b) =(5.434341e+11_pr)*exp((-1.575509e+05_pr)*R_T_inv + (4.948064e-01_pr)*T_log )
    FC(FOr40b) = ((1.0_pr - 9.753000e-01_pr)*exp(-Tloc/(2.100000e+02_pr)) + (9.753000e-01_pr)*exp(-Tloc/(9.840000e+02_pr)))&
              + exp(-(4.374000e+03_pr)/Tloc)
    k(r40b) = getlindratecoeff(Tloc, k_0(FOr40b), k_inf(FOr40b),FC(FOr40b), M(mM40),Ploc)
    k_0(FOr41b) =(2.222499e+37_pr)*exp((-4.471117e+05_pr)*R_T_inv + (-6.990355e+00_pr)*T_log )
    k_inf(FOr41b) =(5.818703e+19_pr)*exp((-4.257524e+05_pr)*R_T_inv + (-9.003551e-01_pr)*T_log )
    FC(FOr41b) = ((1.0_pr - 8.422000e-01_pr)*exp(-Tloc/(1.250000e+02_pr)) + (8.422000e-01_pr)*exp(-Tloc/(2.219000e+03_pr)))&
              + exp(-(6.882000e+03_pr)/Tloc)
    k(r41b) = getlindratecoeff(Tloc, k_0(FOr41b), k_inf(FOr41b),FC(FOr41b), M(mM41),Ploc)
    k(r42b) = (6.872133e+05_pr)*exp((-2.827968e+05_pr)*R_T_inv + (3.456417e-01_pr)*T_log )
    k(r43b) = (1.780304e-01_pr)*exp((-4.509670e+04_pr)*R_T_inv + (2.196803e+00_pr)*T_log )
    k_0(FOr44b) =(3.261455e+23_pr)*exp((-3.511594e+05_pr)*R_T_inv + (-3.617188e+00_pr)*T_log )
    k_inf(FOr44b) =(2.766126e+09_pr)*exp((-3.312854e+05_pr)*R_T_inv + (1.302812e+00_pr)*T_log )
    FC(FOr44b) = ((1.0_pr - 9.320000e-01_pr)*exp(-Tloc/(1.970000e+02_pr)) + (9.320000e-01_pr)*exp(-Tloc/(1.540000e+03_pr)))&
              + exp(-(1.030000e+04_pr)/Tloc)
    k(r44b) = getlindratecoeff(Tloc, k_0(FOr44b), k_inf(FOr44b),FC(FOr44b), M(mM44),Ploc)
    k(r45b) = (7.881342e+02_pr)*exp((-7.624287e+04_pr)*R_T_inv + (1.543273e+00_pr)*T_log )
    k(r46b) = (2.562191e-01_pr)*exp((-5.932403e+04_pr)*R_T_inv + (2.448919e+00_pr)*T_log )
    k(r47b) = (4.266693e+07_pr)*exp((-2.891567e+05_pr)*R_T_inv + (2.818537e-01_pr)*T_log )
    k(r48b) = (1.108439e+11_pr)*exp((-3.230519e+05_pr)*R_T_inv + (-4.006360e-01_pr)*T_log )
    k(r49b) = (1.751759e+11_pr)*exp((-3.607433e+05_pr)*R_T_inv + (-5.085952e-01_pr)*T_log )
    k_0(FOr50b) =(1.266235e+36_pr)*exp((-3.990703e+05_pr)*R_T_inv + (-6.615918e+00_pr)*T_log )
    k_inf(FOr50b) =(2.954550e+17_pr)*exp((-3.860999e+05_pr)*R_T_inv + (-3.159185e-01_pr)*T_log )
    FC(FOr50b) = ((1.0_pr - 2.105000e-01_pr)*exp(-Tloc/(8.350000e+01_pr)) + (2.105000e-01_pr)*exp(-Tloc/(5.398000e+03_pr)))&
              + exp(-(8.370000e+03_pr)/Tloc)
    k(r50b) = getlindratecoeff(Tloc, k_0(FOr50b), k_inf(FOr50b),FC(FOr50b), M(mM50),Ploc)
    k(r51b) = (2.759006e+00_pr)*exp((-5.541631e+04_pr)*R_T_inv + (1.930346e+00_pr)*T_log )
    k(r52b) = (1.169519e+06_pr)*exp((4.952396e+03_pr)*R_T_inv + (4.383049e-01_pr)*T_log )
    k(r53b) = (6.156277e+00_pr)*exp((-6.943424e+04_pr)*R_T_inv + (1.725504e+00_pr)*T_log )
    k(r54b) = (6.086105e+07_pr)*exp((-1.065614e+05_pr)*R_T_inv + (1.331063e-01_pr)*T_log )
    k(r55b) = (3.230452e+07_pr)*exp((-4.306169e+05_pr)*R_T_inv + (4.425051e-01_pr)*T_log )
    k(r56b) = (1.899656e+02_pr)*exp((-1.257902e+05_pr)*R_T_inv + (1.387678e+00_pr)*T_log )
    k(r57b) = (1.057276e+04_pr)*exp((-4.059666e+05_pr)*R_T_inv + (1.084698e+00_pr)*T_log )
    k(r58b) = (1.094333e+02_pr)*exp((-6.462504e+04_pr)*R_T_inv + (1.580652e+00_pr)*T_log )
    k(r59b) = (1.999613e-02_pr)*exp((-7.912301e+04_pr)*R_T_inv + (2.450076e+00_pr)*T_log )
    k(r60b) = (9.974555e+07_pr)*exp((-4.760991e+05_pr)*R_T_inv + (1.691416e-01_pr)*T_log )
    k(r61b) = (2.389875e+07_pr)*exp((-2.348686e+05_pr)*R_T_inv + (1.563495e-01_pr)*T_log )
    k(r62b) = (2.324020e+09_pr)*exp((-1.028715e+05_pr)*R_T_inv + (-5.852104e-01_pr)*T_log )
    k(r63b) = (1.725859e+11_pr)*exp((-3.580581e+05_pr)*R_T_inv + (-5.251160e-01_pr)*T_log )
    k(r64b) = (2.478134e+06_pr)*exp((-3.187868e+05_pr)*R_T_inv + (9.496560e-02_pr)*T_log )
    k(r65b) = (3.702985e+01_pr)*exp((-5.940304e+04_pr)*R_T_inv + (1.702927e+00_pr)*T_log )
    k(r66b) = (1.508003e+13_pr)*exp((-2.727764e+05_pr)*R_T_inv + (-8.356787e-01_pr)*T_log )
    k(r67b) = (3.073893e+00_pr)*exp((-5.824281e+04_pr)*R_T_inv + (1.795159e+00_pr)*T_log )
    k(r68b) = (1.580383e+07_pr)*exp((-4.020182e+04_pr)*R_T_inv + (-1.079592e-01_pr)*T_log )
    k(r69b) = (5.672064e+00_pr)*exp((-2.861945e+05_pr)*R_T_inv + (9.790592e-03_pr)*T_log )
    k(r70b) = (1.533545e+06_pr)*exp((-7.808191e+05_pr)*R_T_inv + (4.295115e-01_pr)*T_log )
    k(r71b) = (5.461991e+09_pr)*exp((-6.684415e+04_pr)*R_T_inv + (-4.050317e-01_pr)*T_log )
    k_0(FOr72b) =(2.707827e+37_pr)*exp((-4.040227e+05_pr)*R_T_inv + (-7.054223e+00_pr)*T_log )
    k_inf(FOr72b) =(2.005798e+18_pr)*exp((-3.910523e+05_pr)*R_T_inv + (-7.542234e-01_pr)*T_log )
    FC(FOr72b) = ((1.0_pr - 1.507000e-01_pr)*exp(-Tloc/(1.340000e+02_pr)) + (1.507000e-01_pr)*exp(-Tloc/(2.383000e+03_pr)))&
              + exp(-(7.265000e+03_pr)/Tloc)
    k(r72b) = getlindratecoeff(Tloc, k_0(FOr72b), k_inf(FOr72b),FC(FOr72b), M(mM72),Ploc)
    k(r73b) = (3.160766e+07_pr)*exp((-3.769142e+04_pr)*R_T_inv + (-1.079592e-01_pr)*T_log )
    k(r74b) = (4.766444e+12_pr)*exp((-3.080829e+05_pr)*R_T_inv + (-9.436379e-01_pr)*T_log )
    k(r75b) = (2.106418e+07_pr)*exp((-5.894767e+04_pr)*R_T_inv + (-3.128007e-01_pr)*T_log )
    k(r76b) = (9.482297e+06_pr)*exp((-3.769142e+04_pr)*R_T_inv + (-1.079592e-01_pr)*T_log )
    k(r77b) = (7.375120e+06_pr)*exp((-3.769142e+04_pr)*R_T_inv + (-1.079592e-01_pr)*T_log )
    k(r78b) = (6.393646e+04_pr)*exp((-2.544748e+05_pr)*R_T_inv + (5.862985e-01_pr)*T_log )
    k(r79b) = (4.831802e+06_pr)*exp((-7.813412e+04_pr)*R_T_inv + (-1.082286e-01_pr)*T_log )
    k(r80b) = (1.516295e+10_pr)*exp((-2.742968e+02_pr)*R_T_inv + (-8.181452e-01_pr)*T_log )
    k(r81b) = (6.012252e+03_pr)*exp((-2.549943e+05_pr)*R_T_inv + (2.176337e-01_pr)*T_log )
    k_0(FOr82b) =(2.928603e+50_pr)*exp((-4.059930e+05_pr)*R_T_inv + (-1.046460e+01_pr)*T_log )
    k_inf(FOr82b) =(3.507706e+22_pr)*exp((-3.825626e+05_pr)*R_T_inv + (-1.764603e+00_pr)*T_log )
    FC(FOr82b) = ((1.0_pr - 5.325000e-01_pr)*exp(-Tloc/(1.510000e+02_pr)) + (5.325000e-01_pr)*exp(-Tloc/(1.038000e+03_pr)))&
              + exp(-(4.970000e+03_pr)/Tloc)
    k(r82b) = getlindratecoeff(Tloc, k_0(FOr82b), k_inf(FOr82b),FC(FOr82b), M(mM82),Ploc)
    k(r83b) = (7.392636e+10_pr)*exp((-5.177275e+03_pr)*R_T_inv + (-7.842478e-01_pr)*T_log )
    k(r84b) = (2.779030e+08_pr)*exp((-3.742367e+05_pr)*R_T_inv + (3.170008e-01_pr)*T_log )
    k(r85b) = (2.986763e-03_pr)*exp((-9.579852e+04_pr)*R_T_inv + (2.892173e+00_pr)*T_log )
    k(r86b) = (2.821569e+03_pr)*exp((-4.355784e+04_pr)*R_T_inv + (9.551473e-01_pr)*T_log )
    k(r87b) = (5.633689e-01_pr)*exp((-6.282557e+04_pr)*R_T_inv + (1.944572e+00_pr)*T_log )
    k(r88b) = (2.298185e+06_pr)*exp((-7.120282e+03_pr)*R_T_inv + (-9.772162e-01_pr)*T_log )
    k(r89b) = (1.915154e+05_pr)*exp((-7.120282e+03_pr)*R_T_inv + (-9.772162e-01_pr)*T_log )
    k(r90b) = (3.337440e+06_pr)*exp((-1.410418e+05_pr)*R_T_inv + (1.606514e-01_pr)*T_log )
    k(r91b) = (6.151323e-22_pr)*exp((-9.994832e+04_pr)*R_T_inv + (8.402844e+00_pr)*T_log )
    k(r92b) = (8.933764e+04_pr)*exp((-6.389267e+05_pr)*R_T_inv + (8.880337e-01_pr)*T_log )
    k(r93b) = (7.158036e+05_pr)*exp((-6.965283e+04_pr)*R_T_inv + (9.706116e-02_pr)*T_log )
  
    return
  end subroutine get_rate_coefficients

  ! ----------------------------------------------- !
  ! Evaluate reaction rates                         !
  ! ----------------------------------------------- !
  subroutine get_reaction_rates(w,k,m,c,cqss)
    implicit none

    real(pr), dimension(nspec) :: c
    real(pr), dimension(nqss) :: cqss
    real(pr), dimension(nreac + nreac_reverse) :: w,k
    real(pr), dimension(nTB + nFO) :: m

    w(r1f) = k(r1f) * c(sH) * cqss(sqssO) * m(mM1)
    w(r2f) = k(r2f) * c(sH2) * cqss(sqssO) 
    w(r3f) = k(r3f) * c(sHO2) * cqss(sqssO) 
    w(r4f) = k(r4f) * c(sCH3) * cqss(sqssO) 
    w(r5f) = k(r5f) * c(sCH4) * cqss(sqssO) 
    w(r6f) = k(r6f) * c(sCO) * cqss(sqssO) * m(mM6)
    w(r7f) = k(r7f) * c(sHCO) * cqss(sqssO) 
    w(r8f) = k(r8f) * c(sHCO) * cqss(sqssO) 
    w(r9f) = k(r9f) * c(sCH2O) * cqss(sqssO) 
    w(r10f) = k(r10f) * c(sCH3O) * cqss(sqssO) 
    w(r11f) = k(r11f) * c(sC2H4) * cqss(sqssO) 
    w(r12f) = k(r12f) * c(sC2H6) * cqss(sqssO) 
    w(r13f) = k(r13f) * c(sCO) * c(sO2) 
    w(r14f) = k(r14f) * c(sCH2O) * c(sO2) 
    w(r15f) = k(r15f) * c(sH) * c(sO2) * m(mM15)
    w(r16f) = k(r16f) * c(sH) * c(sO2)**2.0_pr 
    w(r17f) = k(r17f) * c(sH) * c(sH2O) * c(sO2) 
    w(r18f) = k(r18f) * c(sH) * c(sN2) * c(sO2) 
    w(r19f) = k(r19f) * c(sH) * c(sO2) 
    w(r20f) = k(r20f) * c(sH)**2.0_pr * m(mM20)
    w(r21f) = k(r21f) * c(sH)**2.0_pr * c(sH2) 
    w(r22f) = k(r22f) * c(sH)**2.0_pr * c(sH2O) 
    w(r23f) = k(r23f) * c(sCO2) * c(sH)**2.0_pr 
    w(r24f) = k(r24f) * c(sH) * c(sOH) * m(mM24)
    w(r25f) = k(r25f) * c(sH) * c(sHO2) 
    w(r26f) = k(r26f) * c(sH) * c(sHO2) 
    w(r27f) = k(r27f) * c(sH) * c(sHO2) 
    w(r28f) = k(r28f) * cqss(sqssCH2) * c(sH) 
    w(r29f) = k(r29f) * c(sCH3) * c(sH) 
    w(r30f) = k(r30f) * c(sCH4) * c(sH) 
    w(r31f) = k(r31f) * c(sH) * c(sHCO) 
    w(r32f) = k(r32f) * c(sH) * c(sHCO) 
    w(r33f) = k(r33f) * c(sCH2O) * c(sH) 
    w(r34f) = k(r34f) * c(sCH2O) * c(sH) 
    w(r35f) = k(r35f) * c(sCH3O) * c(sH) 
    w(r36f) = k(r36f) * c(sCH3O) * c(sH) 
    w(r37f) = k(r37f) * c(sCH3O) * c(sH) 
    w(r38f) = k(r38f) * c(sCH3O) * c(sH) 
    w(r39f) = k(r39f) * cqss(sqssCH3OH) * c(sH) 
    w(r40f) = k(r40f) * c(sC2H4) * c(sH) 
    w(r41f) = k(r41f) * cqss(sqssC2H5) * c(sH) 
    w(r42f) = k(r42f) * cqss(sqssC2H5) * c(sH) 
    w(r43f) = k(r43f) * c(sC2H6) * c(sH) 
    w(r44f) = k(r44f) * c(sCO) * c(sH2) 
    w(r45f) = k(r45f) * c(sH2) * c(sOH) 
    w(r46f) = k(r46f) * c(sOH)**2.0_pr 
    w(r47f) = k(r47f) * c(sHO2) * c(sOH) 
    w(r48f) = k(r48f) * cqss(sqssCH2) * c(sOH) 
    w(r49f) = k(r49f) * cqss(sqssCH2GSG) * c(sOH) 
    w(r50f) = k(r50f) * c(sCH3) * c(sOH) 
    w(r51f) = k(r51f) * c(sCH3) * c(sOH) 
    w(r52f) = k(r52f) * c(sCH3) * c(sOH) 
    w(r53f) = k(r53f) * c(sCH4) * c(sOH) 
    w(r54f) = k(r54f) * c(sCO) * c(sOH) 
    w(r55f) = k(r55f) * c(sHCO) * c(sOH) 
    w(r56f) = k(r56f) * c(sCH2O) * c(sOH) 
    w(r57f) = k(r57f) * c(sCH3O) * c(sOH) 
    w(r58f) = k(r58f) * cqss(sqssCH3OH) * c(sOH) 
    w(r59f) = k(r59f) * c(sC2H6) * c(sOH) 
    w(r60f) = k(r60f) * cqss(sqssCH2) * c(sHO2) 
    w(r61f) = k(r61f) * c(sCH3) * c(sHO2) 
    w(r62f) = k(r62f) * c(sCH3) * c(sHO2) 
    w(r63f) = k(r63f) * c(sCO) * c(sHO2) 
    w(r64f) = k(r64f) * cqss(sqssCH2) * c(sO2) 
    w(r65f) = k(r65f) * cqss(sqssCH2) * c(sH2) 
    w(r66f) = k(r66f) * cqss(sqssCH2) * c(sCH3) 
    w(r67f) = k(r67f) * cqss(sqssCH2) * c(sCH4) 
    w(r68f) = k(r68f) * cqss(sqssCH2GSG) * c(sN2) 
    w(r69f) = k(r69f) * cqss(sqssCH2GSG) * c(sO2) 
    w(r70f) = k(r70f) * cqss(sqssCH2GSG) * c(sO2) 
    w(r71f) = k(r71f) * cqss(sqssCH2GSG) * c(sH2) 
    w(r72f) = k(r72f) * cqss(sqssCH2GSG) * c(sH2O) 
    w(r73f) = k(r73f) * cqss(sqssCH2GSG) * c(sH2O) 
    w(r74f) = k(r74f) * cqss(sqssCH2GSG) * c(sCH3) 
    w(r75f) = k(r75f) * cqss(sqssCH2GSG) * c(sCH4) 
    w(r76f) = k(r76f) * cqss(sqssCH2GSG) * c(sCO) 
    w(r77f) = k(r77f) * cqss(sqssCH2GSG) * c(sCO2) 
    w(r78f) = k(r78f) * cqss(sqssCH2GSG) * c(sCO2) 
    w(r79f) = k(r79f) * c(sC2H6) * cqss(sqssCH2GSG) 
    w(r80f) = k(r80f) * c(sCH3) * c(sO2) 
    w(r81f) = k(r81f) * c(sCH3) * c(sO2) 
    w(r82f) = k(r82f) * c(sCH3)**2.0_pr 
    w(r83f) = k(r83f) * c(sCH3)**2.0_pr 
    w(r84f) = k(r84f) * c(sCH3) * c(sHCO) 
    w(r85f) = k(r85f) * c(sCH2O) * c(sCH3) 
    w(r86f) = k(r86f) * c(sCH3) * cqss(sqssCH3OH) 
    w(r87f) = k(r87f) * c(sC2H6) * c(sCH3) 
    w(r88f) = k(r88f) * c(sH2O) * c(sHCO) 
    w(r89f) = k(r89f) * c(sHCO) * m(mM89)
    w(r90f) = k(r90f) * c(sHCO) * c(sO2) 
    w(r91f) = k(r91f) * c(sCH3O) * c(sO2) 
    w(r92f) = k(r92f) * cqss(sqssC2H) * c(sO2) 
    w(r93f) = k(r93f) * cqss(sqssC2H5) * c(sO2) 
    w(r1b) = k(r1b) * c(sOH) * m(mM1)
    w(r2b) = k(r2b) * c(sH) * c(sOH) 
    w(r3b) = k(r3b) * c(sO2) * c(sOH) 
    w(r4b) = k(r4b) * c(sCH2O) * c(sH) 
    w(r5b) = k(r5b) * c(sCH3) * c(sOH) 
    w(r6b) = k(r6b) * c(sCO2) * m(mM6)
    w(r7b) = k(r7b) * c(sCO) * c(sOH) 
    w(r8b) = k(r8b) * c(sCO2) * c(sH) 
    w(r9b) = k(r9b) * c(sHCO) * c(sOH) 
    w(r10b) = k(r10b) * c(sCH2O) * c(sOH) 
    w(r11b) = k(r11b) * c(sCH3) * c(sHCO) 
    w(r12b) = k(r12b) * cqss(sqssC2H5) * c(sOH) 
    w(r13b) = k(r13b) * c(sCO2) * cqss(sqssO) 
    w(r14b) = k(r14b) * c(sHCO) * c(sHO2) 
    w(r15b) = k(r15b) * c(sHO2) * m(mM15)
    w(r16b) = k(r16b) * c(sHO2) * c(sO2) 
    w(r17b) = k(r17b) * c(sH2O) * c(sHO2) 
    w(r18b) = k(r18b) * c(sHO2) * c(sN2) 
    w(r19b) = k(r19b) * cqss(sqssO) * c(sOH) 
    w(r20b) = k(r20b) * c(sH2) * m(mM20)
    w(r21b) = k(r21b) * c(sH2)**2.0_pr 
    w(r22b) = k(r22b) * c(sH2) * c(sH2O) 
    w(r23b) = k(r23b) * c(sCO2) * c(sH2) 
    w(r24b) = k(r24b) * c(sH2O) * m(mM24)
    w(r25b) = k(r25b) * c(sH2O) * cqss(sqssO) 
    w(r26b) = k(r26b) * c(sH2) * c(sO2) 
    w(r27b) = k(r27b) * c(sOH)**2.0_pr 
    w(r28b) = k(r28b) * c(sCH3) 
    w(r29b) = k(r29b) * c(sCH4) 
    w(r30b) = k(r30b) * c(sCH3) * c(sH2) 
    w(r31b) = k(r31b) * c(sCH2O) 
    w(r32b) = k(r32b) * c(sCO) * c(sH2) 
    w(r33b) = k(r33b) * c(sCH3O) 
    w(r34b) = k(r34b) * c(sH2) * c(sHCO) 
    w(r35b) = k(r35b) * cqss(sqssCH3OH) 
    w(r36b) = k(r36b) * c(sCH2O) * c(sH2) 
    w(r37b) = k(r37b) * c(sCH3) * c(sOH) 
    w(r38b) = k(r38b) * cqss(sqssCH2GSG) * c(sH2O) 
    w(r39b) = k(r39b) * c(sCH3O) * c(sH2) 
    w(r40b) = k(r40b) * cqss(sqssC2H5) 
    w(r41b) = k(r41b) * c(sC2H6) 
    w(r42b) = k(r42b) * c(sC2H4) * c(sH2) 
    w(r43b) = k(r43b) * cqss(sqssC2H5) * c(sH2) 
    w(r44b) = k(r44b) * c(sCH2O) 
    w(r45b) = k(r45b) * c(sH) * c(sH2O) 
    w(r46b) = k(r46b) * c(sH2O) * cqss(sqssO) 
    w(r47b) = k(r47b) * c(sH2O) * c(sO2) 
    w(r48b) = k(r48b) * c(sCH2O) * c(sH) 
    w(r49b) = k(r49b) * c(sCH2O) * c(sH) 
    w(r50b) = k(r50b) * cqss(sqssCH3OH) 
    w(r51b) = k(r51b) * cqss(sqssCH2) * c(sH2O) 
    w(r52b) = k(r52b) * cqss(sqssCH2GSG) * c(sH2O) 
    w(r53b) = k(r53b) * c(sCH3) * c(sH2O) 
    w(r54b) = k(r54b) * c(sCO2) * c(sH) 
    w(r55b) = k(r55b) * c(sCO) * c(sH2O) 
    w(r56b) = k(r56b) * c(sH2O) * c(sHCO) 
    w(r57b) = k(r57b) * c(sCH2O) * c(sH2O) 
    w(r58b) = k(r58b) * c(sCH3O) * c(sH2O) 
    w(r59b) = k(r59b) * cqss(sqssC2H5) * c(sH2O) 
    w(r60b) = k(r60b) * c(sCH2O) * c(sOH) 
    w(r61b) = k(r61b) * c(sCH4) * c(sO2) 
    w(r62b) = k(r62b) * c(sCH3O) * c(sOH) 
    w(r63b) = k(r63b) * c(sCO2) * c(sOH) 
    w(r64b) = k(r64b) * c(sHCO) * c(sOH) 
    w(r65b) = k(r65b) * c(sCH3) * c(sH) 
    w(r66b) = k(r66b) * c(sC2H4) * c(sH) 
    w(r67b) = k(r67b) * c(sCH3)**2.0_pr 
    w(r68b) = k(r68b) * cqss(sqssCH2) * c(sN2) 
    w(r69b) = k(r69b) * c(sCO) * c(sH) * c(sOH) 
    w(r70b) = k(r70b) * c(sCO) * c(sH2O) 
    w(r71b) = k(r71b) * c(sCH3) * c(sH) 
    w(r72b) = k(r72b) * cqss(sqssCH3OH) 
    w(r73b) = k(r73b) * cqss(sqssCH2) * c(sH2O) 
    w(r74b) = k(r74b) * c(sC2H4) * c(sH) 
    w(r75b) = k(r75b) * c(sCH3)**2.0_pr 
    w(r76b) = k(r76b) * cqss(sqssCH2) * c(sCO) 
    w(r77b) = k(r77b) * cqss(sqssCH2) * c(sCO2) 
    w(r78b) = k(r78b) * c(sCH2O) * c(sCO) 
    w(r79b) = k(r79b) * cqss(sqssC2H5) * c(sCH3) 
    w(r80b) = k(r80b) * c(sCH3O) * cqss(sqssO) 
    w(r81b) = k(r81b) * c(sCH2O) * c(sOH) 
    w(r82b) = k(r82b) * c(sC2H6) 
    w(r83b) = k(r83b) * cqss(sqssC2H5) * c(sH) 
    w(r84b) = k(r84b) * c(sCH4) * c(sCO) 
    w(r85b) = k(r85b) * c(sCH4) * c(sHCO) 
    w(r86b) = k(r86b) * c(sCH3O) * c(sCH4) 
    w(r87b) = k(r87b) * cqss(sqssC2H5) * c(sCH4) 
    w(r88b) = k(r88b) * c(sCO) * c(sH) * c(sH2O) 
    w(r89b) = k(r89b) * c(sCO) * c(sH) * m(mM89)
    w(r90b) = k(r90b) * c(sCO) * c(sHO2) 
    w(r91b) = k(r91b) * c(sCH2O) * c(sHO2) 
    w(r92b) = k(r92b) * c(sCO) * c(sHCO) 
    w(r93b) = k(r93b) * c(sC2H4) * c(sHO2) 
  
    return
  end subroutine get_reaction_rates
  
  ! ----------------------------------------------- !
  ! Evaluate production rates                       !
  ! ----------------------------------------------- !
  subroutine get_production_rates(cdot,w)
    implicit none

    real(pr), dimension(nspec) :: cdot
    real(pr), dimension(nreac + nreac_reverse) :: w

    cdot(sH2) = 0.0_pr &
         - w(r2f) &
         + w(r2b) &
         + w(r20f) &
         - w(r20b) &
         + w(r21f) &
         - w(r21b) &
         + w(r22f) &
         - w(r22b) &
         + w(r23f) &
         - w(r23b) &
         + w(r26f) &
         - w(r26b) &
         + w(r30f) &
         - w(r30b) &
         + w(r32f) &
         - w(r32b) &
         + w(r34f) &
         - w(r34b) &
         + w(r36f) &
         - w(r36b) &
         + w(r39f) &
         - w(r39b) &
         + w(r42f) &
         - w(r42b) &
         + w(r43f) &
         - w(r43b) &
         - w(r44f) &
         + w(r44b) &
         - w(r45f) &
         + w(r45b) &
         - w(r65f) &
         + w(r65b) &
         - w(r71f) &
         + w(r71b) 

    cdot(sH) = 0.0_pr &
         - w(r1f) &
         + w(r1b) &
         + w(r2f) &
         - w(r2b) &
         + w(r4f) &
         - w(r4b) &
         + w(r8f) &
         - w(r8b) &
         - w(r15f) &
         + w(r15b) &
         - w(r16f) &
         + w(r16b) &
         - w(r17f) &
         + w(r17b) &
         - w(r18f) &
         + w(r18b) &
         - w(r19f) &
         + w(r19b) &
         -2.0_pr * w(r20f) &
         + 2.0_pr * w(r20b) &
         -2.0_pr * w(r21f) &
         + 2.0_pr * w(r21b) &
         -2.0_pr * w(r22f) &
         + 2.0_pr * w(r22b) &
         -2.0_pr * w(r23f) &
         + 2.0_pr * w(r23b) &
         - w(r24f) &
         + w(r24b) &
         - w(r25f) &
         + w(r25b) &
         - w(r26f) &
         + w(r26b) &
         - w(r27f) &
         + w(r27b) &
         - w(r28f) &
         + w(r28b) &
         - w(r29f) &
         + w(r29b) &
         - w(r30f) &
         + w(r30b) &
         - w(r31f) &
         + w(r31b) &
         - w(r32f) &
         + w(r32b) &
         - w(r33f) &
         + w(r33b) &
         - w(r34f) &
         + w(r34b) &
         - w(r35f) &
         + w(r35b) &
         - w(r36f) &
         + w(r36b) &
         - w(r37f) &
         + w(r37b) &
         - w(r38f) &
         + w(r38b) &
         - w(r39f) &
         + w(r39b) &
         - w(r40f) &
         + w(r40b) &
         - w(r41f) &
         + w(r41b) &
         - w(r42f) &
         + w(r42b) &
         - w(r43f) &
         + w(r43b) &
         + w(r45f) &
         - w(r45b) &
         + w(r48f) &
         - w(r48b) &
         + w(r49f) &
         - w(r49b) &
         + w(r54f) &
         - w(r54b) &
         + w(r65f) &
         - w(r65b) &
         + w(r66f) &
         - w(r66b) &
         + w(r69f) &
         - w(r69b) &
         + w(r71f) &
         - w(r71b) &
         + w(r74f) &
         - w(r74b) &
         + w(r83f) &
         - w(r83b) &
         + w(r88f) &
         - w(r88b) &
         + w(r89f) &
         - w(r89b) 

    cdot(sO2) = 0.0_pr &
         + w(r3f) &
         - w(r3b) &
         - w(r13f) &
         + w(r13b) &
         - w(r14f) &
         + w(r14b) &
         - w(r15f) &
         + w(r15b) &
         - w(r16f) &
         + w(r16b) &
         - w(r17f) &
         + w(r17b) &
         - w(r18f) &
         + w(r18b) &
         - w(r19f) &
         + w(r19b) &
         + w(r26f) &
         - w(r26b) &
         + w(r47f) &
         - w(r47b) &
         + w(r61f) &
         - w(r61b) &
         - w(r64f) &
         + w(r64b) &
         - w(r69f) &
         + w(r69b) &
         - w(r70f) &
         + w(r70b) &
         - w(r80f) &
         + w(r80b) &
         - w(r81f) &
         + w(r81b) &
         - w(r90f) &
         + w(r90b) &
         - w(r91f) &
         + w(r91b) &
         - w(r92f) &
         + w(r92b) &
         - w(r93f) &
         + w(r93b) 

    cdot(sOH) = 0.0_pr &
         + w(r1f) &
         - w(r1b) &
         + w(r2f) &
         - w(r2b) &
         + w(r3f) &
         - w(r3b) &
         + w(r5f) &
         - w(r5b) &
         + w(r7f) &
         - w(r7b) &
         + w(r9f) &
         - w(r9b) &
         + w(r10f) &
         - w(r10b) &
         + w(r12f) &
         - w(r12b) &
         + w(r19f) &
         - w(r19b) &
         - w(r24f) &
         + w(r24b) &
         + 2.0_pr * w(r27f) &
         - 2.0_pr * w(r27b) &
         + w(r37f) &
         - w(r37b) &
         - w(r45f) &
         + w(r45b) &
         -2.0_pr * w(r46f) &
         + 2.0_pr * w(r46b) &
         - w(r47f) &
         + w(r47b) &
         - w(r48f) &
         + w(r48b) &
         - w(r49f) &
         + w(r49b) &
         - w(r50f) &
         + w(r50b) &
         - w(r51f) &
         + w(r51b) &
         - w(r52f) &
         + w(r52b) &
         - w(r53f) &
         + w(r53b) &
         - w(r54f) &
         + w(r54b) &
         - w(r55f) &
         + w(r55b) &
         - w(r56f) &
         + w(r56b) &
         - w(r57f) &
         + w(r57b) &
         - w(r58f) &
         + w(r58b) &
         - w(r59f) &
         + w(r59b) &
         + w(r60f) &
         - w(r60b) &
         + w(r62f) &
         - w(r62b) &
         + w(r63f) &
         - w(r63b) &
         + w(r64f) &
         - w(r64b) &
         + w(r69f) &
         - w(r69b) &
         + w(r81f) &
         - w(r81b) 

    cdot(sH2O) = 0.0_pr &
         + w(r24f) &
         - w(r24b) &
         + w(r25f) &
         - w(r25b) &
         + w(r38f) &
         - w(r38b) &
         + w(r45f) &
         - w(r45b) &
         + w(r46f) &
         - w(r46b) &
         + w(r47f) &
         - w(r47b) &
         + w(r51f) &
         - w(r51b) &
         + w(r52f) &
         - w(r52b) &
         + w(r53f) &
         - w(r53b) &
         + w(r55f) &
         - w(r55b) &
         + w(r56f) &
         - w(r56b) &
         + w(r57f) &
         - w(r57b) &
         + w(r58f) &
         - w(r58b) &
         + w(r59f) &
         - w(r59b) &
         + w(r70f) &
         - w(r70b) &
         - w(r72f) &
         + w(r72b) 

    cdot(sHO2) = 0.0_pr &
         - w(r3f) &
         + w(r3b) &
         + w(r14f) &
         - w(r14b) &
         + w(r15f) &
         - w(r15b) &
         + w(r16f) &
         - w(r16b) &
         + w(r17f) &
         - w(r17b) &
         + w(r18f) &
         - w(r18b) &
         - w(r25f) &
         + w(r25b) &
         - w(r26f) &
         + w(r26b) &
         - w(r27f) &
         + w(r27b) &
         - w(r47f) &
         + w(r47b) &
         - w(r60f) &
         + w(r60b) &
         - w(r61f) &
         + w(r61b) &
         - w(r62f) &
         + w(r62b) &
         - w(r63f) &
         + w(r63b) &
         + w(r90f) &
         - w(r90b) &
         + w(r91f) &
         - w(r91b) &
         + w(r93f) &
         - w(r93b) 

    cdot(sCH3) = 0.0_pr &
         - w(r4f) &
         + w(r4b) &
         + w(r5f) &
         - w(r5b) &
         + w(r11f) &
         - w(r11b) &
         + w(r28f) &
         - w(r28b) &
         - w(r29f) &
         + w(r29b) &
         + w(r30f) &
         - w(r30b) &
         + w(r37f) &
         - w(r37b) &
         - w(r50f) &
         + w(r50b) &
         - w(r51f) &
         + w(r51b) &
         - w(r52f) &
         + w(r52b) &
         + w(r53f) &
         - w(r53b) &
         - w(r61f) &
         + w(r61b) &
         - w(r62f) &
         + w(r62b) &
         + w(r65f) &
         - w(r65b) &
         - w(r66f) &
         + w(r66b) &
         + 2.0_pr * w(r67f) &
         - 2.0_pr * w(r67b) &
         + w(r71f) &
         - w(r71b) &
         - w(r74f) &
         + w(r74b) &
         + 2.0_pr * w(r75f) &
         - 2.0_pr * w(r75b) &
         + w(r79f) &
         - w(r79b) &
         - w(r80f) &
         + w(r80b) &
         - w(r81f) &
         + w(r81b) &
         -2.0_pr * w(r82f) &
         + 2.0_pr * w(r82b) &
         -2.0_pr * w(r83f) &
         + 2.0_pr * w(r83b) &
         - w(r84f) &
         + w(r84b) &
         - w(r85f) &
         + w(r85b) &
         - w(r86f) &
         + w(r86b) &
         - w(r87f) &
         + w(r87b) 

    cdot(sCH4) = 0.0_pr &
         - w(r5f) &
         + w(r5b) &
         + w(r29f) &
         - w(r29b) &
         - w(r30f) &
         + w(r30b) &
         - w(r53f) &
         + w(r53b) &
         + w(r61f) &
         - w(r61b) &
         - w(r67f) &
         + w(r67b) &
         - w(r75f) &
         + w(r75b) &
         + w(r84f) &
         - w(r84b) &
         + w(r85f) &
         - w(r85b) &
         + w(r86f) &
         - w(r86b) &
         + w(r87f) &
         - w(r87b) 

    cdot(sCO) = 0.0_pr &
         - w(r6f) &
         + w(r6b) &
         + w(r7f) &
         - w(r7b) &
         - w(r13f) &
         + w(r13b) &
         + w(r32f) &
         - w(r32b) &
         - w(r44f) &
         + w(r44b) &
         - w(r54f) &
         + w(r54b) &
         + w(r55f) &
         - w(r55b) &
         - w(r63f) &
         + w(r63b) &
         + w(r69f) &
         - w(r69b) &
         + w(r70f) &
         - w(r70b) &
         + w(r78f) &
         - w(r78b) &
         + w(r84f) &
         - w(r84b) &
         + w(r88f) &
         - w(r88b) &
         + w(r89f) &
         - w(r89b) &
         + w(r90f) &
         - w(r90b) &
         + w(r92f) &
         - w(r92b) 

    cdot(sCO2) = 0.0_pr &
         + w(r6f) &
         - w(r6b) &
         + w(r8f) &
         - w(r8b) &
         + w(r13f) &
         - w(r13b) &
         + w(r54f) &
         - w(r54b) &
         + w(r63f) &
         - w(r63b) &
         - w(r78f) &
         + w(r78b) 

    cdot(sHCO) = 0.0_pr &
         - w(r7f) &
         + w(r7b) &
         - w(r8f) &
         + w(r8b) &
         + w(r9f) &
         - w(r9b) &
         + w(r11f) &
         - w(r11b) &
         + w(r14f) &
         - w(r14b) &
         - w(r31f) &
         + w(r31b) &
         - w(r32f) &
         + w(r32b) &
         + w(r34f) &
         - w(r34b) &
         - w(r55f) &
         + w(r55b) &
         + w(r56f) &
         - w(r56b) &
         + w(r64f) &
         - w(r64b) &
         - w(r84f) &
         + w(r84b) &
         + w(r85f) &
         - w(r85b) &
         - w(r88f) &
         + w(r88b) &
         - w(r89f) &
         + w(r89b) &
         - w(r90f) &
         + w(r90b) &
         + w(r92f) &
         - w(r92b) 

    cdot(sCH2O) = 0.0_pr &
         + w(r4f) &
         - w(r4b) &
         - w(r9f) &
         + w(r9b) &
         + w(r10f) &
         - w(r10b) &
         - w(r14f) &
         + w(r14b) &
         + w(r31f) &
         - w(r31b) &
         - w(r33f) &
         + w(r33b) &
         - w(r34f) &
         + w(r34b) &
         + w(r36f) &
         - w(r36b) &
         + w(r44f) &
         - w(r44b) &
         + w(r48f) &
         - w(r48b) &
         + w(r49f) &
         - w(r49b) &
         - w(r56f) &
         + w(r56b) &
         + w(r57f) &
         - w(r57b) &
         + w(r60f) &
         - w(r60b) &
         + w(r78f) &
         - w(r78b) &
         + w(r81f) &
         - w(r81b) &
         - w(r85f) &
         + w(r85b) &
         + w(r91f) &
         - w(r91b) 

    cdot(sCH3O) = 0.0_pr &
         - w(r10f) &
         + w(r10b) &
         + w(r33f) &
         - w(r33b) &
         - w(r35f) &
         + w(r35b) &
         - w(r36f) &
         + w(r36b) &
         - w(r37f) &
         + w(r37b) &
         - w(r38f) &
         + w(r38b) &
         + w(r39f) &
         - w(r39b) &
         - w(r57f) &
         + w(r57b) &
         + w(r58f) &
         - w(r58b) &
         + w(r62f) &
         - w(r62b) &
         + w(r80f) &
         - w(r80b) &
         + w(r86f) &
         - w(r86b) &
         - w(r91f) &
         + w(r91b) 

    cdot(sC2H4) = 0.0_pr &
         - w(r11f) &
         + w(r11b) &
         - w(r40f) &
         + w(r40b) &
         + w(r42f) &
         - w(r42b) &
         + w(r66f) &
         - w(r66b) &
         + w(r74f) &
         - w(r74b) &
         + w(r93f) &
         - w(r93b) 

    cdot(sC2H6) = 0.0_pr &
         - w(r12f) &
         + w(r12b) &
         + w(r41f) &
         - w(r41b) &
         - w(r43f) &
         + w(r43b) &
         - w(r59f) &
         + w(r59b) &
         - w(r79f) &
         + w(r79b) &
         + w(r82f) &
         - w(r82b) &
         - w(r87f) &
         + w(r87b) 

    cdot(sN2) = 0.0_pr 

  
    return
  end subroutine get_production_rates


  ! ----------------------------------------------- !
  ! Evaluation of QSS concentrations                !
  ! ----------------------------------------------- !
  subroutine get_qss(cqss,c,k,M)
    implicit none

    real(pr), dimension(nqss) :: cqss
    real(pr), dimension(nspec) :: c
    real(pr), dimension(nreac + nreac_reverse) :: k
    real(pr), dimension(nTB + nFO) :: M

    integer :: index

    real(pr) :: O_ct
    real(pr) :: O_num
    real(pr) :: O_denom
    real(pr) :: O_C2H5
    real(pr) :: CH2_ct
    real(pr) :: CH2_num
    real(pr) :: CH2_denom
    real(pr) :: CH2_CH2GSG
    real(pr) :: CH2GSG_ct
    real(pr) :: CH2GSG_num
    real(pr) :: CH2GSG_denom
    real(pr) :: CH2GSG_CH2
    real(pr) :: CH2GSG_CH3OH
    real(pr) :: CH2GSG_C2H5
    real(pr) :: CH3OH_ct
    real(pr) :: CH3OH_num
    real(pr) :: CH3OH_denom
    real(pr) :: CH3OH_CH2GSG
    real(pr) :: C2H_ct
    real(pr) :: C2H_num
    real(pr) :: C2H_denom
    real(pr) :: C2H5_ct
    real(pr) :: C2H5_num
    real(pr) :: C2H5_denom
    real(pr) :: C2H5_O
    real(pr) :: C2H5_CH2GSG
  
    real(pr) :: a_n_a
    real(pr) :: a_x_a
    real(pr) :: a_l_b
    real(pr) :: a_q_b
    real(pr) :: a_v_b
    real(pr) :: a_r_c
    real(pr) :: a_s_c
    real(pr) :: a_w_c
    real(pr) :: a_x_c
    real(pr) :: A_A_A
    real(pr) :: A_B_A
    real(pr) :: A_C_A
    real(pr) :: A_D_A
    real(pr) :: A_B_B
    real(pr) :: A_C_B
    real(pr) :: A_D_B
    real(pr) :: A_C_C
    real(pr) :: A_D_C
    real(pr) :: A_D_D

    C2H5_denom = tiny(1.0_pr) + ( 0.0_pr &
             + k(r41f)* c(sH) &
             + k(r42f)* c(sH) &
             + k(r93f)* c(sO2) &
             + k(r12b)* c(sOH) &
             + k(r40b)&
             + k(r43b)* c(sH2) &
             + k(r59b)* c(sH2O) &
             + k(r79b)* c(sCH3) &
             + k(r83b)* c(sH) &
             + k(r87b)* c(sCH4)   )

    C2H5_num = ( 0.0_pr &
             + k(r40f)* c(sC2H4) * c(sH) &
             + k(r43f)* c(sC2H6) * c(sH) &
             + k(r59f)* c(sC2H6) * c(sOH) &
             + k(r83f) *c(sCH3)** 2.0_pr&
             + k(r87f)* c(sC2H6) * c(sCH3) &
             + k(r41b)* c(sC2H6) &
             + k(r42b)* c(sC2H4) * c(sH2) &
             + k(r93b)* c(sC2H4) * c(sHO2)   )

    C2H5_ct = C2H5_num / C2H5_denom

    C2H5_O = - ( 0.0_pr &
          + k(r12f) * c(sC2H6)  ) / C2H5_denom

    C2H5_CH2GSG = - ( 0.0_pr &
          + k(r79f) * c(sC2H6)  ) / C2H5_denom

    CH3OH_denom = tiny(1.0_pr) + ( 0.0_pr &
             + k(r39f)* c(sH) &
             + k(r58f)* c(sOH) &
             + k(r86f)* c(sCH3) &
             + k(r35b)&
             + k(r50b)&
             + k(r72b)  )

    CH3OH_num = ( 0.0_pr &
             + k(r35f)* c(sCH3O) * c(sH) &
             + k(r50f)* c(sCH3) * c(sOH) &
             + k(r39b)* c(sCH3O) * c(sH2) &
             + k(r58b)* c(sCH3O) * c(sH2O) &
             + k(r86b)* c(sCH3O) * c(sCH4)   )

    CH3OH_ct = CH3OH_num / CH3OH_denom

    CH3OH_CH2GSG = - ( 0.0_pr &
          + k(r72f) * c(sH2O)  ) / CH3OH_denom

    CH2GSG_denom = tiny(1.0_pr) + ( 0.0_pr &
             + k(r49f)* c(sOH) &
             + k(r68f)* c(sN2) &
             + k(r69f)* c(sO2) &
             + k(r70f)* c(sO2) &
             + k(r71f)* c(sH2) &
             + k(r72f)* c(sH2O) &
             + k(r73f)* c(sH2O) &
             + k(r74f)* c(sCH3) &
             + k(r75f)* c(sCH4) &
             + k(r76f)* c(sCO) &
             + k(r77f)* c(sCO2) &
             + k(r78f)* c(sCO2) &
             + k(r79f)* c(sC2H6) &
             + k(r38b)* c(sH2O) &
             + k(r52b)* c(sH2O)   )

    CH2GSG_num = ( 0.0_pr &
             + k(r38f)* c(sCH3O) * c(sH) &
             + k(r52f)* c(sCH3) * c(sOH) &
             + k(r49b)* c(sCH2O) * c(sH) &
             + k(r69b)* c(sCO) * c(sH) * c(sOH) &
             + k(r70b)* c(sCO) * c(sH2O) &
             + k(r71b)* c(sCH3) * c(sH) &
             + k(r74b)* c(sC2H4) * c(sH) &
             + k(r75b) *c(sCH3)** 2.0_pr&
             + k(r78b)* c(sCH2O) * c(sCO)   )

    CH2GSG_ct = CH2GSG_num / CH2GSG_denom

    CH2GSG_CH2 = - ( 0.0_pr &
          + k(r68b) * c(sN2) &
          + k(r73b) * c(sH2O) &
          + k(r76b) * c(sCO) &
          + k(r77b) * c(sCO2)  ) / CH2GSG_denom

    CH2GSG_CH3OH = - ( 0.0_pr &
          + k(r72b)  ) / CH2GSG_denom

    CH2GSG_C2H5 = - ( 0.0_pr &
          + k(r79b) * c(sCH3)  ) / CH2GSG_denom

    CH2_denom = tiny(1.0_pr) + ( 0.0_pr &
             + k(r28f)* c(sH) &
             + k(r48f)* c(sOH) &
             + k(r60f)* c(sHO2) &
             + k(r64f)* c(sO2) &
             + k(r65f)* c(sH2) &
             + k(r66f)* c(sCH3) &
             + k(r67f)* c(sCH4) &
             + k(r51b)* c(sH2O) &
             + k(r68b)* c(sN2) &
             + k(r73b)* c(sH2O) &
             + k(r76b)* c(sCO) &
             + k(r77b)* c(sCO2)   )

    CH2_num = ( 0.0_pr &
             + k(r51f)* c(sCH3) * c(sOH) &
             + k(r28b)* c(sCH3) &
             + k(r48b)* c(sCH2O) * c(sH) &
             + k(r60b)* c(sCH2O) * c(sOH) &
             + k(r64b)* c(sHCO) * c(sOH) &
             + k(r65b)* c(sCH3) * c(sH) &
             + k(r66b)* c(sC2H4) * c(sH) &
             + k(r67b) *c(sCH3)** 2.0_pr  )

    CH2_ct = CH2_num / CH2_denom

    CH2_CH2GSG = - ( 0.0_pr &
          + k(r68f) * c(sN2) &
          + k(r73f) * c(sH2O) &
          + k(r76f) * c(sCO) &
          + k(r77f) * c(sCO2)  ) / CH2_denom

    O_denom = tiny(1.0_pr) + ( 0.0_pr &
             + k(r1f)* c(sH) * m(mM1) &
             + k(r2f)* c(sH2) &
             + k(r3f)* c(sHO2) &
             + k(r4f)* c(sCH3) &
             + k(r5f)* c(sCH4) &
             + k(r6f)* c(sCO) * m(mM6) &
             + k(r7f)* c(sHCO) &
             + k(r8f)* c(sHCO) &
             + k(r9f)* c(sCH2O) &
             + k(r10f)* c(sCH3O) &
             + k(r11f)* c(sC2H4) &
             + k(r12f)* c(sC2H6) &
             + k(r13b)* c(sCO2) &
             + k(r19b)* c(sOH) &
             + k(r25b)* c(sH2O) &
             + k(r46b)* c(sH2O) &
             + k(r80b)* c(sCH3O)   )

    O_num = ( 0.0_pr &
             + k(r13f)* c(sCO) * c(sO2) &
             + k(r19f)* c(sH) * c(sO2) &
             + k(r25f)* c(sH) * c(sHO2) &
             + k(r46f) *c(sOH)** 2.0_pr&
             + k(r80f)* c(sCH3) * c(sO2) &
             + k(r1b)* c(sOH) * m(mM1) &
             + k(r2b)* c(sH) * c(sOH) &
             + k(r3b)* c(sO2) * c(sOH) &
             + k(r4b)* c(sCH2O) * c(sH) &
             + k(r5b)* c(sCH3) * c(sOH) &
             + k(r6b)* c(sCO2) * m(mM6) &
             + k(r7b)* c(sCO) * c(sOH) &
             + k(r8b)* c(sCO2) * c(sH) &
             + k(r9b)* c(sHCO) * c(sOH) &
             + k(r10b)* c(sCH2O) * c(sOH) &
             + k(r11b)* c(sCH3) * c(sHCO)   )

    O_ct = O_num / O_denom

    O_C2H5 = - ( 0.0_pr &
          + k(r12b) * c(sOH)  ) / O_denom

    a_n_a = CH2GSG_C2H5
    a_x_a =  (1.0_pr) - (O_C2H5) * (C2H5_O)
    a_l_b =  (1.0_pr) - (CH2_CH2GSG) * (CH2GSG_CH2)
    a_q_b = CH3OH_CH2GSG
    a_v_b = C2H5_CH2GSG
    a_r_c =  (1.0_pr) - (CH2GSG_CH3OH) * (a_q_b) / (a_l_b)
    a_s_c =  - (a_n_a) * (a_q_b) / (a_l_b)
    a_w_c =  - (CH2GSG_CH3OH) * (a_v_b) / (a_l_b)
    a_x_c =  (a_x_a) - (a_n_a) * (a_v_b) / (a_l_b)
    A_A_A = CH2_ct
    A_B_A = CH2GSG_ct
    A_C_A = CH3OH_ct
    A_D_A =  (C2H5_ct) - (O_ct) * (C2H5_O)
    A_B_B =  (A_B_A) - (A_A_A) * (CH2GSG_CH2)
    A_C_B = A_C_A
    A_D_B = A_D_A
    A_C_C =  (A_C_B) - (A_B_B) * (a_q_b) / (a_l_b)
    A_D_C =  (A_D_B) - (A_B_B) * (a_v_b) / (a_l_b)
    A_D_D =  (A_D_C) - (A_C_C) * (a_w_c) / (a_r_c)

    cqss(sqssC2H5) = ( A_D_D ) / ( a_x_c )  

    cqss(sqssCH3OH) = (A_C_C - (a_s_c) * cqss(sqssC2H5)) / (a_r_c)  

    cqss(sqssCH2GSG) = (A_B_B - (a_n_a) * cqss(sqssC2H5) - (CH2GSG_CH3OH) &
                 * cqss(sqssCH3OH)) / (a_l_b)  

    cqss(sqssCH2) = A_A_A - (CH2_CH2GSG) * cqss(sqssCH2GSG)  

    cqss(sqssO) = O_ct - (O_C2H5) * cqss(sqssC2H5)  

    C2H_denom = tiny(1.0_pr) + ( 0.0_pr &
             + k(r92f)* c(sO2)   )

    C2H_num = ( 0.0_pr &
             + k(r92b)* c(sCO) * c(sHCO)   )

    C2H_ct = C2H_num / C2H_denom

    cqss(sqssC2H) = C2H_ct  

    cqss = max(cqss, tiny(1.0_pr))
    cqss = min(cqss, 1e03_pr)

    ! Necessary for very low concentration variations
    ! Needs to be integrated only for Cantera
    do index=1,nqss
      if (cqss(index) /= cqss(index)) then
        cqss(index) = tiny(1.0_pr)
      end if
    end do

    return
  end subroutine get_qss


  ! ----------------------------------------------- !
  ! Mass fractions to concentrations                !
  ! ----------------------------------------------- !
  subroutine y2c(y, W_sp, P, T, c)
    implicit none

    real(pr),dimension(nspec) :: W_sp
    real(pr),dimension(nspec) :: c, y
    real(pr) :: rho, P, T, inv_W_g

    integer :: k
    
    ! Gas molecular weight inverse
    inv_W_g = 0.0_pr
    do k =1, nspec
      inv_W_g = inv_W_g + y(k) / W_sp(k)
    end do

    ! Gas density
    rho = P / (Rcst * inv_W_g * T)

    ! Conversion
    c = y * rho / W_sp

    ! Concentrations clipping
    !do  k = 1, nspec
    !   if (c(k)<1.0e-20_pr) c(k) = 0.0_pr
    !end do

        return
    end subroutine y2c

end module mod_customkinetics
! ----------------------------------------------- !
! Cantera routine                                 !
! ----------------------------------------------- !
subroutine customkinetics(P, T, y, wdot)

  use mod_customkinetics
  implicit none

  real(pr), dimension(nspec) :: y, c, wdot, cdot
  real(pr), dimension(nqss) :: cqss
  real(pr), dimension(nreac + nreac_reverse) :: w,k
  real(pr), dimension(nTB + nFO) :: M
  real(pr) :: P, T, rho

  ! Convert to concentrations
  call y2c(y, W_sp, P, T, c)

  ! Evaluate QSS concentrations and reaction rates
  call get_thirdbodies(M,c)

  call get_rate_coefficients(k, M, T, P)
  call get_qss(cqss, c, k, M)

  call get_reaction_rates(w, k, M, c, cqss)

  ! Evaluate production rates
  call get_production_rates(wdot,w)


  return
end subroutine customkinetics

