!--------------------------------------------------------------------------------------------------
!     Copyright (c) CERFACS (all rights reserved)
!--------------------------------------------------------------------------------------------------
!     FILE ./database/S18R117QSS14_0/S18R117QSS14_0.f90
!>    @file ./database/S18R117QSS14_0/S18R117QSS14_0.f90
!!    Module for calculating the analytical source terms in Cantera
!!    @details 
!!    @authors 
!!    @date    2023/08/25
!!    @since   
!!    @note    
!--------------------------------------------------------------------------------------------------

!--------------------------------------------------------------------------------------------------
!     MODULE mod_customkinetics
!>    @details Generated by ARCANE custom kinetics routine to compute the chemical source terms.
!!    @authors Q. Cazères, P. Pepiot
!!    @date    2019/01/24
!--------------------------------------------------------------------------------------------------
module mod_customkinetics
  implicit none

  integer, parameter :: pr = selected_real_kind(15,307)

  ! Ideal gas constant
  real(pr), parameter :: Rcst = 8.3144621_pr
  
  ! Use semi-implicit formulation for select species
  logical, parameter :: semiImplicit = .False.
  
  ! Number of elements in the chemical system 
  integer, parameter :: ne = 3
  
  ! Number of non-qss and qss species and reactions
  integer, parameter :: nspec = 18
  integer, parameter :: nqss = 14
  integer, parameter :: nreac = 117
  integer, parameter :: nreac_reverse = 108
  
  ! Actual expression of each reaction
  character(len=65), dimension(nreac + nreac_reverse) :: reacexp
  
  ! Number of thirdbodies
  integer, parameter :: nTB = 4
  integer, parameter :: nFO = 17
  integer, parameter :: nTB_reverse = 4
  integer, parameter :: nFO_reverse = 17
  
  ! Index of elements
  integer, parameter :: eH = 1
  integer, parameter :: eO = 2
  integer, parameter :: eC = 3

  ! Index of species
  integer, parameter :: sH = 1
  integer, parameter :: sH2 = 2
  integer, parameter :: sO2 = 3
  integer, parameter :: sOH = 4
  integer, parameter :: sH2O = 5
  integer, parameter :: sN2 = 6
  integer, parameter :: sHO2 = 7
  integer, parameter :: sH2O2 = 8
  integer, parameter :: sCO = 9
  integer, parameter :: sCO2 = 10
  integer, parameter :: sCH2O = 11
  integer, parameter :: sCH3O = 12
  integer, parameter :: sCH3O2H = 13
  integer, parameter :: sCH3O2 = 14
  integer, parameter :: sCH4 = 15
  integer, parameter :: sCH3 = 16
  integer, parameter :: sC2H6 = 17
  integer, parameter :: sC2H4 = 18

  integer, parameter :: sqssO = 1
  integer, parameter :: sqssHCO = 2
  integer, parameter :: sqssOCHO = 3
  integer, parameter :: sqssCH3OH = 4
  integer, parameter :: sqssCH2OH = 5
  integer, parameter :: sqssCH2 = 6
  integer, parameter :: sqssCH2GSG = 7
  integer, parameter :: sqssC = 8
  integer, parameter :: sqssC2H5 = 9
  integer, parameter :: sqssC2H3 = 10
  integer, parameter :: sqssC2H2 = 11
  integer, parameter :: sqssCH2CHO = 12
  integer, parameter :: sqssCH2CO = 13
  integer, parameter :: sqssHCCO = 14

  ! Index of reactions
  integer, parameter :: r1f = 1
  integer, parameter :: r2f = 2
  integer, parameter :: r3f = 3
  integer, parameter :: r4f = 4
  integer, parameter :: r5f = 5
  integer, parameter :: r6f = 6
  integer, parameter :: r7f = 7
  integer, parameter :: r8f = 8
  integer, parameter :: r9f = 9
  integer, parameter :: r10f = 10
  integer, parameter :: r11f = 11
  integer, parameter :: r12f = 12
  integer, parameter :: r13f = 13
  integer, parameter :: r14f = 14
  integer, parameter :: r15f = 15
  integer, parameter :: r16f = 16
  integer, parameter :: r17f = 17
  integer, parameter :: r18f = 18
  integer, parameter :: r19f = 19
  integer, parameter :: r20f = 20
  integer, parameter :: r21f = 21
  integer, parameter :: r22f = 22
  integer, parameter :: r23f = 23
  integer, parameter :: r24f = 24
  integer, parameter :: r25f = 25
  integer, parameter :: r26f = 26
  integer, parameter :: r27f = 27
  integer, parameter :: r28f = 28
  integer, parameter :: r29f = 29
  integer, parameter :: r30f = 30
  integer, parameter :: r31f = 31
  integer, parameter :: r32f = 32
  integer, parameter :: r33f = 33
  integer, parameter :: r34f = 34
  integer, parameter :: r35f = 35
  integer, parameter :: r36f = 36
  integer, parameter :: r37f = 37
  integer, parameter :: r38f = 38
  integer, parameter :: r39f = 39
  integer, parameter :: r40f = 40
  integer, parameter :: r41f = 41
  integer, parameter :: r42f = 42
  integer, parameter :: r43f = 43
  integer, parameter :: r44f = 44
  integer, parameter :: r45f = 45
  integer, parameter :: r46f = 46
  integer, parameter :: r47f = 47
  integer, parameter :: r48f = 48
  integer, parameter :: r49f = 49
  integer, parameter :: r50f = 50
  integer, parameter :: r51f = 51
  integer, parameter :: r52f = 52
  integer, parameter :: r53f = 53
  integer, parameter :: r54f = 54
  integer, parameter :: r55f = 55
  integer, parameter :: r56f = 56
  integer, parameter :: r57f = 57
  integer, parameter :: r58f = 58
  integer, parameter :: r59f = 59
  integer, parameter :: r60f = 60
  integer, parameter :: r61f = 61
  integer, parameter :: r62f = 62
  integer, parameter :: r63f = 63
  integer, parameter :: r64f = 64
  integer, parameter :: r65f = 65
  integer, parameter :: r66f = 66
  integer, parameter :: r67f = 67
  integer, parameter :: r68f = 68
  integer, parameter :: r69f = 69
  integer, parameter :: r70f = 70
  integer, parameter :: r71f = 71
  integer, parameter :: r72f = 72
  integer, parameter :: r73f = 73
  integer, parameter :: r74f = 74
  integer, parameter :: r75f = 75
  integer, parameter :: r76f = 76
  integer, parameter :: r77f = 77
  integer, parameter :: r78f = 78
  integer, parameter :: r79f = 79
  integer, parameter :: r80f = 80
  integer, parameter :: r81f = 81
  integer, parameter :: r82f = 82
  integer, parameter :: r83f = 83
  integer, parameter :: r84f = 84
  integer, parameter :: r85f = 85
  integer, parameter :: r86f = 86
  integer, parameter :: r87f = 87
  integer, parameter :: r88f = 88
  integer, parameter :: r89f = 89
  integer, parameter :: r90f = 90
  integer, parameter :: r91f = 91
  integer, parameter :: r92f = 92
  integer, parameter :: r93f = 93
  integer, parameter :: r94f = 94
  integer, parameter :: r95f = 95
  integer, parameter :: r96f = 96
  integer, parameter :: r97f = 97
  integer, parameter :: r98f = 98
  integer, parameter :: r99f = 99
  integer, parameter :: r100f = 100
  integer, parameter :: r101f = 101
  integer, parameter :: r102f = 102
  integer, parameter :: r103f = 103
  integer, parameter :: r104f = 104
  integer, parameter :: r105f = 105
  integer, parameter :: r106f = 106
  integer, parameter :: r107f = 107
  integer, parameter :: r108f = 108
  integer, parameter :: r109f = 109
  integer, parameter :: r110f = 110
  integer, parameter :: r111f = 111
  integer, parameter :: r112f = 112
  integer, parameter :: r113f = 113
  integer, parameter :: r114f = 114
  integer, parameter :: r115f = 115
  integer, parameter :: r116f = 116
  integer, parameter :: r117f = 117
  integer, parameter :: r1b = 118
  integer, parameter :: r2b = 119
  integer, parameter :: r3b = 120
  integer, parameter :: r4b = 121
  integer, parameter :: r5b = 122
  integer, parameter :: r6b = 123
  integer, parameter :: r7b = 124
  integer, parameter :: r8b = 125
  integer, parameter :: r9b = 126
  integer, parameter :: r10b = 127
  integer, parameter :: r11b = 128
  integer, parameter :: r12b = 129
  integer, parameter :: r13b = 130
  integer, parameter :: r14b = 131
  integer, parameter :: r15b = 132
  integer, parameter :: r16b = 133
  integer, parameter :: r17b = 134
  integer, parameter :: r18b = 135
  integer, parameter :: r19b = 136
  integer, parameter :: r20b = 137
  integer, parameter :: r21b = 138
  integer, parameter :: r22b = 139
  integer, parameter :: r23b = 140
  integer, parameter :: r24b = 141
  integer, parameter :: r25b = 142
  integer, parameter :: r26b = 143
  integer, parameter :: r27b = 144
  integer, parameter :: r28b = 145
  integer, parameter :: r29b = 146
  integer, parameter :: r30b = 147
  integer, parameter :: r31b = 148
  integer, parameter :: r32b = 149
  integer, parameter :: r33b = 150
  integer, parameter :: r34b = 151
  integer, parameter :: r35b = 152
  integer, parameter :: r36b = 153
  integer, parameter :: r37b = 154
  integer, parameter :: r38b = 155
  integer, parameter :: r39b = 156
  integer, parameter :: r40b = 157
  integer, parameter :: r41b = 158
  integer, parameter :: r42b = 159
  integer, parameter :: r43b = 160
  integer, parameter :: r44b = 161
  integer, parameter :: r45b = 162
  integer, parameter :: r46b = 163
  integer, parameter :: r47b = 164
  integer, parameter :: r48b = 165
  integer, parameter :: r49b = 166
  integer, parameter :: r50b = 167
  integer, parameter :: r51b = 168
  integer, parameter :: r52b = 169
  integer, parameter :: r53b = 170
  integer, parameter :: r54b = 171
  integer, parameter :: r55b = 172
  integer, parameter :: r56b = 173
  integer, parameter :: r57b = 174
  integer, parameter :: r58b = 175
  integer, parameter :: r59b = 176
  integer, parameter :: r60b = 177
  integer, parameter :: r61b = 178
  integer, parameter :: r62b = 179
  integer, parameter :: r63b = 180
  integer, parameter :: r64b = 181
  integer, parameter :: r65b = 182
  integer, parameter :: r66b = 183
  integer, parameter :: r67b = 184
  integer, parameter :: r70b = 185
  integer, parameter :: r71b = 186
  integer, parameter :: r72b = 187
  integer, parameter :: r73b = 188
  integer, parameter :: r74b = 189
  integer, parameter :: r75b = 190
  integer, parameter :: r76b = 191
  integer, parameter :: r78b = 192
  integer, parameter :: r79b = 193
  integer, parameter :: r80b = 194
  integer, parameter :: r81b = 195
  integer, parameter :: r82b = 196
  integer, parameter :: r84b = 197
  integer, parameter :: r85b = 198
  integer, parameter :: r86b = 199
  integer, parameter :: r87b = 200
  integer, parameter :: r88b = 201
  integer, parameter :: r89b = 202
  integer, parameter :: r90b = 203
  integer, parameter :: r91b = 204
  integer, parameter :: r92b = 205
  integer, parameter :: r93b = 206
  integer, parameter :: r94b = 207
  integer, parameter :: r95b = 208
  integer, parameter :: r96b = 209
  integer, parameter :: r97b = 210
  integer, parameter :: r98b = 211
  integer, parameter :: r100b = 212
  integer, parameter :: r101b = 213
  integer, parameter :: r102b = 214
  integer, parameter :: r104b = 215
  integer, parameter :: r107b = 216
  integer, parameter :: r108b = 217
  integer, parameter :: r109b = 218
  integer, parameter :: r110b = 219
  integer, parameter :: r111b = 220
  integer, parameter :: r112b = 221
  integer, parameter :: r113b = 222
  integer, parameter :: r115b = 223
  integer, parameter :: r116b = 224
  integer, parameter :: r117b = 225
  
  ! Index of third body species
  integer, parameter :: mM5 = 1
  integer, parameter :: mM6 = 2
  integer, parameter :: mM7 = 3
  integer, parameter :: mM25 = 4
  
  integer, parameter :: mM8 = 5
  integer, parameter :: mM15 = 6
  integer, parameter :: mM16 = 7
  integer, parameter :: mM21 = 8
  integer, parameter :: mM37 = 9
  integer, parameter :: mM41 = 10
  integer, parameter :: mM44 = 11
  integer, parameter :: mM45 = 12
  integer, parameter :: mM50 = 13
  integer, parameter :: mM63 = 14
  integer, parameter :: mM81 = 15
  integer, parameter :: mM85 = 16
  integer, parameter :: mM86 = 17
  integer, parameter :: mM92 = 18
  integer, parameter :: mM97 = 19
  integer, parameter :: mM98 = 20
  integer, parameter :: mM112 = 21
  
  ! Index of third body reactions
  integer, parameter :: TBr5f = 1
  integer, parameter :: TBr6f = 2
  integer, parameter :: TBr7f = 3
  integer, parameter :: TBr25f = 4
  integer, parameter :: TBr5b = 5
  integer, parameter :: TBr6b = 6
  integer, parameter :: TBr7b = 7
  integer, parameter :: TBr25b = 8
  
  ! Index of fall off reactions
  integer, parameter :: FOr8f = 1
  integer, parameter :: FOr15f = 2
  integer, parameter :: FOr16f = 3
  integer, parameter :: FOr21f = 4
  integer, parameter :: FOr37f = 5
  integer, parameter :: FOr41f = 6
  integer, parameter :: FOr44f = 7
  integer, parameter :: FOr45f = 8
  integer, parameter :: FOr50f = 9
  integer, parameter :: FOr63f = 10
  integer, parameter :: FOr81f = 11
  integer, parameter :: FOr85f = 12
  integer, parameter :: FOr86f = 13
  integer, parameter :: FOr92f = 14
  integer, parameter :: FOr97f = 15
  integer, parameter :: FOr98f = 16
  integer, parameter :: FOr112f = 17
  integer, parameter :: FOr8b = 18
  integer, parameter :: FOr15b = 19
  integer, parameter :: FOr16b = 20
  integer, parameter :: FOr21b = 21
  integer, parameter :: FOr37b = 22
  integer, parameter :: FOr41b = 23
  integer, parameter :: FOr44b = 24
  integer, parameter :: FOr45b = 25
  integer, parameter :: FOr50b = 26
  integer, parameter :: FOr63b = 27
  integer, parameter :: FOr81b = 28
  integer, parameter :: FOr85b = 29
  integer, parameter :: FOr86b = 30
  integer, parameter :: FOr92b = 31
  integer, parameter :: FOr97b = 32
  integer, parameter :: FOr98b = 33
  integer, parameter :: FOr112b = 34
  
  ! Molar mass
  real(pr), parameter, dimension(nspec) :: W_sp =(/ &
       1.007940e-03_pr, & ! H
       2.015880e-03_pr, & ! H2
       3.199880e-02_pr, & ! O2
       1.700734e-02_pr, & ! OH
       1.801528e-02_pr, & ! H2O
       2.801348e-02_pr, & ! N2
       3.300674e-02_pr, & ! HO2
       3.401468e-02_pr, & ! H2O2
       2.801040e-02_pr, & ! CO
       4.400980e-02_pr, & ! CO2
       3.002628e-02_pr, & ! CH2O
       3.103422e-02_pr, & ! CH3O
       4.804156e-02_pr, & ! CH3O2H
       4.703362e-02_pr, & ! CH3O2
       1.604276e-02_pr, & ! CH4
       1.503482e-02_pr, & ! CH3
       3.006964e-02_pr, & ! C2H6
       2.805376e-02_pr & ! C2H4
      !1.599940e-02_pr, & ! O
      !2.901834e-02_pr, & ! HCO
      !4.501774e-02_pr, & ! OCHO
      !3.204216e-02_pr, & ! CH3OH
      !3.103422e-02_pr, & ! CH2OH
      !1.402688e-02_pr, & ! CH2
      !1.402688e-02_pr, & ! CH2GSG
      !1.201100e-02_pr, & ! C
      !2.906170e-02_pr, & ! C2H5
      !2.704582e-02_pr, & ! C2H3
      !2.603788e-02_pr, & ! C2H2
      !4.304522e-02_pr, & ! CH2CHO
      !4.203728e-02_pr, & ! CH2CO
      !4.102934e-02_pr & ! HCCO
       /)
  
contains

  ! ----------------------------------------------- !
  ! Subroutine for pressure dependent coefficients  !
  ! ----------------------------------------------- !
  real(pr) function getlindratecoeff(Tloc,k0,kinf,fc,concin,Ploc)
    implicit none

    real(pr) ::  Tloc,k0,kinf,fc,redP,Ploc
    real(pr) :: ntmp,ccoeff,dcoeff,lgknull
    real(pr) :: f
    real(pr) :: conc, concin

    if (concin.gt.0.0_pr) then
       conc = concin
    else
       conc = Ploc / ( Rcst * Tloc )
    end if
    
    redP = abs(k0) * conc / max(abs(kinf), tiny(1.0_pr)) + tiny(1.0_pr)

    ntmp = 0.75_pr - 1.27_pr * log10( fc )
    ccoeff = - 0.4_pr - 0.67_pr * log10( fc )
    dcoeff = 0.14_pr
    lgknull = log10(redP)
    f = (lgknull+ccoeff)/(ntmp-dcoeff*(lgknull+ccoeff))
    f = fc**(1.0_pr / ( f * f + 1.0_pr ))
    
    getlindratecoeff = kinf * f * redP / ( 1.0_pr + redP )

  end function getlindratecoeff

  ! ----------------------------------------------- !
  ! Evaluate thirdbodies                            !
  ! ----------------------------------------------- !
  subroutine get_thirdbodies(M,c)
    implicit none

    real(pr), dimension(nspec) :: c
    real(pr), dimension(nTB + nFO) :: M

    M(mM5) = (1.000000e+00_pr)*c(sCH4) &
         + (9.000000e-01_pr)*c(sCO) &
         + (2.800000e+00_pr)*c(sCO2) &
         + (1.500000e+00_pr)*c(sH2) &
         + (1.100000e+01_pr)*c(sH2O) &
         + sum(c)

    M(mM6) = (1.000000e+00_pr)*c(sCH4) &
         + (5.000000e-01_pr)*c(sCO) &
         + (1.000000e+00_pr)*c(sCO2) &
         + (1.500000e+00_pr)*c(sH2) &
         + (1.100000e+01_pr)*c(sH2O) &
         + sum(c)

    M(mM7) = (1.000000e+00_pr)*c(sCH4) &
         + (-2.700000e-01_pr)*c(sH2) &
         + (2.650000e+00_pr)*c(sH2O) &
         + sum(c)

    M(mM25) = (1.000000e+00_pr)*c(sCH4) &
         + (5.000000e-01_pr)*c(sCO) &
         + (1.000000e+00_pr)*c(sCO2) &
         + (1.000000e+00_pr)*c(sH2) &
         + (1.100000e+01_pr)*c(sH2O) &
         + sum(c)

    M(mM8) = (1.000000e+00_pr)*c(sCH4) &
         + (9.000000e-01_pr)*c(sCO) &
         + (2.800000e+00_pr)*c(sCO2) &
         + (3.000000e-01_pr)*c(sH2) &
         + (9.000000e+00_pr)*c(sH2O) &
         + sum(c)

    M(mM15) = c(sH2O)

    M(mM16) = (1.800000e+00_pr)*c(sCO) &
         + (6.000000e-01_pr)*c(sCO2) &
         + (2.700000e+00_pr)*c(sH2) &
         + (-1.000000e+00_pr)*c(sH2O) &
         + (5.000000e-01_pr)*c(sN2) &
         + (2.000000e-01_pr)*c(sO2) &
         + sum(c)

    M(mM21) = (7.500000e-01_pr)*c(sCO) &
         + (2.600000e+00_pr)*c(sCO2) &
         + (1.000000e+00_pr)*c(sH2) &
         + (1.100000e+01_pr)*c(sH2O) &
         + sum(c)

    M(mM37) = (1.000000e+00_pr)*c(sCH4) &
         + (5.000000e-01_pr)*c(sCO) &
         + (1.000000e+00_pr)*c(sCO2) &
         + (1.000000e+00_pr)*c(sH2) &
         + (5.000000e+00_pr)*c(sH2O) &
         + sum(c)

    M(mM41) = (1.000000e+00_pr)*c(sCH4) &
         + (5.000000e-01_pr)*c(sCO) &
         + (1.000000e+00_pr)*c(sCO2) &
         + (1.000000e+00_pr)*c(sH2) &
         + (5.000000e+00_pr)*c(sH2O) &
         + sum(c)

    M(mM44) = sum(c)

    M(mM45) = sum(c)

    M(mM50) = (1.000000e+00_pr)*c(sCH4) &
         + (5.000000e-01_pr)*c(sCO) &
         + (1.000000e+00_pr)*c(sCO2) &
         + (1.000000e+00_pr)*c(sH2) &
         + (5.000000e+00_pr)*c(sH2O) &
         + sum(c)

    M(mM63) = sum(c)

    M(mM81) = (1.000000e+00_pr)*c(sCH4) &
         + (5.000000e-01_pr)*c(sCO) &
         + (1.000000e+00_pr)*c(sCO2) &
         + (1.000000e+00_pr)*c(sH2) &
         + (5.000000e+00_pr)*c(sH2O) &
         + sum(c)

    M(mM85) = (1.000000e+00_pr)*c(sCO) &
         + (2.000000e+00_pr)*c(sCO2) &
         + (4.000000e+00_pr)*c(sH2O) &
         + sum(c)

    M(mM86) = (1.000000e+00_pr)*c(sCH4) &
         + (5.000000e-01_pr)*c(sCO) &
         + (1.000000e+00_pr)*c(sCO2) &
         + (1.000000e+00_pr)*c(sH2) &
         + (5.000000e+00_pr)*c(sH2O) &
         + sum(c)

    M(mM92) = (1.000000e+00_pr)*c(sCH4) &
         + (5.000000e-01_pr)*c(sCO) &
         + (1.000000e+00_pr)*c(sCO2) &
         + (1.000000e+00_pr)*c(sH2) &
         + (5.000000e+00_pr)*c(sH2O) &
         + sum(c)

    M(mM97) = sum(c)

    M(mM98) = sum(c)

    M(mM112) = (1.000000e+00_pr)*c(sCH4) &
         + (5.000000e-01_pr)*c(sCO) &
         + (1.000000e+00_pr)*c(sCO2) &
         + (1.000000e+00_pr)*c(sH2) &
         + (5.000000e+00_pr)*c(sH2O) &
         + sum(c)

  end subroutine get_thirdbodies
  
  ! ----------------------------------------------- !
  ! Evaluate rate coefficients                      !
  ! ----------------------------------------------- !
  subroutine get_rate_coefficients(k,M,Tloc,Ploc)
    implicit none

    real(pr), dimension(nreac + nreac_reverse) :: k
    real(pr), dimension(nFO + nFO_reverse) :: k_0
    real(pr), dimension(nFO + nFO_reverse) :: k_inf
    real(pr), dimension(nFO + nFO_reverse) :: FC
    real(pr), dimension(nTB + nFO) :: M
    real(pr) :: Tloc,Ploc,R_T_inv,T_log,redP

    ! Rate coefficients
    R_T_inv = 1.0_pr/(Rcst*Tloc)
    T_log = log(Tloc)

    k(r1f) = (1.040000e+08_pr)*exp((-6.395662e+04_pr)*R_T_inv )
    k(r2f) = (5.080000e-02_pr)*exp((-2.632573e+04_pr)*R_T_inv + (2.670000e+00_pr)*T_log )
    k(r3f) = (4.380000e+07_pr)*exp((-2.924616e+04_pr)*R_T_inv )
    k(r4f) = (2.970000e+00_pr)*exp((-5.606560e+04_pr)*R_T_inv + (2.020000e+00_pr)*T_log )
    k(r5f) = (4.577000e+13_pr)*exp((-4.368096e+05_pr)*R_T_inv + (-1.400000e+00_pr)*T_log )
    k(r6f) = (4.714000e+06_pr)*exp((-1.000000e+00_pr)*T_log )
    k(r7f) = (3.500000e+10_pr)*exp((-2.000000e+00_pr)*T_log )
    k_0(FOr8f) =(1.737000e+07_pr)*exp((-1.230000e+00_pr)*T_log )
    k_inf(FOr8f) =(4.650000e+06_pr)*exp((4.400000e-01_pr)*T_log )
    FC(FOr8f) = ((1.0_pr - 6.700000e-01_pr)*exp(-Tloc/(1.000000e-30_pr)) + (6.700000e-01_pr)*exp(-Tloc/(1.000000e+30_pr)))&
              + exp(-(1.000000e+30_pr)/Tloc)
    k(r8f) = getlindratecoeff(Tloc, k_0(FOr8f), k_inf(FOr8f),FC(FOr8f), M(mM8),Ploc)
    k(r9f) = (7.079000e+07_pr)*exp((-1.234280e+03_pr)*R_T_inv )
    k(r10f) = (5.176000e-01_pr)*exp((-2.238524e+05_pr)*R_T_inv + (2.433000e+00_pr)*T_log )
    k(r11f) = (3.250000e+07_pr)
    k(r12f) = (2.456000e+07_pr)*exp((2.079448e+03_pr)*R_T_inv )
    k(r13f) = (1.300000e+05_pr)*exp((6.819920e+03_pr)*R_T_inv )
    k(r14f) = (3.658000e+08_pr)*exp((-5.020800e+04_pr)*R_T_inv )
    k_0(FOr15f) =(1.865000e+19_pr)*exp((-2.039658e+05_pr)*R_T_inv + (-2.300000e+00_pr)*T_log )
    k_inf(FOr15f) =(2.000000e+12_pr)*exp((-2.039658e+05_pr)*R_T_inv + (9.000000e-01_pr)*T_log )
    FC(FOr15f) = ((1.0_pr - 5.100000e-01_pr)*exp(-Tloc/(1.000000e-30_pr)) + (5.100000e-01_pr)*exp(-Tloc/(1.000000e+30_pr)))
    k(r15f) = getlindratecoeff(Tloc, k_0(FOr15f), k_inf(FOr15f),FC(FOr15f), M(mM15),Ploc)
    k_0(FOr16f) =(2.490000e+18_pr)*exp((-2.039658e+05_pr)*R_T_inv + (-2.300000e+00_pr)*T_log )
    k_inf(FOr16f) =(2.000000e+12_pr)*exp((-2.039658e+05_pr)*R_T_inv + (9.000000e-01_pr)*T_log )
    FC(FOr16f) = ((1.0_pr - 4.300000e-01_pr)*exp(-Tloc/(1.000000e-30_pr)) + (4.300000e-01_pr)*exp(-Tloc/(1.000000e+30_pr)))
    k(r16f) = getlindratecoeff(Tloc, k_0(FOr16f), k_inf(FOr16f),FC(FOr16f), M(mM16),Ploc)
    k(r17f) = (2.410000e+07_pr)*exp((-1.661048e+04_pr)*R_T_inv )
    k(r18f) = (2.150000e+04_pr)*exp((-2.510400e+04_pr)*R_T_inv + (1.000000e+00_pr)*T_log )
    k(r19f) = (9.550000e+00_pr)*exp((-1.661048e+04_pr)*R_T_inv + (2.000000e+00_pr)*T_log )
    k(r20f) = (7.590000e+07_pr)*exp((-3.041350e+04_pr)*R_T_inv )
    k_0(FOr21f) =(1.173000e+12_pr)*exp((-1.753514e+04_pr)*R_T_inv + (-2.790000e+00_pr)*T_log )
    k_inf(FOr21f) =(1.362000e+04_pr)*exp((-9.974656e+03_pr)*R_T_inv )
    redP = abs(k_0(FOr21f)) * M(mM21) / max(abs(k_inf(FOr21f)), tiny(1.0_pr)) + tiny(1.0_pr)
    k(r21f) = k_inf(FOr21f) * redP / ( 1.0_pr + redP )
    k(r22f) = (7.015000e-02_pr)*exp((1.488249e+03_pr)*R_T_inv + (2.053000e+00_pr)*T_log )
    k(r23f) = (5.757000e+06_pr)*exp((-1.388251e+03_pr)*R_T_inv + (-6.640000e-01_pr)*T_log )
    k(r24f) = (1.570000e-01_pr)*exp((-7.506096e+04_pr)*R_T_inv + (2.180000e+00_pr)*T_log )
    k(r25f) = (5.700000e+05_pr)*exp((-6.221608e+04_pr)*R_T_inv + (6.600000e-01_pr)*T_log )
    k(r26f) = (7.580000e+06_pr)*exp((-1.715440e+03_pr)*R_T_inv )
    k(r27f) = (7.340000e+07_pr)
    k(r28f) = (1.020000e+08_pr)
    k(r29f) = (2.650000e+07_pr)
    k(r30f) = (8.070000e+09_pr)*exp((-2.235093e+05_pr)*R_T_inv )
    k(r31f) = (7.500000e+07_pr)*exp((-1.213360e+05_pr)*R_T_inv )
    k(r32f) = (7.820000e+01_pr)*exp((4.414120e+03_pr)*R_T_inv + (1.630000e+00_pr)*T_log )
    k(r33f) = (5.740000e+01_pr)*exp((-1.146416e+04_pr)*R_T_inv + (1.900000e+00_pr)*T_log )
    k(r34f) = (6.260000e+03_pr)*exp((-9.455840e+03_pr)*R_T_inv + (1.150000e+00_pr)*T_log )
    k(r35f) = (3.830000e-05_pr)*exp((-1.804141e+04_pr)*R_T_inv + (3.360000e+00_pr)*T_log )
    k(r36f) = (1.880000e-02_pr)*exp((-4.819968e+04_pr)*R_T_inv + (2.700000e+00_pr)*T_log )
    k_0(FOr37f) =(1.867000e+19_pr)*exp((-1.017005e+05_pr)*R_T_inv + (-3.000000e+00_pr)*T_log )
    k_inf(FOr37f) =(6.800000e+13_pr)*exp((-1.094953e+05_pr)*R_T_inv )
    FC(FOr37f) = ((1.0_pr - 9.000000e-01_pr)*exp(-Tloc/(2.500000e+03_pr)) + (9.000000e-01_pr)*exp(-Tloc/(1.300000e+03_pr)))&
              + exp(-(1.000000e+99_pr)/Tloc)
    k(r37f) = getlindratecoeff(Tloc, k_0(FOr37f), k_inf(FOr37f),FC(FOr37f), M(mM37),Ploc)
    k(r38f) = (4.380000e-25_pr)*exp((2.301618e+04_pr)*R_T_inv + (9.500000e+00_pr)*T_log )
    k(r39f) = (1.200000e+07_pr)
    k(r40f) = (2.000000e+07_pr)
    k_0(FOr41f) =(1.270000e+20_pr)*exp((-2.732152e+04_pr)*R_T_inv + (-4.820000e+00_pr)*T_log )
    k_inf(FOr41f) =(5.400000e+05_pr)*exp((-1.506240e+04_pr)*R_T_inv + (4.540000e-01_pr)*T_log )
    FC(FOr41f) = ((1.0_pr - 7.187000e-01_pr)*exp(-Tloc/(1.030000e+02_pr)) + (7.187000e-01_pr)*exp(-Tloc/(1.291000e+03_pr)))&
              + exp(-(4.160000e+03_pr)/Tloc)
    k(r41f) = getlindratecoeff(Tloc, k_0(FOr41f), k_inf(FOr41f),FC(FOr41f), M(mM41),Ploc)
    k(r42f) = (2.410000e+08_pr)*exp((-2.099113e+04_pr)*R_T_inv )
    k(r43f) = (2.400000e+07_pr)
    k_0(FOr44f) =(1.500000e+37_pr)*exp((-4.099994e+05_pr)*R_T_inv + (-6.995000e+00_pr)*T_log )
    k_inf(FOr44f) =(2.084000e+18_pr)*exp((-3.871899e+05_pr)*R_T_inv + (-6.150000e-01_pr)*T_log )
    FC(FOr44f) = ((1.0_pr - -4.748000e-01_pr)*exp(-Tloc/(3.558000e+04_pr)) + (-4.748000e-01_pr)*exp(-Tloc/(1.116000e+03_pr)))&
              + exp(-(9.023000e+03_pr)/Tloc)
    k(r44f) = getlindratecoeff(Tloc, k_0(FOr44f), k_inf(FOr44f),FC(FOr44f), M(mM44),Ploc)
    k_0(FOr45f) =(1.430000e+41_pr)*exp((-4.159611e+05_pr)*R_T_inv + (-8.227000e+00_pr)*T_log )
    k_inf(FOr45f) =(3.121000e+18_pr)*exp((-3.837230e+05_pr)*R_T_inv + (-1.017000e+00_pr)*T_log )
    FC(FOr45f) = ((1.0_pr - 2.545000e+00_pr)*exp(-Tloc/(3.290000e+03_pr)) + (2.545000e+00_pr)*exp(-Tloc/(4.732000e+04_pr)))&
              + exp(-(4.711000e+04_pr)/Tloc)
    k(r45f) = getlindratecoeff(Tloc, k_0(FOr45f), k_inf(FOr45f),FC(FOr45f), M(mM45),Ploc)
    k(r46f) = (3.070000e-01_pr)*exp((-2.276096e+04_pr)*R_T_inv + (2.550000e+00_pr)*T_log )
    k(r47f) = (3.080000e-02_pr)*exp((3.375233e+03_pr)*R_T_inv + (2.650000e+00_pr)*T_log )
    k(r48f) = (1.500000e-04_pr)*exp((3.192392e+03_pr)*R_T_inv + (3.030000e+00_pr)*T_log )
    k(r49f) = (6.030000e+07_pr)
    k_0(FOr50f) =(2.477000e+21_pr)*exp((-1.020896e+04_pr)*R_T_inv + (-4.760000e+00_pr)*T_log )
    k_inf(FOr50f) =(1.270000e+10_pr)*exp((-1.602472e+03_pr)*R_T_inv + (-6.300000e-01_pr)*T_log )
    FC(FOr50f) = ((1.0_pr - 7.830000e-01_pr)*exp(-Tloc/(7.400000e+01_pr)) + (7.830000e-01_pr)*exp(-Tloc/(2.941000e+03_pr)))&
              + exp(-(6.964000e+03_pr)/Tloc)
    k(r50f) = getlindratecoeff(Tloc, k_0(FOr50f), k_inf(FOr50f),FC(FOr50f), M(mM50),Ploc)
    k(r51f) = (6.140000e-01_pr)*exp((-4.011201e+04_pr)*R_T_inv + (2.500000e+00_pr)*T_log )
    k(r52f) = (5.830000e-02_pr)*exp((-9.162960e+03_pr)*R_T_inv + (2.600000e+00_pr)*T_log )
    k(r53f) = (1.020000e+03_pr)*exp((-3.598240e+04_pr)*R_T_inv + (1.500000e+00_pr)*T_log )
    k(r54f) = (1.695000e-05_pr)*exp((-8.790584e+04_pr)*R_T_inv + (3.740000e+00_pr)*T_log )
    k(r55f) = (5.282000e+11_pr)*exp((-7.414048e+03_pr)*R_T_inv + (-1.518000e+00_pr)*T_log )
    k(r56f) = (4.686000e+04_pr)*exp((-1.492014e+04_pr)*R_T_inv + (8.330000e-01_pr)*T_log )
    k(r57f) = (1.230000e+03_pr)*exp((-4.999880e+04_pr)*R_T_inv + (1.011000e+00_pr)*T_log )
    k(r58f) = (1.000000e+06_pr)*exp((2.876500e+03_pr)*R_T_inv + (2.690000e-01_pr)*T_log )
    k(r59f) = (1.160000e-01_pr)*exp((1.264405e+04_pr)*R_T_inv + (2.230000e+00_pr)*T_log )
    k(r60f) = (5.540000e+07_pr)*exp((5.690240e+02_pr)*R_T_inv + (5.000000e-02_pr)*T_log )
    k(r61f) = (7.546000e+06_pr)*exp((-1.184909e+05_pr)*R_T_inv )
    k(r62f) = (2.641000e-06_pr)*exp((-3.391132e+04_pr)*R_T_inv + (3.283000e+00_pr)*T_log )
    k_0(FOr63f) =(6.850000e+12_pr)*exp((-3.000000e+00_pr)*T_log )
    k_inf(FOr63f) =(7.812000e+03_pr)*exp((9.000000e-01_pr)*T_log )
    FC(FOr63f) = ((1.0_pr - 6.000000e-01_pr)*exp(-Tloc/(1.000000e+03_pr)) + (6.000000e-01_pr)*exp(-Tloc/(7.000000e+01_pr)))&
              + exp(-(1.700000e+03_pr)/Tloc)
    k(r63f) = getlindratecoeff(Tloc, k_0(FOr63f), k_inf(FOr63f),FC(FOr63f), M(mM63),Ploc)
    k(r64f) = (1.990000e+06_pr)*exp((-4.878544e+04_pr)*R_T_inv )
    k(r65f) = (9.600000e-07_pr)*exp((-7.451704e+04_pr)*R_T_inv + (3.770000e+00_pr)*T_log )
    k(r66f) = (5.080000e+06_pr)*exp((5.903624e+03_pr)*R_T_inv )
    k(r67f) = (2.470000e+05_pr)*exp((6.568880e+03_pr)*R_T_inv )
    k(r68f) = (3.110000e+08_pr)*exp((4.397384e+03_pr)*R_T_inv + (-1.610000e+00_pr)*T_log )
    k(r69f) = (1.400000e+10_pr)*exp((-7.782240e+03_pr)*R_T_inv + (-1.610000e+00_pr)*T_log )
    k(r70f) = (9.600000e+07_pr)
    k(r71f) = (3.600000e+07_pr)
    k(r72f) = (6.000000e+07_pr)
    k(r73f) = (6.310000e+14_pr)*exp((-1.769832e+05_pr)*R_T_inv )
    k(r74f) = (1.500000e+07_pr)*exp((-2.510400e+03_pr)*R_T_inv )
    k(r75f) = (3.000000e+07_pr)
    k(r76f) = (7.000000e+07_pr)
    k(r77f) = (2.800000e+07_pr)
    k(r78f) = (1.200000e+07_pr)
    k(r79f) = (3.000000e+07_pr)
    k(r80f) = (1.400000e+07_pr)
    k_0(FOr81f) =(3.200000e+15_pr)*exp((-5.146320e+03_pr)*R_T_inv + (-3.140000e+00_pr)*T_log )
    k_inf(FOr81f) =(2.500000e+10_pr)*exp((-8.000000e-01_pr)*T_log )
    FC(FOr81f) = ((1.0_pr - 6.800000e-01_pr)*exp(-Tloc/(7.800000e+01_pr)) + (6.800000e-01_pr)*exp(-Tloc/(1.995000e+03_pr)))&
              + exp(-(5.590000e+03_pr)/Tloc)
    k(r81f) = getlindratecoeff(Tloc, k_0(FOr81f), k_inf(FOr81f),FC(FOr81f), M(mM81),Ploc)
    k(r82f) = (1.060000e+07_pr)*exp((-6.276000e+03_pr)*R_T_inv )
    k(r83f) = (2.640000e+06_pr)*exp((-6.276000e+03_pr)*R_T_inv )
    k(r84f) = (5.000000e+07_pr)
    k_0(FOr85f) =(8.054000e+19_pr)*exp((-4.107014e+03_pr)*R_T_inv + (-3.750000e+00_pr)*T_log )
    k_inf(FOr85f) =(2.277000e+09_pr)*exp((-7.317816e+02_pr)*R_T_inv + (-6.900000e-01_pr)*T_log )
    FC(FOr85f) = ((1.0_pr - 0.000000e+00_pr)*exp(-Tloc/(5.700000e+02_pr)) + (0.000000e+00_pr)*exp(-Tloc/(1.000000e+30_pr)))&
              + exp(-(1.000000e+30_pr)/Tloc)
    k(r85f) = getlindratecoeff(Tloc, k_0(FOr85f), k_inf(FOr85f),FC(FOr85f), M(mM85),Ploc)
    k_0(FOr86f) =(1.990000e+29_pr)*exp((-2.797004e+04_pr)*R_T_inv + (-7.080000e+00_pr)*T_log )
    k_inf(FOr86f) =(5.210000e+11_pr)*exp((-6.610720e+03_pr)*R_T_inv + (-9.900000e-01_pr)*T_log )
    FC(FOr86f) = ((1.0_pr - 8.420000e-01_pr)*exp(-Tloc/(1.250000e+02_pr)) + (8.420000e-01_pr)*exp(-Tloc/(2.219000e+03_pr)))&
              + exp(-(6.882000e+03_pr)/Tloc)
    k(r86f) = getlindratecoeff(Tloc, k_0(FOr86f), k_inf(FOr86f),FC(FOr86f), M(mM86),Ploc)
    k(r87f) = (1.150000e+02_pr)*exp((-3.150552e+04_pr)*R_T_inv + (1.900000e+00_pr)*T_log )
    k(r88f) = (3.550000e+00_pr)*exp((-2.439272e+04_pr)*R_T_inv + (2.400000e+00_pr)*T_log )
    k(r89f) = (1.480000e+01_pr)*exp((-3.974800e+03_pr)*R_T_inv + (1.900000e+00_pr)*T_log )
    k(r90f) = (5.480000e-07_pr)*exp((-3.464352e+04_pr)*R_T_inv + (4.000000e+00_pr)*T_log )
    k(r91f) = (3.460000e-05_pr)*exp((-7.079328e+04_pr)*R_T_inv + (3.610000e+00_pr)*T_log )
    k_0(FOr92f) =(1.419000e+27_pr)*exp((-2.413750e+04_pr)*R_T_inv + (-6.642000e+00_pr)*T_log )
    k_inf(FOr92f) =(9.569000e+02_pr)*exp((-5.669320e+03_pr)*R_T_inv + (1.463000e+00_pr)*T_log )
    FC(FOr92f) = ((1.0_pr - -5.690000e-01_pr)*exp(-Tloc/(2.990000e+02_pr)) + (-5.690000e-01_pr)*exp(-Tloc/(-9.147000e+03_pr)))&
              + exp(-(1.524000e+02_pr)/Tloc)
    k(r92f) = getlindratecoeff(Tloc, k_0(FOr92f), k_inf(FOr92f),FC(FOr92f), M(mM92),Ploc)
    k(r93f) = (1.500000e+08_pr)*exp((-1.089095e+05_pr)*R_T_inv )
    k(r94f) = (1.180000e-02_pr)*exp((1.222146e+04_pr)*R_T_inv + (2.450000e+00_pr)*T_log )
    k(r95f) = (3.100000e+08_pr)*exp((-5.595054e+04_pr)*R_T_inv + (-3.620000e-01_pr)*T_log )
    k(r96f) = (1.843000e+01_pr)*exp((3.014990e+03_pr)*R_T_inv + (1.130000e+00_pr)*T_log )
    k_0(FOr97f) =(6.000000e+23_pr)*exp((-1.816856e+05_pr)*R_T_inv + (-3.800000e+00_pr)*T_log )
    k_inf(FOr97f) =(1.430000e+15_pr)*exp((-1.907904e+05_pr)*R_T_inv + (-1.500000e-01_pr)*T_log )
    FC(FOr97f) = ((1.0_pr - 9.850000e-01_pr)*exp(-Tloc/(3.930000e+02_pr)) + (9.850000e-01_pr)*exp(-Tloc/(9.800000e+09_pr)))&
              + exp(-(5.000000e+09_pr)/Tloc)
    k(r97f) = getlindratecoeff(Tloc, k_0(FOr97f), k_inf(FOr97f),FC(FOr97f), M(mM97),Ploc)
    k_0(FOr98f) =(9.520000e+27_pr)*exp((-1.727992e+05_pr)*R_T_inv + (-5.070000e+00_pr)*T_log )
    k_inf(FOr98f) =(2.930000e+12_pr)*exp((-1.686152e+05_pr)*R_T_inv + (2.900000e-01_pr)*T_log )
    FC(FOr98f) = ((1.0_pr - 7.130000e-17_pr)*exp(-Tloc/(1.150000e+03_pr)) + (7.130000e-17_pr)*exp(-Tloc/(4.990000e+09_pr)))&
              + exp(-(1.790000e+09_pr)/Tloc)
    k(r98f) = getlindratecoeff(Tloc, k_0(FOr98f), k_inf(FOr98f),FC(FOr98f), M(mM98),Ploc)
    k(r99f) = (1.650000e+13_pr)*exp((-4.326256e+04_pr)*R_T_inv + (-2.220000e+00_pr)*T_log )
    k(r100f) = (1.401000e+09_pr)*exp((-3.674891e+04_pr)*R_T_inv + (-1.710000e-01_pr)*T_log )
    k(r101f) = (7.704000e+07_pr)*exp((-1.750251e+04_pr)*R_T_inv + (-1.710000e-01_pr)*T_log )
    k(r102f) = (1.000000e+07_pr)*exp((-8.368000e+03_pr)*R_T_inv )
    k(r103f) = (1.000000e+08_pr)
    k(r104f) = (1.000000e+08_pr)
    k(r105f) = (1.910000e+05_pr)*exp((-4.267680e+03_pr)*R_T_inv + (-2.000000e-02_pr)*T_log )
    k(r106f) = (4.780000e+06_pr)*exp((-4.811600e+03_pr)*R_T_inv + (-1.420000e-01_pr)*T_log )
    k(r107f) = (5.070000e+01_pr)*exp((-5.418280e+04_pr)*R_T_inv + (1.930000e+00_pr)*T_log )
    k(r108f) = (7.453000e+00_pr)*exp((-7.656720e+02_pr)*R_T_inv + (1.880000e+00_pr)*T_log )
    k(r109f) = (6.098000e+00_pr)*exp((-7.656720e+02_pr)*R_T_inv + (1.880000e+00_pr)*T_log )
    k(r110f) = (2.230000e-02_pr)*exp((-9.269652e+03_pr)*R_T_inv + (2.745000e+00_pr)*T_log )
    k(r111f) = (6.620000e-06_pr)*exp((-3.974800e+04_pr)*R_T_inv + (3.700000e+00_pr)*T_log )
    k_0(FOr112f) =(6.346000e+19_pr)*exp((-1.581552e+04_pr)*R_T_inv + (-4.664000e+00_pr)*T_log )
    k_inf(FOr112f) =(1.710000e+04_pr)*exp((-1.133446e+04_pr)*R_T_inv + (1.266000e+00_pr)*T_log )
    FC(FOr112f) = ((1.0_pr - 7.880000e-01_pr)*exp(-Tloc/(-1.020000e+04_pr)) + (7.880000e-01_pr)*exp(-Tloc/(1.000000e-30_pr)))
    k(r112f) = getlindratecoeff(Tloc, k_0(FOr112f), k_inf(FOr112f),FC(FOr112f), M(mM112),Ploc)
    k(r113f) = (1.700000e+23_pr)*exp((-2.720897e+04_pr)*R_T_inv + (-5.312000e+00_pr)*T_log )
    k(r114f) = (5.190000e+09_pr)*exp((-1.385992e+04_pr)*R_T_inv + (-1.260000e+00_pr)*T_log )
    k(r115f) = (9.000000e+07_pr)
    k(r116f) = (3.011000e+07_pr)
    k(r117f) = (7.528000e+00_pr)*exp((-8.811504e+03_pr)*R_T_inv + (1.550000e+00_pr)*T_log )
    k(r1b) = (4.615442e+05_pr)*exp((5.835146e+03_pr)*R_T_inv + (3.353172e-01_pr)*T_log )
    k(r2b) = (2.536907e-02_pr)*exp((-2.030601e+04_pr)*R_T_inv + (2.656775e+00_pr)*T_log )
    k(r3b) = (1.592922e+08_pr)*exp((-9.088480e+04_pr)*R_T_inv + (3.374882e-02_pr)*T_log )
    k(r4b) = (4.078279e-01_pr)*exp((1.159275e+04_pr)*R_T_inv + (1.973026e+00_pr)*T_log )
    k(r5b) = (2.608371e+08_pr)*exp((-4.068153e+03_pr)*R_T_inv + (-1.784421e+00_pr)*T_log )
    k(r6b) = (4.130875e+11_pr)*exp((-4.267217e+05_pr)*R_T_inv + (-6.288039e-01_pr)*T_log )
    k(r7b) = (2.233572e+16_pr)*exp((-4.943801e+05_pr)*R_T_inv + (-1.581830e+00_pr)*T_log )
    k_0(FOr8b) =(7.529529e+12_pr)*exp((-2.036382e+05_pr)*R_T_inv + (-1.093623e+00_pr)*T_log )
    k_inf(FOr8b) =(2.015677e+12_pr)*exp((-2.036382e+05_pr)*R_T_inv + (5.763768e-01_pr)*T_log )
    FC(FOr8b) = ((1.0_pr - 6.700000e-01_pr)*exp(-Tloc/(1.000000e-30_pr)) + (6.700000e-01_pr)*exp(-Tloc/(1.000000e+30_pr)))&
              + exp(-(1.000000e+30_pr)/Tloc)
    k(r8b) = getlindratecoeff(Tloc, k_0(FOr8b), k_inf(FOr8b),FC(FOr8b), M(mM8),Ploc)
    k(r9b) = (6.350915e+04_pr)*exp((-1.545260e+05_pr)*R_T_inv + (5.701365e-01_pr)*T_log )
    k(r10b) = (1.278646e+00_pr)*exp((5.250853e+03_pr)*R_T_inv + (2.184956e+00_pr)*T_log )
    k(r11b) = (6.570037e+06_pr)*exp((-2.230835e+05_pr)*R_T_inv + (2.348193e-01_pr)*T_log )
    k(r12b) = (3.615699e+07_pr)*exp((-2.886624e+05_pr)*R_T_inv + (2.817931e-01_pr)*T_log )
    k(r13b) = (5.967381e+06_pr)*exp((-1.542237e+05_pr)*R_T_inv + (-2.398911e-01_pr)*T_log )
    k(r14b) = (1.679129e+10_pr)*exp((-2.112516e+05_pr)*R_T_inv + (-2.398911e-01_pr)*T_log )
    k_0(FOr15b) =(8.408816e+08_pr)*exp((7.424250e+03_pr)*R_T_inv + (-1.626349e+00_pr)*T_log )
    k_inf(FOr15b) =(9.017497e+01_pr)*exp((7.424250e+03_pr)*R_T_inv + (1.573651e+00_pr)*T_log )
    FC(FOr15b) = ((1.0_pr - 5.100000e-01_pr)*exp(-Tloc/(1.000000e-30_pr)) + (5.100000e-01_pr)*exp(-Tloc/(1.000000e+30_pr)))
    k(r15b) = getlindratecoeff(Tloc, k_0(FOr15b), k_inf(FOr15b),FC(FOr15b), M(mM15),Ploc)
    k_0(FOr16b) =(1.122678e+08_pr)*exp((7.424250e+03_pr)*R_T_inv + (-1.626349e+00_pr)*T_log )
    k_inf(FOr16b) =(9.017497e+01_pr)*exp((7.424250e+03_pr)*R_T_inv + (1.573651e+00_pr)*T_log )
    FC(FOr16b) = ((1.0_pr - 4.300000e-01_pr)*exp(-Tloc/(1.000000e-30_pr)) + (4.300000e-01_pr)*exp(-Tloc/(1.000000e+30_pr)))
    k(r16b) = getlindratecoeff(Tloc, k_0(FOr16b), k_inf(FOr16b),FC(FOr16b), M(mM16),Ploc)
    k(r17b) = (6.934337e+02_pr)*exp((-2.996005e+05_pr)*R_T_inv + (1.091821e+00_pr)*T_log )
    k(r18b) = (1.896014e+02_pr)*exp((-9.316365e+04_pr)*R_T_inv + (1.487935e+00_pr)*T_log )
    k(r19b) = (4.205788e-02_pr)*exp((-7.865041e+04_pr)*R_T_inv + (2.474710e+00_pr)*T_log )
    k(r20b) = (2.434251e+06_pr)*exp((-1.601118e+05_pr)*R_T_inv + (5.216842e-01_pr)*T_log )
    k_0(FOr21b) =(1.295503e+23_pr)*exp((-5.502659e+05_pr)*R_T_inv + (-3.511699e+00_pr)*T_log )
    k_inf(FOr21b) =(1.504241e+15_pr)*exp((-5.427054e+05_pr)*R_T_inv + (-7.216986e-01_pr)*T_log )
    redP = abs(k_0(FOr21b)) * M(mM21) / max(abs(k_inf(FOr21b)), tiny(1.0_pr)) + tiny(1.0_pr)
    k(r21b) = k_inf(FOr21b) * redP / ( 1.0_pr + redP )
    k(r22b) = (8.841290e+04_pr)*exp((-1.045208e+05_pr)*R_T_inv + (9.601053e-01_pr)*T_log )
    k(r23b) = (7.255782e+12_pr)*exp((-1.073973e+05_pr)*R_T_inv + (-1.756895e+00_pr)*T_log )
    k(r24b) = (1.775219e+02_pr)*exp((-3.343617e+05_pr)*R_T_inv + (1.657242e+00_pr)*T_log )
    k(r25b) = (3.453160e-01_pr)*exp((1.763634e+03_pr)*R_T_inv + (7.554170e-01_pr)*T_log )
    k(r26b) = (1.990577e+06_pr)*exp((-1.413740e+05_pr)*R_T_inv + (2.317938e-01_pr)*T_log )
    k(r27b) = (7.802780e+06_pr)*exp((-3.687617e+05_pr)*R_T_inv + (4.798380e-01_pr)*T_log )
    k(r28b) = (3.943428e+07_pr)*exp((-4.304004e+05_pr)*R_T_inv + (5.135869e-01_pr)*T_log )
    k(r29b) = (1.753251e+08_pr)*exp((-3.741021e+05_pr)*R_T_inv + (3.808988e-01_pr)*T_log )
    k(r30b) = (5.430642e+08_pr)*exp((-5.959748e+04_pr)*R_T_inv + (-1.544625e-01_pr)*T_log )
    k(r31b) = (1.833402e+12_pr)*exp((-7.331502e+04_pr)*R_T_inv + (2.654950e-01_pr)*T_log )
    k(r32b) = (7.747263e+00_pr)*exp((-1.224159e+05_pr)*R_T_inv + (1.757331e+00_pr)*T_log )
    k(r33b) = (1.563627e+00_pr)*exp((-7.665558e+04_pr)*R_T_inv + (1.993582e+00_pr)*T_log )
    k(r34b) = (8.516015e+01_pr)*exp((-6.862754e+04_pr)*R_T_inv + (1.230357e+00_pr)*T_log )
    k(r35b) = (6.493291e-05_pr)*exp((-8.857319e+04_pr)*R_T_inv + (3.354642e+00_pr)*T_log )
    k(r36b) = (5.807322e-02_pr)*exp((-4.533145e+04_pr)*R_T_inv + (2.305646e+00_pr)*T_log )
    k_0(FOr37b) =(5.898269e+10_pr)*exp((-1.349203e+04_pr)*R_T_inv + (-2.326917e+00_pr)*T_log )
    k_inf(FOr37b) =(2.148271e+05_pr)*exp((-2.128682e+04_pr)*R_T_inv + (6.730833e-01_pr)*T_log )
    FC(FOr37b) = ((1.0_pr - 9.000000e-01_pr)*exp(-Tloc/(2.500000e+03_pr)) + (9.000000e-01_pr)*exp(-Tloc/(1.300000e+03_pr)))&
              + exp(-(1.000000e+99_pr)/Tloc)
    k(r37b) = getlindratecoeff(Tloc, k_0(FOr37b), k_inf(FOr37b),FC(FOr37b), M(mM37),Ploc)
    k(r38b) = (5.998219e-28_pr)*exp((-9.241359e+04_pr)*R_T_inv + (1.030946e+01_pr)*T_log )
    k(r39b) = (4.140168e+05_pr)*exp((-3.498734e+05_pr)*R_T_inv + (9.585651e-01_pr)*T_log )
    k(r40b) = (1.108720e+04_pr)*exp((-3.445330e+05_pr)*R_T_inv + (1.057504e+00_pr)*T_log )
    k_0(FOr41b) =(1.031007e+27_pr)*exp((-1.517569e+05_pr)*R_T_inv + (-5.175852e+00_pr)*T_log )
    k_inf(FOr41b) =(4.383811e+12_pr)*exp((-1.394978e+05_pr)*R_T_inv + (9.814762e-02_pr)*T_log )
    FC(FOr41b) = ((1.0_pr - 7.187000e-01_pr)*exp(-Tloc/(1.030000e+02_pr)) + (7.187000e-01_pr)*exp(-Tloc/(1.291000e+03_pr)))&
              + exp(-(4.160000e+03_pr)/Tloc)
    k(r41b) = getlindratecoeff(Tloc, k_0(FOr41b), k_inf(FOr41b),FC(FOr41b), M(mM41),Ploc)
    k(r42b) = (1.286847e+07_pr)*exp((-1.001940e+05_pr)*R_T_inv + (4.922291e-01_pr)*T_log )
    k(r43b) = (1.886623e+06_pr)*exp((-3.699447e+05_pr)*R_T_inv + (7.740222e-01_pr)*T_log )
    k_0(FOr44b) =(4.857833e+27_pr)*exp((-2.434159e+04_pr)*R_T_inv + (-6.730355e+00_pr)*T_log )
    k_inf(FOr44b) =(6.749149e+08_pr)*exp((-1.532093e+03_pr)*R_T_inv + (-3.503550e-01_pr)*T_log )
    FC(FOr44b) = ((1.0_pr - -4.748000e-01_pr)*exp(-Tloc/(3.558000e+04_pr)) + (-4.748000e-01_pr)*exp(-Tloc/(1.116000e+03_pr)))&
              + exp(-(9.023000e+03_pr)/Tloc)
    k(r44b) = getlindratecoeff(Tloc, k_0(FOr44b), k_inf(FOr44b),FC(FOr44b), M(mM44),Ploc)
    k_0(FOr45b) =(2.271301e+30_pr)*exp((-2.601946e+04_pr)*R_T_inv + (-7.530502e+00_pr)*T_log )
    k_inf(FOr45b) =(4.957155e+07_pr)*exp((6.218682e+03_pr)*R_T_inv + (-3.205022e-01_pr)*T_log )
    FC(FOr45b) = ((1.0_pr - 2.545000e+00_pr)*exp(-Tloc/(3.290000e+03_pr)) + (2.545000e+00_pr)*exp(-Tloc/(4.732000e+04_pr)))&
              + exp(-(4.711000e+04_pr)/Tloc)
    k(r45b) = getlindratecoeff(Tloc, k_0(FOr45b), k_inf(FOr45b),FC(FOr45b), M(mM45),Ploc)
    k(r46b) = (5.968997e-02_pr)*exp((-5.556472e+04_pr)*R_T_inv + (2.356895e+00_pr)*T_log )
    k(r47b) = (2.177881e-02_pr)*exp((-9.106717e+04_pr)*R_T_inv + (2.490643e+00_pr)*T_log )
    k(r48b) = (4.135579e-03_pr)*exp((-5.502308e+04_pr)*R_T_inv + (2.553412e+00_pr)*T_log )
    k(r49b) = (4.409449e+03_pr)*exp((-3.479562e+05_pr)*R_T_inv + (1.567841e+00_pr)*T_log )
    k_0(FOr50b) =(2.705095e+28_pr)*exp((-4.482908e+05_pr)*R_T_inv + (-4.474518e+00_pr)*T_log )
    k_inf(FOr50b) =(1.386948e+17_pr)*exp((-4.396843e+05_pr)*R_T_inv + (-3.445182e-01_pr)*T_log )
    FC(FOr50b) = ((1.0_pr - 7.830000e-01_pr)*exp(-Tloc/(7.400000e+01_pr)) + (7.830000e-01_pr)*exp(-Tloc/(2.941000e+03_pr)))&
              + exp(-(6.964000e+03_pr)/Tloc)
    k(r50b) = getlindratecoeff(Tloc, k_0(FOr50b), k_inf(FOr50b),FC(FOr50b), M(mM50),Ploc)
    k(r51b) = (9.865598e-03_pr)*exp((-3.477164e+04_pr)*R_T_inv + (2.598939e+00_pr)*T_log )
    k(r52b) = (3.406779e-03_pr)*exp((-6.546123e+04_pr)*R_T_inv + (2.732688e+00_pr)*T_log )
    k(r53b) = (8.184576e+00_pr)*exp((-2.462232e+04_pr)*R_T_inv + (1.585714e+00_pr)*T_log )
    k(r54b) = (3.088315e-05_pr)*exp((-1.450583e+04_pr)*R_T_inv + (3.351004e+00_pr)*T_log )
    k(r55b) = (2.590513e+10_pr)*exp((-3.130134e+03_pr)*R_T_inv + (-1.086147e+00_pr)*T_log )
    k(r56b) = (1.603255e+08_pr)*exp((-6.402355e+02_pr)*R_T_inv + (-9.171482e-03_pr)*T_log )
    k(r57b) = (1.640843e+08_pr)*exp((5.080403e+02_pr)*R_T_inv + (-1.484024e-01_pr)*T_log )
    k(r58b) = (1.196813e+08_pr)*exp((-9.990839e+04_pr)*R_T_inv + (-3.202659e-01_pr)*T_log )
    k(r59b) = (2.922441e+00_pr)*exp((-2.217995e+05_pr)*R_T_inv + (2.379105e+00_pr)*T_log )
    k(r60b) = (2.045994e+09_pr)*exp((-2.874374e+05_pr)*R_T_inv + (-6.512303e-02_pr)*T_log )
    k(r61b) = (4.467439e+09_pr)*exp((1.807730e+03_pr)*R_T_inv + (-8.240852e-01_pr)*T_log )
    k(r62b) = (4.328554e-07_pr)*exp((-2.521260e+05_pr)*R_T_inv + (3.503194e+00_pr)*T_log )
    k_0(FOr63b) =(1.885744e+23_pr)*exp((-1.357623e+05_pr)*R_T_inv + (-3.764212e+00_pr)*T_log )
    k_inf(FOr63b) =(2.150575e+14_pr)*exp((-1.357623e+05_pr)*R_T_inv + (1.357882e-01_pr)*T_log )
    FC(FOr63b) = ((1.0_pr - 6.000000e-01_pr)*exp(-Tloc/(1.000000e+03_pr)) + (6.000000e-01_pr)*exp(-Tloc/(7.000000e+01_pr)))&
              + exp(-(1.700000e+03_pr)/Tloc)
    k(r63b) = getlindratecoeff(Tloc, k_0(FOr63b), k_inf(FOr63b),FC(FOr63b), M(mM63),Ploc)
    k(r64b) = (8.949916e+08_pr)*exp((-3.796703e+04_pr)*R_T_inv + (-1.183389e+00_pr)*T_log )
    k(r65b) = (2.546660e-04_pr)*exp((6.833154e+03_pr)*R_T_inv + (2.591969e+00_pr)*T_log )
    k(r66b) = (1.277108e+09_pr)*exp((-1.142504e+05_pr)*R_T_inv + (-8.480798e-01_pr)*T_log )
    k(r67b) = (1.650765e+09_pr)*exp((-1.465245e+05_pr)*R_T_inv + (-1.028926e+00_pr)*T_log )
    k(r70b) = (1.809144e+05_pr)*exp((-1.706608e+05_pr)*R_T_inv + (3.113226e-01_pr)*T_log )
    k(r71b) = (1.528708e+07_pr)*exp((-2.404526e+05_pr)*R_T_inv + (-2.399457e-02_pr)*T_log )
    k(r72b) = (6.729886e+06_pr)*exp((-2.498955e+05_pr)*R_T_inv + (4.995668e-01_pr)*T_log )
    k(r73b) = (4.104641e+02_pr)*exp((9.087604e+03_pr)*R_T_inv + (1.203872e+00_pr)*T_log )
    k(r74b) = (1.316080e+07_pr)*exp((-4.014551e+04_pr)*R_T_inv + (-8.252791e-02_pr)*T_log )
    k(r75b) = (1.645159e+11_pr)*exp((-3.599487e+05_pr)*R_T_inv + (-5.000020e-01_pr)*T_log )
    k(r76b) = (5.190761e+09_pr)*exp((-6.592255e+04_pr)*R_T_inv + (-3.981040e-01_pr)*T_log )
    k(r78b) = (1.535973e+06_pr)*exp((-7.797290e+05_pr)*R_T_inv + (4.292588e-01_pr)*T_log )
    k(r79b) = (2.632160e+07_pr)*exp((-3.763511e+04_pr)*R_T_inv + (-8.252791e-02_pr)*T_log )
    k(r80b) = (6.091534e+04_pr)*exp((-2.539397e+05_pr)*R_T_inv + (5.928926e-01_pr)*T_log )
    k_0(FOr81b) =(4.745735e+22_pr)*exp((-4.661752e+05_pr)*R_T_inv + (-3.071155e+00_pr)*T_log )
    k_inf(FOr81b) =(3.707605e+17_pr)*exp((-4.610289e+05_pr)*R_T_inv + (-7.311550e-01_pr)*T_log )
    FC(FOr81b) = ((1.0_pr - 6.800000e-01_pr)*exp(-Tloc/(7.800000e+01_pr)) + (6.800000e-01_pr)*exp(-Tloc/(1.995000e+03_pr)))&
              + exp(-(5.590000e+03_pr)/Tloc)
    k(r81b) = getlindratecoeff(Tloc, k_0(FOr81b), k_inf(FOr81b),FC(FOr81b), M(mM81),Ploc)
    k(r82b) = (3.999848e+06_pr)*exp((-3.179695e+05_pr)*R_T_inv + (-1.800165e-03_pr)*T_log )
    k(r84b) = (2.830047e+07_pr)*exp((-5.774400e+05_pr)*R_T_inv + (1.558144e-01_pr)*T_log )
    k_0(FOr85b) =(1.245762e+32_pr)*exp((-3.836385e+05_pr)*R_T_inv + (-4.535345e+00_pr)*T_log )
    k_inf(FOr85b) =(3.521976e+21_pr)*exp((-3.802633e+05_pr)*R_T_inv + (-1.475345e+00_pr)*T_log )
    FC(FOr85b) = ((1.0_pr - 0.000000e+00_pr)*exp(-Tloc/(5.700000e+02_pr)) + (0.000000e+00_pr)*exp(-Tloc/(1.000000e+30_pr)))&
              + exp(-(1.000000e+30_pr)/Tloc)
    k(r85b) = getlindratecoeff(Tloc, k_0(FOr85b), k_inf(FOr85b),FC(FOr85b), M(mM85),Ploc)
    k_0(FOr86b) =(1.996591e+37_pr)*exp((-4.494293e+05_pr)*R_T_inv + (-6.972214e+00_pr)*T_log )
    k_inf(FOr86b) =(5.227255e+19_pr)*exp((-4.280700e+05_pr)*R_T_inv + (-8.822137e-01_pr)*T_log )
    FC(FOr86b) = ((1.0_pr - 8.420000e-01_pr)*exp(-Tloc/(1.250000e+02_pr)) + (8.420000e-01_pr)*exp(-Tloc/(2.219000e+03_pr)))&
              + exp(-(6.882000e+03_pr)/Tloc)
    k(r86b) = getlindratecoeff(Tloc, k_0(FOr86b), k_inf(FOr86b),FC(FOr86b), M(mM86),Ploc)
    k(r87b) = (2.011285e-01_pr)*exp((-4.278768e+04_pr)*R_T_inv + (2.176635e+00_pr)*T_log )
    k(r88b) = (3.100593e-03_pr)*exp((-2.965516e+04_pr)*R_T_inv + (2.663410e+00_pr)*T_log )
    k(r89b) = (9.413641e-02_pr)*exp((-7.689559e+04_pr)*R_T_inv + (2.210384e+00_pr)*T_log )
    k(r90b) = (5.964871e-08_pr)*exp((-5.126604e+04_pr)*R_T_inv + (4.177695e+00_pr)*T_log )
    k(r91b) = (6.861965e-06_pr)*exp((-1.401579e+04_pr)*R_T_inv + (3.398699e+00_pr)*T_log )
    k_0(FOr92b) =(7.606229e+32_pr)*exp((-1.717304e+05_pr)*R_T_inv + (-6.613318e+00_pr)*T_log )
    k_inf(FOr92b) =(5.129246e+08_pr)*exp((-1.532622e+05_pr)*R_T_inv + (1.491682e+00_pr)*T_log )
    FC(FOr92b) = ((1.0_pr - -5.690000e-01_pr)*exp(-Tloc/(2.990000e+02_pr)) + (-5.690000e-01_pr)*exp(-Tloc/(-9.147000e+03_pr)))&
              + exp(-(1.524000e+02_pr)/Tloc)
    k(r92b) = getlindratecoeff(Tloc, k_0(FOr92b), k_inf(FOr92b),FC(FOr92b), M(mM92),Ploc)
    k(r93b) = (2.476487e+12_pr)*exp((-3.289969e+04_pr)*R_T_inv + (-1.276971e+00_pr)*T_log )
    k(r94b) = (2.404092e-01_pr)*exp((-2.782674e+05_pr)*R_T_inv + (2.706800e+00_pr)*T_log )
    k(r95b) = (4.779132e+12_pr)*exp((-1.402273e+04_pr)*R_T_inv + (-1.255131e+00_pr)*T_log )
    k(r96b) = (1.490412e+01_pr)*exp((-5.303034e+04_pr)*R_T_inv + (1.237694e+00_pr)*T_log )
    k_0(FOr97b) =(2.238425e+17_pr)*exp((-2.569615e+04_pr)*R_T_inv + (-3.705695e+00_pr)*T_log )
    k_inf(FOr97b) =(5.334912e+08_pr)*exp((-3.480095e+04_pr)*R_T_inv + (-5.569512e-02_pr)*T_log )
    FC(FOr97b) = ((1.0_pr - 9.850000e-01_pr)*exp(-Tloc/(3.930000e+02_pr)) + (9.850000e-01_pr)*exp(-Tloc/(9.800000e+09_pr)))&
              + exp(-(5.000000e+09_pr)/Tloc)
    k(r97b) = getlindratecoeff(Tloc, k_0(FOr97b), k_inf(FOr97b),FC(FOr97b), M(mM97),Ploc)
    k_0(FOr98b) =(2.962373e+15_pr)*exp((-1.463346e+05_pr)*R_T_inv + (-3.559224e+00_pr)*T_log )
    k_inf(FOr98b) =(9.117385e-01_pr)*exp((-1.421506e+05_pr)*R_T_inv + (1.800776e+00_pr)*T_log )
    FC(FOr98b) = ((1.0_pr - 7.130000e-17_pr)*exp(-Tloc/(1.150000e+03_pr)) + (7.130000e-17_pr)*exp(-Tloc/(4.990000e+09_pr)))&
              + exp(-(1.790000e+09_pr)/Tloc)
    k(r98b) = getlindratecoeff(Tloc, k_0(FOr98b), k_inf(FOr98b),FC(FOr98b), M(mM98),Ploc)
    k(r100b) = (3.306841e+07_pr)*exp((-2.686873e+04_pr)*R_T_inv + (-4.771865e-02_pr)*T_log )
    k(r101b) = (6.425810e+01_pr)*exp((-1.470273e+05_pr)*R_T_inv + (1.245471e+00_pr)*T_log )
    k(r102b) = (8.584118e+05_pr)*exp((-6.012646e+04_pr)*R_T_inv + (1.570301e-01_pr)*T_log )
    k(r104b) = (4.765443e+01_pr)*exp((-7.348242e+04_pr)*R_T_inv + (1.691294e+00_pr)*T_log )
    k(r107b) = (9.464868e-02_pr)*exp((-2.596913e+04_pr)*R_T_inv + (2.253716e+00_pr)*T_log )
    k(r108b) = (1.485713e-03_pr)*exp((-1.107428e+05_pr)*R_T_inv + (2.395851e+00_pr)*T_log )
    k(r109b) = (2.366629e+03_pr)*exp((-7.322773e+04_pr)*R_T_inv + (9.804921e-01_pr)*T_log )
    k(r110b) = (1.514021e-04_pr)*exp((-4.269462e+04_pr)*R_T_inv + (3.102465e+00_pr)*T_log )
    k(r111b) = (7.691475e-07_pr)*exp((-1.687470e+04_pr)*R_T_inv + (3.924777e+00_pr)*T_log )
    k_0(FOr112b) =(4.497092e+23_pr)*exp((-1.627644e+05_pr)*R_T_inv + (-4.039608e+00_pr)*T_log )
    k_inf(FOr112b) =(1.211791e+08_pr)*exp((-1.582833e+05_pr)*R_T_inv + (1.890392e+00_pr)*T_log )
    FC(FOr112b) = ((1.0_pr - 7.880000e-01_pr)*exp(-Tloc/(-1.020000e+04_pr)) + (7.880000e-01_pr)*exp(-Tloc/(1.000000e-30_pr)))
    k(r112b) = getlindratecoeff(Tloc, k_0(FOr112b), k_inf(FOr112b),FC(FOr112b), M(mM112),Ploc)
    k(r113b) = (5.957714e+21_pr)*exp((-3.896341e+05_pr)*R_T_inv + (-4.886446e+00_pr)*T_log )
    k(r115b) = (2.228550e+09_pr)*exp((-2.857926e+05_pr)*R_T_inv + (-2.399708e-01_pr)*T_log )
    k(r116b) = (2.711508e+09_pr)*exp((-3.474312e+05_pr)*R_T_inv + (-2.062220e-01_pr)*T_log )
    k(r117b) = (8.285100e+03_pr)*exp((-1.064663e+05_pr)*R_T_inv + (1.058698e+00_pr)*T_log )
  
    return
  end subroutine get_rate_coefficients

  ! ----------------------------------------------- !
  ! Evaluate reaction rates                         !
  ! ----------------------------------------------- !
  subroutine get_reaction_rates(w,k,m,c,cqss)
    implicit none

    real(pr), dimension(nspec) :: c
    real(pr), dimension(nqss) :: cqss
    real(pr), dimension(nreac + nreac_reverse) :: w,k
    real(pr), dimension(nTB + nFO) :: m

    w(r1f) = k(r1f) * c(sH) * c(sO2) 
    w(r2f) = k(r2f) * c(sH2) * cqss(sqssO) 
    w(r3f) = k(r3f) * c(sH2) * c(sOH) 
    w(r4f) = k(r4f) * c(sH2O) * cqss(sqssO) 
    w(r5f) = k(r5f) * c(sH2) * m(mM5)
    w(r6f) = k(r6f) * c(sH) * cqss(sqssO) * m(mM6)
    w(r7f) = k(r7f) * c(sH) * c(sOH) * m(mM7)
    w(r8f) = k(r8f) * c(sH) * c(sO2) 
    w(r9f) = k(r9f) * c(sH) * c(sHO2) 
    w(r10f) = k(r10f) * c(sH2) * c(sO2) 
    w(r11f) = k(r11f) * c(sHO2) * cqss(sqssO) 
    w(r12f) = k(r12f) * c(sHO2) * c(sOH) 
    w(r13f) = k(r13f) * c(sHO2)**2.0_pr 
    w(r14f) = k(r14f) * c(sHO2)**2.0_pr 
    w(r15f) = k(r15f) * c(sH2O2) 
    w(r16f) = k(r16f) * c(sH2O2) 
    w(r17f) = k(r17f) * c(sH) * c(sH2O2) 
    w(r18f) = k(r18f) * c(sH) * c(sH2O2) 
    w(r19f) = k(r19f) * c(sH2O2) * cqss(sqssO) 
    w(r20f) = k(r20f) * c(sH2O2) * c(sOH) 
    w(r21f) = k(r21f) * c(sCO) * cqss(sqssO) 
    w(r22f) = k(r22f) * c(sCO) * c(sOH) 
    w(r23f) = k(r23f) * c(sCO) * c(sOH) 
    w(r24f) = k(r24f) * c(sCO) * c(sHO2) 
    w(r25f) = k(r25f) * cqss(sqssHCO) * m(mM25)
    w(r26f) = k(r26f) * cqss(sqssHCO) * c(sO2) 
    w(r27f) = k(r27f) * c(sH) * cqss(sqssHCO) 
    w(r28f) = k(r28f) * cqss(sqssHCO) * c(sOH) 
    w(r29f) = k(r29f) * c(sCH3) * cqss(sqssHCO) 
    w(r30f) = k(r30f) * c(sCH2O) * c(sO2) 
    w(r31f) = k(r31f) * c(sCO2) * c(sH) 
    w(r32f) = k(r32f) * c(sCH2O) * c(sOH) 
    w(r33f) = k(r33f) * c(sCH2O) * c(sH) 
    w(r34f) = k(r34f) * c(sCH2O) * cqss(sqssO) 
    w(r35f) = k(r35f) * c(sCH2O) * c(sCH3) 
    w(r36f) = k(r36f) * c(sCH2O) * c(sHO2) 
    w(r37f) = k(r37f) * c(sCH3O) 
    w(r38f) = k(r38f) * c(sCH3O) * c(sO2) 
    w(r39f) = k(r39f) * c(sCH3) * c(sCH3O) 
    w(r40f) = k(r40f) * c(sCH3O) * c(sH) 
    w(r41f) = k(r41f) * c(sCH2O) * c(sH) 
    w(r42f) = k(r42f) * cqss(sqssCH2OH) * c(sO2) 
    w(r43f) = k(r43f) * cqss(sqssCH2OH) * c(sOH) 
    w(r44f) = k(r44f) * cqss(sqssCH3OH) 
    w(r45f) = k(r45f) * cqss(sqssCH3OH) 
    w(r46f) = k(r46f) * cqss(sqssCH3OH) * c(sH) 
    w(r47f) = k(r47f) * cqss(sqssCH3OH) * c(sOH) 
    w(r48f) = k(r48f) * cqss(sqssCH3OH) * c(sOH) 
    w(r49f) = k(r49f) * c(sCH3O)**2.0_pr 
    w(r50f) = k(r50f) * c(sCH3) * c(sH) 
    w(r51f) = k(r51f) * c(sCH4) * c(sH) 
    w(r52f) = k(r52f) * c(sCH4) * c(sOH) 
    w(r53f) = k(r53f) * c(sCH4) * cqss(sqssO) 
    w(r54f) = k(r54f) * c(sCH4) * c(sHO2) 
    w(r55f) = k(r55f) * c(sCH3) * c(sOH) 
    w(r56f) = k(r56f) * c(sCH3) * c(sOH) 
    w(r57f) = k(r57f) * c(sCH3) * c(sOH) 
    w(r58f) = k(r58f) * c(sCH3) * c(sHO2) 
    w(r59f) = k(r59f) * c(sCH3) * c(sHO2) 
    w(r60f) = k(r60f) * c(sCH3) * cqss(sqssO) 
    w(r61f) = k(r61f) * c(sCH3) * c(sO2) 
    w(r62f) = k(r62f) * c(sCH3) * c(sO2) 
    w(r63f) = k(r63f) * c(sCH3) * c(sO2) 
    w(r64f) = k(r64f) * c(sCH2O) * c(sCH3O2) 
    w(r65f) = k(r65f) * c(sCH3O2) * c(sCH4) 
    w(r66f) = k(r66f) * c(sCH3) * c(sCH3O2) 
    w(r67f) = k(r67f) * c(sCH3O2) * c(sHO2) 
    w(r68f) = k(r68f) * c(sCH3O2)**2.0_pr 
    w(r69f) = k(r69f) * c(sCH3O2)**2.0_pr 
    w(r70f) = k(r70f) * c(sCH3O2) * c(sH) 
    w(r71f) = k(r71f) * c(sCH3O2) * cqss(sqssO) 
    w(r72f) = k(r72f) * c(sCH3O2) * c(sOH) 
    w(r73f) = k(r73f) * c(sCH3O2H) 
    w(r74f) = k(r74f) * cqss(sqssCH2GSG) * c(sN2) 
    w(r75f) = k(r75f) * cqss(sqssCH2GSG) * c(sOH) 
    w(r76f) = k(r76f) * cqss(sqssCH2GSG) * c(sH2) 
    w(r77f) = k(r77f) * cqss(sqssCH2GSG) * c(sO2) 
    w(r78f) = k(r78f) * cqss(sqssCH2GSG) * c(sO2) 
    w(r79f) = k(r79f) * cqss(sqssCH2GSG) * c(sH2O) 
    w(r80f) = k(r80f) * cqss(sqssCH2GSG) * c(sCO2) 
    w(r81f) = k(r81f) * cqss(sqssCH2) * c(sH) 
    w(r82f) = k(r82f) * cqss(sqssCH2) * c(sO2) 
    w(r83f) = k(r83f) * cqss(sqssCH2) * c(sO2) 
    w(r84f) = k(r84f) * cqss(sqssC) * c(sO2) 
    w(r85f) = k(r85f) * c(sCH3)**2.0_pr 
    w(r86f) = k(r86f) * cqss(sqssC2H5) * c(sH) 
    w(r87f) = k(r87f) * c(sC2H6) * c(sH) 
    w(r88f) = k(r88f) * c(sC2H6) * cqss(sqssO) 
    w(r89f) = k(r89f) * c(sC2H6) * c(sOH) 
    w(r90f) = k(r90f) * c(sC2H6) * c(sCH3) 
    w(r91f) = k(r91f) * c(sC2H6) * c(sHO2) 
    w(r92f) = k(r92f) * c(sC2H4) * c(sH) 
    w(r93f) = k(r93f) * c(sCH3O2) * c(sH2) 
    w(r94f) = k(r94f) * cqss(sqssC2H5) * c(sCH3) 
    w(r95f) = k(r95f) * c(sCH3)**2.0_pr 
    w(r96f) = k(r96f) * cqss(sqssC2H5) * c(sO2) 
    w(r97f) = k(r97f) * cqss(sqssCH2CHO) 
    w(r98f) = k(r98f) * cqss(sqssCH2CHO) 
    w(r99f) = k(r99f) * cqss(sqssCH2CHO) * c(sO2) 
    w(r100f) = k(r100f) * cqss(sqssCH2CO) * c(sH) 
    w(r101f) = k(r101f) * cqss(sqssCH2CO) * c(sH) 
    w(r102f) = k(r102f) * cqss(sqssCH2CO) * c(sOH) 
    w(r103f) = k(r103f) * cqss(sqssHCCO) * c(sOH) 
    w(r104f) = k(r104f) * c(sH) * cqss(sqssHCCO) 
    w(r105f) = k(r105f) * cqss(sqssHCCO) * c(sO2) 
    w(r106f) = k(r106f) * cqss(sqssHCCO) * c(sO2) 
    w(r107f) = k(r107f) * c(sC2H4) * c(sH) 
    w(r108f) = k(r108f) * c(sC2H4) * cqss(sqssO) 
    w(r109f) = k(r109f) * c(sC2H4) * cqss(sqssO) 
    w(r110f) = k(r110f) * c(sC2H4) * c(sOH) 
    w(r111f) = k(r111f) * c(sC2H4) * c(sCH3) 
    w(r112f) = k(r112f) * cqss(sqssC2H2) * c(sH) 
    w(r113f) = k(r113f) * cqss(sqssC2H3) * c(sO2) 
    w(r114f) = k(r114f) * cqss(sqssC2H3) * c(sO2) 
    w(r115f) = k(r115f) * cqss(sqssC2H3) * c(sH) 
    w(r116f) = k(r116f) * cqss(sqssC2H3) * c(sOH) 
    w(r117f) = k(r117f) * cqss(sqssC2H2) * c(sOH) 
    w(r1b) = k(r1b) * cqss(sqssO) * c(sOH) 
    w(r2b) = k(r2b) * c(sH) * c(sOH) 
    w(r3b) = k(r3b) * c(sH) * c(sH2O) 
    w(r4b) = k(r4b) * c(sOH)**2.0_pr 
    w(r5b) = k(r5b) * c(sH)**2.0_pr * m(mM5)
    w(r6b) = k(r6b) * c(sOH) * m(mM6)
    w(r7b) = k(r7b) * c(sH2O) * m(mM7)
    w(r8b) = k(r8b) * c(sHO2) 
    w(r9b) = k(r9b) * c(sOH)**2.0_pr 
    w(r10b) = k(r10b) * c(sH) * c(sHO2) 
    w(r11b) = k(r11b) * c(sO2) * c(sOH) 
    w(r12b) = k(r12b) * c(sH2O) * c(sO2) 
    w(r13b) = k(r13b) * c(sH2O2) * c(sO2) 
    w(r14b) = k(r14b) * c(sH2O2) * c(sO2) 
    w(r15b) = k(r15b) * c(sOH)**2.0_pr 
    w(r16b) = k(r16b) * c(sOH)**2.0_pr 
    w(r17b) = k(r17b) * c(sH2O) * c(sOH) 
    w(r18b) = k(r18b) * c(sH2) * c(sHO2) 
    w(r19b) = k(r19b) * c(sHO2) * c(sOH) 
    w(r20b) = k(r20b) * c(sH2O) * c(sHO2) 
    w(r21b) = k(r21b) * c(sCO2) 
    w(r22b) = k(r22b) * c(sCO2) * c(sH) 
    w(r23b) = k(r23b) * c(sCO2) * c(sH) 
    w(r24b) = k(r24b) * c(sCO2) * c(sOH) 
    w(r25b) = k(r25b) * c(sCO) * c(sH) * m(mM25)
    w(r26b) = k(r26b) * c(sCO) * c(sHO2) 
    w(r27b) = k(r27b) * c(sCO) * c(sH2) 
    w(r28b) = k(r28b) * c(sCO) * c(sH2O) 
    w(r29b) = k(r29b) * c(sCH4) * c(sCO) 
    w(r30b) = k(r30b) * cqss(sqssHCO) * c(sHO2) 
    w(r31b) = k(r31b) * cqss(sqssOCHO) 
    w(r32b) = k(r32b) * c(sH2O) * cqss(sqssHCO) 
    w(r33b) = k(r33b) * c(sH2) * cqss(sqssHCO) 
    w(r34b) = k(r34b) * cqss(sqssHCO) * c(sOH) 
    w(r35b) = k(r35b) * c(sCH4) * cqss(sqssHCO) 
    w(r36b) = k(r36b) * c(sH2O2) * cqss(sqssHCO) 
    w(r37b) = k(r37b) * c(sCH2O) * c(sH) 
    w(r38b) = k(r38b) * c(sCH2O) * c(sHO2) 
    w(r39b) = k(r39b) * c(sCH2O) * c(sCH4) 
    w(r40b) = k(r40b) * c(sCH2O) * c(sH2) 
    w(r41b) = k(r41b) * cqss(sqssCH2OH) 
    w(r42b) = k(r42b) * c(sCH2O) * c(sHO2) 
    w(r43b) = k(r43b) * c(sCH2O) * c(sH2O) 
    w(r44b) = k(r44b) * c(sCH3) * c(sOH) 
    w(r45b) = k(r45b) * cqss(sqssCH2GSG) * c(sH2O) 
    w(r46b) = k(r46b) * cqss(sqssCH2OH) * c(sH2) 
    w(r47b) = k(r47b) * cqss(sqssCH2OH) * c(sH2O) 
    w(r48b) = k(r48b) * c(sCH3O) * c(sH2O) 
    w(r49b) = k(r49b) * c(sCH2O) * cqss(sqssCH3OH) 
    w(r50b) = k(r50b) * c(sCH4) 
    w(r51b) = k(r51b) * c(sCH3) * c(sH2) 
    w(r52b) = k(r52b) * c(sCH3) * c(sH2O) 
    w(r53b) = k(r53b) * c(sCH3) * c(sOH) 
    w(r54b) = k(r54b) * c(sCH3) * c(sH2O2) 
    w(r55b) = k(r55b) * cqss(sqssCH2GSG) * c(sH2O) 
    w(r56b) = k(r56b) * cqss(sqssCH2OH) * c(sH) 
    w(r57b) = k(r57b) * c(sCH3O) * c(sH) 
    w(r58b) = k(r58b) * c(sCH3O) * c(sOH) 
    w(r59b) = k(r59b) * c(sCH4) * c(sO2) 
    w(r60b) = k(r60b) * c(sCH2O) * c(sH) 
    w(r61b) = k(r61b) * c(sCH3O) * cqss(sqssO) 
    w(r62b) = k(r62b) * c(sCH2O) * c(sOH) 
    w(r63b) = k(r63b) * c(sCH3O2) 
    w(r64b) = k(r64b) * c(sCH3O2H) * cqss(sqssHCO) 
    w(r65b) = k(r65b) * c(sCH3) * c(sCH3O2H) 
    w(r66b) = k(r66b) * c(sCH3O)**2.0_pr 
    w(r67b) = k(r67b) * c(sCH3O2H) * c(sO2) 
    w(r70b) = k(r70b) * c(sCH3O) * c(sOH) 
    w(r71b) = k(r71b) * c(sCH3O) * c(sO2) 
    w(r72b) = k(r72b) * cqss(sqssCH3OH) * c(sO2) 
    w(r73b) = k(r73b) * c(sCH3O) * c(sOH) 
    w(r74b) = k(r74b) * cqss(sqssCH2) * c(sN2) 
    w(r75b) = k(r75b) * c(sCH2O) * c(sH) 
    w(r76b) = k(r76b) * c(sCH3) * c(sH) 
    w(r78b) = k(r78b) * c(sCO) * c(sH2O) 
    w(r79b) = k(r79b) * cqss(sqssCH2) * c(sH2O) 
    w(r80b) = k(r80b) * c(sCH2O) * c(sCO) 
    w(r81b) = k(r81b) * c(sCH3) 
    w(r82b) = k(r82b) * cqss(sqssHCO) * c(sOH) 
    w(r84b) = k(r84b) * c(sCO) * cqss(sqssO) 
    w(r85b) = k(r85b) * c(sC2H6) 
    w(r86b) = k(r86b) * c(sC2H6) 
    w(r87b) = k(r87b) * cqss(sqssC2H5) * c(sH2) 
    w(r88b) = k(r88b) * cqss(sqssC2H5) * c(sOH) 
    w(r89b) = k(r89b) * cqss(sqssC2H5) * c(sH2O) 
    w(r90b) = k(r90b) * cqss(sqssC2H5) * c(sCH4) 
    w(r91b) = k(r91b) * cqss(sqssC2H5) * c(sH2O2) 
    w(r92b) = k(r92b) * cqss(sqssC2H5) 
    w(r93b) = k(r93b) * c(sCH3O2H) * c(sH) 
    w(r94b) = k(r94b) * c(sC2H4) * c(sCH4) 
    w(r95b) = k(r95b) * cqss(sqssC2H5) * c(sH) 
    w(r96b) = k(r96b) * c(sC2H4) * c(sHO2) 
    w(r97b) = k(r97b) * cqss(sqssCH2CO) * c(sH) 
    w(r98b) = k(r98b) * c(sCH3) * c(sCO) 
    w(r100b) = k(r100b) * c(sH2) * cqss(sqssHCCO) 
    w(r101b) = k(r101b) * c(sCH3) * c(sCO) 
    w(r102b) = k(r102b) * c(sH2O) * cqss(sqssHCCO) 
    w(r104b) = k(r104b) * cqss(sqssCH2GSG) * c(sCO) 
    w(r107b) = k(r107b) * cqss(sqssC2H3) * c(sH2) 
    w(r108b) = k(r108b) * c(sCH3) * cqss(sqssHCO) 
    w(r109b) = k(r109b) * cqss(sqssCH2CHO) * c(sH) 
    w(r110b) = k(r110b) * cqss(sqssC2H3) * c(sH2O) 
    w(r111b) = k(r111b) * cqss(sqssC2H3) * c(sCH4) 
    w(r112b) = k(r112b) * cqss(sqssC2H3) 
    w(r113b) = k(r113b) * c(sCH2O) * cqss(sqssHCO) 
    w(r115b) = k(r115b) * cqss(sqssC2H2) * c(sH2) 
    w(r116b) = k(r116b) * cqss(sqssC2H2) * c(sH2O) 
    w(r117b) = k(r117b) * cqss(sqssCH2CO) * c(sH) 
  
    return
  end subroutine get_reaction_rates
  
  ! ----------------------------------------------- !
  ! Evaluate production rates                       !
  ! ----------------------------------------------- !
  subroutine get_production_rates(cdot,w)
    implicit none

    real(pr), dimension(nspec) :: cdot
    real(pr), dimension(nreac + nreac_reverse) :: w

    cdot(sH) = 0.0_pr &
         - w(r1f) &
         + w(r1b) &
         + w(r2f) &
         - w(r2b) &
         + w(r3f) &
         - w(r3b) &
         + 2.0_pr * w(r5f) &
         - 2.0_pr * w(r5b) &
         - w(r6f) &
         + w(r6b) &
         - w(r7f) &
         + w(r7b) &
         - w(r8f) &
         + w(r8b) &
         - w(r9f) &
         + w(r9b) &
         + w(r10f) &
         - w(r10b) &
         - w(r17f) &
         + w(r17b) &
         - w(r18f) &
         + w(r18b) &
         + w(r22f) &
         - w(r22b) &
         + w(r23f) &
         - w(r23b) &
         + w(r25f) &
         - w(r25b) &
         - w(r27f) &
         + w(r27b) &
         - w(r31f) &
         + w(r31b) &
         - w(r33f) &
         + w(r33b) &
         + w(r37f) &
         - w(r37b) &
         - w(r40f) &
         + w(r40b) &
         - w(r41f) &
         + w(r41b) &
         - w(r46f) &
         + w(r46b) &
         - w(r50f) &
         + w(r50b) &
         - w(r51f) &
         + w(r51b) &
         + w(r56f) &
         - w(r56b) &
         + w(r57f) &
         - w(r57b) &
         + w(r60f) &
         - w(r60b) &
         - w(r70f) &
         + w(r70b) &
         + w(r75f) &
         - w(r75b) &
         + w(r76f) &
         - w(r76b) &
         + w(r77f) &
         - w(r81f) &
         + w(r81b) &
         + 2.0_pr * w(r83f) &
         - w(r86f) &
         + w(r86b) &
         - w(r87f) &
         + w(r87b) &
         - w(r92f) &
         + w(r92b) &
         + w(r93f) &
         - w(r93b) &
         + w(r95f) &
         - w(r95b) &
         + w(r97f) &
         - w(r97b) &
         - w(r100f) &
         + w(r100b) &
         - w(r101f) &
         + w(r101b) &
         - w(r104f) &
         + w(r104b) &
         + w(r106f) &
         - w(r107f) &
         + w(r107b) &
         + w(r109f) &
         - w(r109b) &
         - w(r112f) &
         + w(r112b) &
         + w(r114f) &
         - w(r115f) &
         + w(r115b) &
         + w(r117f) &
         - w(r117b) 

    cdot(sH2) = 0.0_pr &
         - w(r2f) &
         + w(r2b) &
         - w(r3f) &
         + w(r3b) &
         - w(r5f) &
         + w(r5b) &
         - w(r10f) &
         + w(r10b) &
         + w(r18f) &
         - w(r18b) &
         + w(r27f) &
         - w(r27b) &
         + w(r33f) &
         - w(r33b) &
         + w(r40f) &
         - w(r40b) &
         + w(r46f) &
         - w(r46b) &
         + w(r51f) &
         - w(r51b) &
         - w(r76f) &
         + w(r76b) &
         + w(r87f) &
         - w(r87b) &
         - w(r93f) &
         + w(r93b) &
         + w(r100f) &
         - w(r100b) &
         + w(r103f) &
         + w(r107f) &
         - w(r107b) &
         + w(r115f) &
         - w(r115b) 

    cdot(sO2) = 0.0_pr &
         - w(r1f) &
         + w(r1b) &
         - w(r8f) &
         + w(r8b) &
         - w(r10f) &
         + w(r10b) &
         + w(r11f) &
         - w(r11b) &
         + w(r12f) &
         - w(r12b) &
         + w(r13f) &
         - w(r13b) &
         + w(r14f) &
         - w(r14b) &
         - w(r26f) &
         + w(r26b) &
         - w(r30f) &
         + w(r30b) &
         - w(r38f) &
         + w(r38b) &
         - w(r42f) &
         + w(r42b) &
         + w(r59f) &
         - w(r59b) &
         - w(r61f) &
         + w(r61b) &
         - w(r62f) &
         + w(r62b) &
         - w(r63f) &
         + w(r63b) &
         + w(r67f) &
         - w(r67b) &
         + w(r68f) &
         + w(r69f) &
         + w(r71f) &
         - w(r71b) &
         + w(r72f) &
         - w(r72b) &
         - w(r77f) &
         - w(r78f) &
         + w(r78b) &
         - w(r82f) &
         + w(r82b) &
         - w(r83f) &
         - w(r84f) &
         + w(r84b) &
         - w(r96f) &
         + w(r96b) &
         - w(r99f) &
         - w(r105f) &
         - w(r106f) &
         - w(r113f) &
         + w(r113b) &
         - w(r114f) 

    cdot(sOH) = 0.0_pr &
         + w(r1f) &
         - w(r1b) &
         + w(r2f) &
         - w(r2b) &
         - w(r3f) &
         + w(r3b) &
         + 2.0_pr * w(r4f) &
         - 2.0_pr * w(r4b) &
         + w(r6f) &
         - w(r6b) &
         - w(r7f) &
         + w(r7b) &
         + 2.0_pr * w(r9f) &
         - 2.0_pr * w(r9b) &
         + w(r11f) &
         - w(r11b) &
         - w(r12f) &
         + w(r12b) &
         + 2.0_pr * w(r15f) &
         - 2.0_pr * w(r15b) &
         + 2.0_pr * w(r16f) &
         - 2.0_pr * w(r16b) &
         + w(r17f) &
         - w(r17b) &
         + w(r19f) &
         - w(r19b) &
         - w(r20f) &
         + w(r20b) &
         - w(r22f) &
         + w(r22b) &
         - w(r23f) &
         + w(r23b) &
         + w(r24f) &
         - w(r24b) &
         - w(r28f) &
         + w(r28b) &
         - w(r32f) &
         + w(r32b) &
         + w(r34f) &
         - w(r34b) &
         - w(r43f) &
         + w(r43b) &
         + w(r44f) &
         - w(r44b) &
         - w(r47f) &
         + w(r47b) &
         - w(r48f) &
         + w(r48b) &
         - w(r52f) &
         + w(r52b) &
         + w(r53f) &
         - w(r53b) &
         - w(r55f) &
         + w(r55b) &
         - w(r56f) &
         + w(r56b) &
         - w(r57f) &
         + w(r57b) &
         + w(r58f) &
         - w(r58b) &
         + w(r62f) &
         - w(r62b) &
         + w(r70f) &
         - w(r70b) &
         - w(r72f) &
         + w(r72b) &
         + w(r73f) &
         - w(r73b) &
         - w(r75f) &
         + w(r75b) &
         + w(r77f) &
         + w(r82f) &
         - w(r82b) &
         + w(r88f) &
         - w(r88b) &
         - w(r89f) &
         + w(r89b) &
         + w(r99f) &
         - w(r102f) &
         + w(r102b) &
         - w(r103f) &
         + w(r105f) &
         - w(r110f) &
         + w(r110b) &
         - w(r116f) &
         + w(r116b) &
         - w(r117f) &
         + w(r117b) 

    cdot(sH2O) = 0.0_pr &
         + w(r3f) &
         - w(r3b) &
         - w(r4f) &
         + w(r4b) &
         + w(r7f) &
         - w(r7b) &
         + w(r12f) &
         - w(r12b) &
         + w(r17f) &
         - w(r17b) &
         + w(r20f) &
         - w(r20b) &
         + w(r28f) &
         - w(r28b) &
         + w(r32f) &
         - w(r32b) &
         + w(r43f) &
         - w(r43b) &
         + w(r45f) &
         - w(r45b) &
         + w(r47f) &
         - w(r47b) &
         + w(r48f) &
         - w(r48b) &
         + w(r52f) &
         - w(r52b) &
         + w(r55f) &
         - w(r55b) &
         + w(r78f) &
         - w(r78b) &
         + w(r89f) &
         - w(r89b) &
         + w(r102f) &
         - w(r102b) &
         + w(r110f) &
         - w(r110b) &
         + w(r116f) &
         - w(r116b) 

    cdot(sN2) = 0.0_pr 

    cdot(sHO2) = 0.0_pr &
         + w(r8f) &
         - w(r8b) &
         - w(r9f) &
         + w(r9b) &
         + w(r10f) &
         - w(r10b) &
         - w(r11f) &
         + w(r11b) &
         - w(r12f) &
         + w(r12b) &
         -2.0_pr * w(r13f) &
         + 2.0_pr * w(r13b) &
         -2.0_pr * w(r14f) &
         + 2.0_pr * w(r14b) &
         + w(r18f) &
         - w(r18b) &
         + w(r19f) &
         - w(r19b) &
         + w(r20f) &
         - w(r20b) &
         - w(r24f) &
         + w(r24b) &
         + w(r26f) &
         - w(r26b) &
         + w(r30f) &
         - w(r30b) &
         - w(r36f) &
         + w(r36b) &
         + w(r38f) &
         - w(r38b) &
         + w(r42f) &
         - w(r42b) &
         - w(r54f) &
         + w(r54b) &
         - w(r58f) &
         + w(r58b) &
         - w(r59f) &
         + w(r59b) &
         - w(r67f) &
         + w(r67b) &
         - w(r91f) &
         + w(r91b) &
         + w(r96f) &
         - w(r96b) 

    cdot(sH2O2) = 0.0_pr &
         + w(r13f) &
         - w(r13b) &
         + w(r14f) &
         - w(r14b) &
         - w(r15f) &
         + w(r15b) &
         - w(r16f) &
         + w(r16b) &
         - w(r17f) &
         + w(r17b) &
         - w(r18f) &
         + w(r18b) &
         - w(r19f) &
         + w(r19b) &
         - w(r20f) &
         + w(r20b) &
         + w(r36f) &
         - w(r36b) &
         + w(r54f) &
         - w(r54b) &
         + w(r91f) &
         - w(r91b) 

    cdot(sCO) = 0.0_pr &
         - w(r21f) &
         + w(r21b) &
         - w(r22f) &
         + w(r22b) &
         - w(r23f) &
         + w(r23b) &
         - w(r24f) &
         + w(r24b) &
         + w(r25f) &
         - w(r25b) &
         + w(r26f) &
         - w(r26b) &
         + w(r27f) &
         - w(r27b) &
         + w(r28f) &
         - w(r28b) &
         + w(r29f) &
         - w(r29b) &
         + w(r77f) &
         + w(r78f) &
         - w(r78b) &
         + w(r80f) &
         - w(r80b) &
         + w(r84f) &
         - w(r84b) &
         + w(r98f) &
         - w(r98b) &
         + w(r99f) &
         + w(r101f) &
         - w(r101b) &
         + 2.0_pr * w(r103f) &
         + w(r104f) &
         - w(r104b) &
         + 2.0_pr * w(r105f) &
         + w(r106f) &
         + w(r114f) 

    cdot(sCO2) = 0.0_pr &
         + w(r21f) &
         - w(r21b) &
         + w(r22f) &
         - w(r22b) &
         + w(r23f) &
         - w(r23b) &
         + w(r24f) &
         - w(r24b) &
         - w(r31f) &
         + w(r31b) &
         - w(r80f) &
         + w(r80b) &
         + w(r83f) &
         + w(r106f) 

    cdot(sCH2O) = 0.0_pr &
         - w(r30f) &
         + w(r30b) &
         - w(r32f) &
         + w(r32b) &
         - w(r33f) &
         + w(r33b) &
         - w(r34f) &
         + w(r34b) &
         - w(r35f) &
         + w(r35b) &
         - w(r36f) &
         + w(r36b) &
         + w(r37f) &
         - w(r37b) &
         + w(r38f) &
         - w(r38b) &
         + w(r39f) &
         - w(r39b) &
         + w(r40f) &
         - w(r40b) &
         - w(r41f) &
         + w(r41b) &
         + w(r42f) &
         - w(r42b) &
         + w(r43f) &
         - w(r43b) &
         + w(r49f) &
         - w(r49b) &
         + w(r60f) &
         - w(r60b) &
         + w(r62f) &
         - w(r62b) &
         - w(r64f) &
         + w(r64b) &
         + w(r68f) &
         + w(r75f) &
         - w(r75b) &
         + w(r80f) &
         - w(r80b) &
         + w(r99f) &
         + w(r113f) &
         - w(r113b) &
         + w(r114f) 

    cdot(sCH3O) = 0.0_pr &
         - w(r37f) &
         + w(r37b) &
         - w(r38f) &
         + w(r38b) &
         - w(r39f) &
         + w(r39b) &
         - w(r40f) &
         + w(r40b) &
         + w(r48f) &
         - w(r48b) &
         -2.0_pr * w(r49f) &
         + 2.0_pr * w(r49b) &
         + w(r57f) &
         - w(r57b) &
         + w(r58f) &
         - w(r58b) &
         + w(r61f) &
         - w(r61b) &
         + 2.0_pr * w(r66f) &
         - 2.0_pr * w(r66b) &
         + 2.0_pr * w(r69f) &
         + w(r70f) &
         - w(r70b) &
         + w(r71f) &
         - w(r71b) &
         + w(r73f) &
         - w(r73b) 

    cdot(sCH3O2H) = 0.0_pr &
         + w(r64f) &
         - w(r64b) &
         + w(r65f) &
         - w(r65b) &
         + w(r67f) &
         - w(r67b) &
         - w(r73f) &
         + w(r73b) &
         + w(r93f) &
         - w(r93b) 

    cdot(sCH3O2) = 0.0_pr &
         + w(r63f) &
         - w(r63b) &
         - w(r64f) &
         + w(r64b) &
         - w(r65f) &
         + w(r65b) &
         - w(r66f) &
         + w(r66b) &
         - w(r67f) &
         + w(r67b) &
         -2.0_pr * w(r68f) &
         -2.0_pr * w(r69f) &
         - w(r70f) &
         + w(r70b) &
         - w(r71f) &
         + w(r71b) &
         - w(r72f) &
         + w(r72b) &
         - w(r93f) &
         + w(r93b) 

    cdot(sCH4) = 0.0_pr &
         + w(r29f) &
         - w(r29b) &
         + w(r35f) &
         - w(r35b) &
         + w(r39f) &
         - w(r39b) &
         + w(r50f) &
         - w(r50b) &
         - w(r51f) &
         + w(r51b) &
         - w(r52f) &
         + w(r52b) &
         - w(r53f) &
         + w(r53b) &
         - w(r54f) &
         + w(r54b) &
         + w(r59f) &
         - w(r59b) &
         - w(r65f) &
         + w(r65b) &
         + w(r90f) &
         - w(r90b) &
         + w(r94f) &
         - w(r94b) &
         + w(r111f) &
         - w(r111b) 

    cdot(sCH3) = 0.0_pr &
         - w(r29f) &
         + w(r29b) &
         - w(r35f) &
         + w(r35b) &
         - w(r39f) &
         + w(r39b) &
         + w(r44f) &
         - w(r44b) &
         - w(r50f) &
         + w(r50b) &
         + w(r51f) &
         - w(r51b) &
         + w(r52f) &
         - w(r52b) &
         + w(r53f) &
         - w(r53b) &
         + w(r54f) &
         - w(r54b) &
         - w(r55f) &
         + w(r55b) &
         - w(r56f) &
         + w(r56b) &
         - w(r57f) &
         + w(r57b) &
         - w(r58f) &
         + w(r58b) &
         - w(r59f) &
         + w(r59b) &
         - w(r60f) &
         + w(r60b) &
         - w(r61f) &
         + w(r61b) &
         - w(r62f) &
         + w(r62b) &
         - w(r63f) &
         + w(r63b) &
         + w(r65f) &
         - w(r65b) &
         - w(r66f) &
         + w(r66b) &
         + w(r76f) &
         - w(r76b) &
         + w(r81f) &
         - w(r81b) &
         -2.0_pr * w(r85f) &
         + 2.0_pr * w(r85b) &
         - w(r90f) &
         + w(r90b) &
         - w(r94f) &
         + w(r94b) &
         -2.0_pr * w(r95f) &
         + 2.0_pr * w(r95b) &
         + w(r98f) &
         - w(r98b) &
         + w(r101f) &
         - w(r101b) &
         + w(r108f) &
         - w(r108b) &
         - w(r111f) &
         + w(r111b) 

    cdot(sC2H6) = 0.0_pr &
         + w(r85f) &
         - w(r85b) &
         + w(r86f) &
         - w(r86b) &
         - w(r87f) &
         + w(r87b) &
         - w(r88f) &
         + w(r88b) &
         - w(r89f) &
         + w(r89b) &
         - w(r90f) &
         + w(r90b) &
         - w(r91f) &
         + w(r91b) 

    cdot(sC2H4) = 0.0_pr &
         - w(r92f) &
         + w(r92b) &
         + w(r94f) &
         - w(r94b) &
         + w(r96f) &
         - w(r96b) &
         - w(r107f) &
         + w(r107b) &
         - w(r108f) &
         + w(r108b) &
         - w(r109f) &
         + w(r109b) &
         - w(r110f) &
         + w(r110b) &
         - w(r111f) &
         + w(r111b) 

  
    return
  end subroutine get_production_rates


  ! ----------------------------------------------- !
  ! Evaluation of QSS concentrations                !
  ! ----------------------------------------------- !
  subroutine get_qss(cqss,c,k,M)
    implicit none

    real(pr), dimension(nqss) :: cqss
    real(pr), dimension(nspec) :: c
    real(pr), dimension(nreac + nreac_reverse) :: k
    real(pr), dimension(nTB + nFO) :: M

    integer :: index

    real(pr) :: O_ct
    real(pr) :: O_num
    real(pr) :: O_denom
    real(pr) :: O_HCO
    real(pr) :: O_C
    real(pr) :: O_C2H5
    real(pr) :: O_CH2CHO
    real(pr) :: HCO_ct
    real(pr) :: HCO_num
    real(pr) :: HCO_denom
    real(pr) :: HCO_O
    real(pr) :: HCO_CH2
    real(pr) :: HCO_C2H3
    real(pr) :: OCHO_ct
    real(pr) :: OCHO_num
    real(pr) :: OCHO_denom
    real(pr) :: CH3OH_ct
    real(pr) :: CH3OH_num
    real(pr) :: CH3OH_denom
    real(pr) :: CH3OH_CH2OH
    real(pr) :: CH3OH_CH2GSG
    real(pr) :: CH2OH_ct
    real(pr) :: CH2OH_num
    real(pr) :: CH2OH_denom
    real(pr) :: CH2OH_CH3OH
    real(pr) :: CH2_ct
    real(pr) :: CH2_num
    real(pr) :: CH2_denom
    real(pr) :: CH2_HCO
    real(pr) :: CH2_CH2GSG
    real(pr) :: CH2GSG_ct
    real(pr) :: CH2GSG_num
    real(pr) :: CH2GSG_denom
    real(pr) :: CH2GSG_CH3OH
    real(pr) :: CH2GSG_CH2
    real(pr) :: CH2GSG_HCCO
    real(pr) :: C_ct
    real(pr) :: C_num
    real(pr) :: C_denom
    real(pr) :: C_O
    real(pr) :: C2H5_ct
    real(pr) :: C2H5_num
    real(pr) :: C2H5_denom
    real(pr) :: C2H5_O
    real(pr) :: C2H3_ct
    real(pr) :: C2H3_num
    real(pr) :: C2H3_denom
    real(pr) :: C2H3_HCO
    real(pr) :: C2H3_C2H2
    real(pr) :: C2H2_ct
    real(pr) :: C2H2_num
    real(pr) :: C2H2_denom
    real(pr) :: C2H2_C2H3
    real(pr) :: C2H2_CH2CO
    real(pr) :: CH2CHO_ct
    real(pr) :: CH2CHO_num
    real(pr) :: CH2CHO_denom
    real(pr) :: CH2CHO_O
    real(pr) :: CH2CHO_CH2CO
    real(pr) :: CH2CO_ct
    real(pr) :: CH2CO_num
    real(pr) :: CH2CO_denom
    real(pr) :: CH2CO_C2H2
    real(pr) :: CH2CO_CH2CHO
    real(pr) :: CH2CO_HCCO
    real(pr) :: HCCO_ct
    real(pr) :: HCCO_num
    real(pr) :: HCCO_denom
    real(pr) :: HCCO_CH2GSG
    real(pr) :: HCCO_CH2CO
  
    real(pr) :: a_n_a
    real(pr) :: a_s_a
    real(pr) :: a_t_a
    real(pr) :: a_w_a
    real(pr) :: a_ba_a
    real(pr) :: a_ca_a
    real(pr) :: a_cf_a
    real(pr) :: a_cg_a
    real(pr) :: a_cj_a
    real(pr) :: a_cn_a
    real(pr) :: a_cs_a
    real(pr) :: a_ct_a
    real(pr) :: a_cw_a
    real(pr) :: a_da_a
    real(pr) :: a_ea_a
    real(pr) :: a_ef_a
    real(pr) :: a_eg_a
    real(pr) :: a_ej_a
    real(pr) :: a_ew_a
    real(pr) :: a_bd_b
    real(pr) :: a_bh_b
    real(pr) :: a_bq_b
    real(pr) :: a_cd_b
    real(pr) :: a_ch_b
    real(pr) :: a_cq_b
    real(pr) :: a_cu_b
    real(pr) :: a_dd_b
    real(pr) :: a_dh_b
    real(pr) :: a_du_b
    real(pr) :: a_ed_b
    real(pr) :: a_eh_b
    real(pr) :: a_ap_c
    real(pr) :: a_ar_c
    real(pr) :: a_be_c
    real(pr) :: a_bp_c
    real(pr) :: a_br_c
    real(pr) :: a_fe_c
    real(pr) :: a_br_e
    real(pr) :: a_ce_e
    real(pr) :: a_cr_e
    real(pr) :: a_de_e
    real(pr) :: a_ee_e
    real(pr) :: a_fe_e
    real(pr) :: a_cl_f
    real(pr) :: a_cy_f
    real(pr) :: a_dl_f
    real(pr) :: a_el_f
    real(pr) :: a_ey_f
    real(pr) :: a_fl_f
    real(pr) :: a_dv_i
    real(pr) :: a_ei_i
    real(pr) :: a_ev_i
    real(pr) :: a_ek_j
    real(pr) :: a_ex_j
    real(pr) :: a_fk_j
    real(pr) :: a_ex_k
    real(pr) :: a_fk_k
    real(pr) :: a_fl_l
    real(pr) :: A_A_A
    real(pr) :: A_B_A
    real(pr) :: A_C_A
    real(pr) :: A_D_A
    real(pr) :: A_E_A
    real(pr) :: A_F_A
    real(pr) :: A_G_A
    real(pr) :: A_H_A
    real(pr) :: A_I_A
    real(pr) :: A_J_A
    real(pr) :: A_K_A
    real(pr) :: A_L_A
    real(pr) :: A_B_B
    real(pr) :: A_C_B
    real(pr) :: A_D_B
    real(pr) :: A_E_B
    real(pr) :: A_F_B
    real(pr) :: A_G_B
    real(pr) :: A_H_B
    real(pr) :: A_I_B
    real(pr) :: A_J_B
    real(pr) :: A_K_B
    real(pr) :: A_L_B
    real(pr) :: A_C_C
    real(pr) :: A_D_C
    real(pr) :: A_E_C
    real(pr) :: A_F_C
    real(pr) :: A_G_C
    real(pr) :: A_H_C
    real(pr) :: A_I_C
    real(pr) :: A_J_C
    real(pr) :: A_K_C
    real(pr) :: A_L_C
    real(pr) :: A_D_D
    real(pr) :: A_E_D
    real(pr) :: A_F_D
    real(pr) :: A_G_D
    real(pr) :: A_H_D
    real(pr) :: A_I_D
    real(pr) :: A_J_D
    real(pr) :: A_K_D
    real(pr) :: A_L_D
    real(pr) :: A_E_E
    real(pr) :: A_F_E
    real(pr) :: A_G_E
    real(pr) :: A_H_E
    real(pr) :: A_I_E
    real(pr) :: A_J_E
    real(pr) :: A_K_E
    real(pr) :: A_L_E
    real(pr) :: A_F_F
    real(pr) :: A_G_F
    real(pr) :: A_H_F
    real(pr) :: A_I_F
    real(pr) :: A_J_F
    real(pr) :: A_K_F
    real(pr) :: A_L_F
    real(pr) :: A_G_G
    real(pr) :: A_H_G
    real(pr) :: A_I_G
    real(pr) :: A_J_G
    real(pr) :: A_K_G
    real(pr) :: A_L_G
    real(pr) :: A_H_H
    real(pr) :: A_I_H
    real(pr) :: A_J_H
    real(pr) :: A_K_H
    real(pr) :: A_L_H
    real(pr) :: A_I_I
    real(pr) :: A_J_I
    real(pr) :: A_K_I
    real(pr) :: A_L_I
    real(pr) :: A_J_J
    real(pr) :: A_K_J
    real(pr) :: A_L_J
    real(pr) :: A_K_K
    real(pr) :: A_L_K
    real(pr) :: A_L_L

    HCCO_denom = tiny(1.0_pr) + ( 0.0_pr &
             + k(r103f)* c(sOH) &
             + k(r104f)* c(sH) &
             + k(r105f)* c(sO2) &
             + k(r106f)* c(sO2) &
             + k(r100b)* c(sH2) &
             + k(r102b)* c(sH2O)   )

    HCCO_num = ( 0.0_pr   )

    HCCO_ct = HCCO_num / HCCO_denom

    HCCO_CH2GSG = - ( 0.0_pr &
          + k(r104b) * c(sCO)  ) / HCCO_denom

    HCCO_CH2CO = - ( 0.0_pr &
          + k(r100f) * c(sH) &
          + k(r102f) * c(sOH)  ) / HCCO_denom

    CH2CO_denom = tiny(1.0_pr) + ( 0.0_pr &
             + k(r100f)* c(sH) &
             + k(r101f)* c(sH) &
             + k(r102f)* c(sOH) &
             + k(r97b)* c(sH) &
             + k(r117b)* c(sH)   )

    CH2CO_num = ( 0.0_pr &
             + k(r101b)* c(sCH3) * c(sCO)   )

    CH2CO_ct = CH2CO_num / CH2CO_denom

    CH2CO_C2H2 = - ( 0.0_pr &
          + k(r117f) * c(sOH)  ) / CH2CO_denom

    CH2CO_CH2CHO = - ( 0.0_pr &
          + k(r97f)  ) / CH2CO_denom

    CH2CO_HCCO = - ( 0.0_pr &
          + k(r100b) * c(sH2) &
          + k(r102b) * c(sH2O)  ) / CH2CO_denom

    CH2CHO_denom = tiny(1.0_pr) + ( 0.0_pr &
             + k(r97f)&
             + k(r98f)&
             + k(r99f)* c(sO2) &
             + k(r109b)* c(sH)   )

    CH2CHO_num = ( 0.0_pr &
             + k(r98b)* c(sCH3) * c(sCO)   )

    CH2CHO_ct = CH2CHO_num / CH2CHO_denom

    CH2CHO_O = - ( 0.0_pr &
          + k(r109f) * c(sC2H4)  ) / CH2CHO_denom

    CH2CHO_CH2CO = - ( 0.0_pr &
          + k(r97b) * c(sH)  ) / CH2CHO_denom

    C2H2_denom = tiny(1.0_pr) + ( 0.0_pr &
             + k(r112f)* c(sH) &
             + k(r117f)* c(sOH) &
             + k(r115b)* c(sH2) &
             + k(r116b)* c(sH2O)   )

    C2H2_num = ( 0.0_pr   )

    C2H2_ct = C2H2_num / C2H2_denom

    C2H2_C2H3 = - ( 0.0_pr &
          + k(r115f) * c(sH) &
          + k(r116f) * c(sOH) &
          + k(r112b)  ) / C2H2_denom

    C2H2_CH2CO = - ( 0.0_pr &
          + k(r117b) * c(sH)  ) / C2H2_denom

    C2H3_denom = tiny(1.0_pr) + ( 0.0_pr &
             + k(r113f)* c(sO2) &
             + k(r114f)* c(sO2) &
             + k(r115f)* c(sH) &
             + k(r116f)* c(sOH) &
             + k(r107b)* c(sH2) &
             + k(r110b)* c(sH2O) &
             + k(r111b)* c(sCH4) &
             + k(r112b)  )

    C2H3_num = ( 0.0_pr &
             + k(r107f)* c(sC2H4) * c(sH) &
             + k(r110f)* c(sC2H4) * c(sOH) &
             + k(r111f)* c(sC2H4) * c(sCH3)   )

    C2H3_ct = C2H3_num / C2H3_denom

    C2H3_HCO = - ( 0.0_pr &
          + k(r113b) * c(sCH2O)  ) / C2H3_denom

    C2H3_C2H2 = - ( 0.0_pr &
          + k(r112f) * c(sH) &
          + k(r115b) * c(sH2) &
          + k(r116b) * c(sH2O)  ) / C2H3_denom

    C2H5_denom = tiny(1.0_pr) + ( 0.0_pr &
             + k(r86f)* c(sH) &
             + k(r94f)* c(sCH3) &
             + k(r96f)* c(sO2) &
             + k(r87b)* c(sH2) &
             + k(r88b)* c(sOH) &
             + k(r89b)* c(sH2O) &
             + k(r90b)* c(sCH4) &
             + k(r91b)* c(sH2O2) &
             + k(r92b)&
             + k(r95b)* c(sH)   )

    C2H5_num = ( 0.0_pr &
             + k(r87f)* c(sC2H6) * c(sH) &
             + k(r89f)* c(sC2H6) * c(sOH) &
             + k(r90f)* c(sC2H6) * c(sCH3) &
             + k(r91f)* c(sC2H6) * c(sHO2) &
             + k(r92f)* c(sC2H4) * c(sH) &
             + k(r95f) *c(sCH3)** 2.0_pr&
             + k(r86b)* c(sC2H6) &
             + k(r94b)* c(sC2H4) * c(sCH4) &
             + k(r96b)* c(sC2H4) * c(sHO2)   )

    C2H5_ct = C2H5_num / C2H5_denom

    C2H5_O = - ( 0.0_pr &
          + k(r88f) * c(sC2H6)  ) / C2H5_denom

    C_denom = tiny(1.0_pr) + ( 0.0_pr &
             + k(r84f)* c(sO2)   )

    C_num = ( 0.0_pr   )

    C_ct = C_num / C_denom

    C_O = - ( 0.0_pr &
          + k(r84b) * c(sCO)  ) / C_denom

    CH2GSG_denom = tiny(1.0_pr) + ( 0.0_pr &
             + k(r74f)* c(sN2) &
             + k(r75f)* c(sOH) &
             + k(r76f)* c(sH2) &
             + k(r77f)* c(sO2) &
             + k(r78f)* c(sO2) &
             + k(r79f)* c(sH2O) &
             + k(r80f)* c(sCO2) &
             + k(r45b)* c(sH2O) &
             + k(r55b)* c(sH2O) &
             + k(r104b)* c(sCO)   )

    CH2GSG_num = ( 0.0_pr &
             + k(r55f)* c(sCH3) * c(sOH) &
             + k(r75b)* c(sCH2O) * c(sH) &
             + k(r76b)* c(sCH3) * c(sH) &
             + k(r78b)* c(sCO) * c(sH2O) &
             + k(r80b)* c(sCH2O) * c(sCO)   )

    CH2GSG_ct = CH2GSG_num / CH2GSG_denom

    CH2GSG_CH3OH = - ( 0.0_pr &
          + k(r45f)  ) / CH2GSG_denom

    CH2GSG_CH2 = - ( 0.0_pr &
          + k(r74b) * c(sN2) &
          + k(r79b) * c(sH2O)  ) / CH2GSG_denom

    CH2GSG_HCCO = - ( 0.0_pr &
          + k(r104f) * c(sH)  ) / CH2GSG_denom

    CH2_denom = tiny(1.0_pr) + ( 0.0_pr &
             + k(r81f)* c(sH) &
             + k(r82f)* c(sO2) &
             + k(r83f)* c(sO2) &
             + k(r74b)* c(sN2) &
             + k(r79b)* c(sH2O)   )

    CH2_num = ( 0.0_pr &
             + k(r81b)* c(sCH3)   )

    CH2_ct = CH2_num / CH2_denom

    CH2_HCO = - ( 0.0_pr &
          + k(r82b) * c(sOH)  ) / CH2_denom

    CH2_CH2GSG = - ( 0.0_pr &
          + k(r74f) * c(sN2) &
          + k(r79f) * c(sH2O)  ) / CH2_denom

    CH2OH_denom = tiny(1.0_pr) + ( 0.0_pr &
             + k(r42f)* c(sO2) &
             + k(r43f)* c(sOH) &
             + k(r41b)&
             + k(r46b)* c(sH2) &
             + k(r47b)* c(sH2O) &
             + k(r56b)* c(sH)   )

    CH2OH_num = ( 0.0_pr &
             + k(r41f)* c(sCH2O) * c(sH) &
             + k(r56f)* c(sCH3) * c(sOH) &
             + k(r42b)* c(sCH2O) * c(sHO2) &
             + k(r43b)* c(sCH2O) * c(sH2O)   )

    CH2OH_ct = CH2OH_num / CH2OH_denom

    CH2OH_CH3OH = - ( 0.0_pr &
          + k(r46f) * c(sH) &
          + k(r47f) * c(sOH)  ) / CH2OH_denom

    CH3OH_denom = tiny(1.0_pr) + ( 0.0_pr &
             + k(r44f)&
             + k(r45f)&
             + k(r46f)* c(sH) &
             + k(r47f)* c(sOH) &
             + k(r48f)* c(sOH) &
             + k(r49b)* c(sCH2O) &
             + k(r72b)* c(sO2)   )

    CH3OH_num = ( 0.0_pr &
             + k(r49f) *c(sCH3O)** 2.0_pr&
             + k(r68f) *c(sCH3O2)** 2.0_pr&
             + k(r72f)* c(sCH3O2) * c(sOH) &
             + k(r44b)* c(sCH3) * c(sOH) &
             + k(r48b)* c(sCH3O) * c(sH2O)   )

    CH3OH_ct = CH3OH_num / CH3OH_denom

    CH3OH_CH2OH = - ( 0.0_pr &
          + k(r46b) * c(sH2) &
          + k(r47b) * c(sH2O)  ) / CH3OH_denom

    CH3OH_CH2GSG = - ( 0.0_pr &
          + k(r45b) * c(sH2O)  ) / CH3OH_denom

    HCO_denom = tiny(1.0_pr) + ( 0.0_pr &
             + k(r25f)* m(mM25) &
             + k(r26f)* c(sO2) &
             + k(r27f)* c(sH) &
             + k(r28f)* c(sOH) &
             + k(r29f)* c(sCH3) &
             + k(r30b)* c(sHO2) &
             + k(r32b)* c(sH2O) &
             + k(r33b)* c(sH2) &
             + k(r34b)* c(sOH) &
             + k(r35b)* c(sCH4) &
             + k(r36b)* c(sH2O2) &
             + k(r64b)* c(sCH3O2H) &
             + k(r82b)* c(sOH) &
             + k(r108b)* c(sCH3) &
             + k(r113b)* c(sCH2O)   )

    HCO_num = ( 0.0_pr &
             + k(r30f)* c(sCH2O) * c(sO2) &
             + k(r32f)* c(sCH2O) * c(sOH) &
             + k(r33f)* c(sCH2O) * c(sH) &
             + k(r35f)* c(sCH2O) * c(sCH3) &
             + k(r36f)* c(sCH2O) * c(sHO2) &
             + k(r64f)* c(sCH2O) * c(sCH3O2) &
             + k(r25b)* c(sCO) * c(sH) * m(mM25) &
             + k(r26b)* c(sCO) * c(sHO2) &
             + k(r27b)* c(sCO) * c(sH2) &
             + k(r28b)* c(sCO) * c(sH2O) &
             + k(r29b)* c(sCH4) * c(sCO)   )

    HCO_ct = HCO_num / HCO_denom

    HCO_O = - ( 0.0_pr &
          + k(r34f) * c(sCH2O) &
          + k(r108f) * c(sC2H4)  ) / HCO_denom

    HCO_CH2 = - ( 0.0_pr &
          + k(r82f) * c(sO2)  ) / HCO_denom

    HCO_C2H3 = - ( 0.0_pr &
          + k(r113f) * c(sO2)  ) / HCO_denom

    O_denom = tiny(1.0_pr) + ( 0.0_pr &
             + k(r2f)* c(sH2) &
             + k(r4f)* c(sH2O) &
             + k(r6f)* c(sH) * m(mM6) &
             + k(r11f)* c(sHO2) &
             + k(r19f)* c(sH2O2) &
             + k(r21f)* c(sCO) &
             + k(r34f)* c(sCH2O) &
             + k(r53f)* c(sCH4) &
             + k(r60f)* c(sCH3) &
             + k(r71f)* c(sCH3O2) &
             + k(r88f)* c(sC2H6) &
             + k(r108f)* c(sC2H4) &
             + k(r109f)* c(sC2H4) &
             + k(r1b)* c(sOH) &
             + k(r61b)* c(sCH3O) &
             + k(r84b)* c(sCO)   )

    O_num = ( 0.0_pr &
             + k(r1f)* c(sH) * c(sO2) &
             + k(r61f)* c(sCH3) * c(sO2) &
             + k(r2b)* c(sH) * c(sOH) &
             + k(r4b) *c(sOH)** 2.0_pr&
             + k(r6b)* c(sOH) * m(mM6) &
             + k(r11b)* c(sO2) * c(sOH) &
             + k(r19b)* c(sHO2) * c(sOH) &
             + k(r21b)* c(sCO2) &
             + k(r53b)* c(sCH3) * c(sOH) &
             + k(r60b)* c(sCH2O) * c(sH) &
             + k(r71b)* c(sCH3O) * c(sO2)   )

    O_ct = O_num / O_denom

    O_HCO = - ( 0.0_pr &
          + k(r34b) * c(sOH) &
          + k(r108b) * c(sCH3)  ) / O_denom

    O_C = - ( 0.0_pr &
          + k(r84f) * c(sO2)  ) / O_denom

    O_C2H5 = - ( 0.0_pr &
          + k(r88b) * c(sOH)  ) / O_denom

    O_CH2CHO = - ( 0.0_pr &
          + k(r109b) * c(sH)  ) / O_denom

    a_n_a =  (1.0_pr) - (O_HCO) * (HCO_O)
    a_s_a =  - (O_C) * (HCO_O)
    a_t_a =  - (O_C2H5) * (HCO_O)
    a_w_a =  - (O_CH2CHO) * (HCO_O)
    a_ba_a = CH2_HCO
    a_ca_a =  - (O_HCO) * (C_O)
    a_cf_a =  (1.0_pr) - (O_C) * (C_O)
    a_cg_a =  - (O_C2H5) * (C_O)
    a_cj_a =  - (O_CH2CHO) * (C_O)
    a_cn_a =  - (O_HCO) * (C2H5_O)
    a_cs_a =  - (O_C) * (C2H5_O)
    a_ct_a =  (1.0_pr) - (O_C2H5) * (C2H5_O)
    a_cw_a =  - (O_CH2CHO) * (C2H5_O)
    a_da_a = C2H3_HCO
    a_ea_a =  - (O_HCO) * (CH2CHO_O)
    a_ef_a =  - (O_C) * (CH2CHO_O)
    a_eg_a =  - (O_C2H5) * (CH2CHO_O)
    a_ej_a =  (1.0_pr) - (O_CH2CHO) * (CH2CHO_O)
    a_ew_a = CH2CO_CH2CHO
    a_bd_b =  (1.0_pr) - (HCO_CH2) * (a_ba_a) / (a_n_a)
    a_bh_b =  - (HCO_C2H3) * (a_ba_a) / (a_n_a)
    a_bq_b = CH2GSG_CH2
    a_cd_b =  - (HCO_CH2) * (a_ca_a) / (a_n_a)
    a_ch_b =  - (HCO_C2H3) * (a_ca_a) / (a_n_a)
    a_cq_b =  - (HCO_CH2) * (a_cn_a) / (a_n_a)
    a_cu_b =  - (HCO_C2H3) * (a_cn_a) / (a_n_a)
    a_dd_b =  - (HCO_CH2) * (a_da_a) / (a_n_a)
    a_dh_b =  (1.0_pr) - (HCO_C2H3) * (a_da_a) / (a_n_a)
    a_du_b = C2H2_C2H3
    a_ed_b =  - (HCO_CH2) * (a_ea_a) / (a_n_a)
    a_eh_b =  - (HCO_C2H3) * (a_ea_a) / (a_n_a)
    a_ap_c =  (1.0_pr) - (CH3OH_CH2OH) * (CH2OH_CH3OH)
    a_ar_c =  - (CH3OH_CH2GSG) * (CH2OH_CH3OH)
    a_be_c = CH2_CH2GSG
    a_bp_c =  - (CH3OH_CH2OH) * (CH2GSG_CH3OH)
    a_br_c =  (1.0_pr) - (CH3OH_CH2GSG) * (CH2GSG_CH3OH)
    a_fe_c = HCCO_CH2GSG
    a_br_e =  (a_br_c) - (a_be_c) * (a_bq_b) / (a_bd_b)
    a_ce_e =  - (a_be_c) * (a_cd_b) / (a_bd_b)
    a_cr_e =  - (a_be_c) * (a_cq_b) / (a_bd_b)
    a_de_e =  - (a_be_c) * (a_dd_b) / (a_bd_b)
    a_ee_e =  - (a_be_c) * (a_ed_b) / (a_bd_b)
    a_fe_e = a_fe_c
    a_cl_f =  - (CH2GSG_HCCO) * (a_ce_e) / (a_br_e)
    a_cy_f =  - (CH2GSG_HCCO) * (a_cr_e) / (a_br_e)
    a_dl_f =  - (CH2GSG_HCCO) * (a_de_e) / (a_br_e)
    a_el_f =  - (CH2GSG_HCCO) * (a_ee_e) / (a_br_e)
    a_ey_f = CH2CO_HCCO
    a_fl_f =  (1.0_pr) - (CH2GSG_HCCO) * (a_fe_e) / (a_br_e)
    a_dv_i =  (1.0_pr) - (C2H3_C2H2) * (a_du_b) / (a_dh_b)
    a_ei_i =  - (C2H3_C2H2) * (a_eh_b) / (a_dh_b)
    a_ev_i = CH2CO_C2H2
    a_ek_j =  (CH2CHO_CH2CO) - (C2H2_CH2CO) * (a_ei_i) / (a_dv_i)
    a_ex_j =  (1.0_pr) - (C2H2_CH2CO) * (a_ev_i) / (a_dv_i)
    a_fk_j = HCCO_CH2CO
    a_ex_k =  (a_ex_j) - (a_ek_j) * (a_ew_a) / (a_ej_a)
    a_fk_k = a_fk_j
    a_fl_l =  (a_fl_f) - (a_ey_f) * (a_fk_k) / (a_ex_k)
    A_A_A =  (HCO_ct) - (O_ct) * (HCO_O)
    A_B_A = CH3OH_ct
    A_C_A = CH2OH_ct
    A_D_A = CH2_ct
    A_E_A = CH2GSG_ct
    A_F_A =  (C_ct) - (O_ct) * (C_O)
    A_G_A =  (C2H5_ct) - (O_ct) * (C2H5_O)
    A_H_A = C2H3_ct
    A_I_A = C2H2_ct
    A_J_A =  (CH2CHO_ct) - (O_ct) * (CH2CHO_O)
    A_K_A = CH2CO_ct
    A_L_A = HCCO_ct
    A_B_B = A_B_A
    A_C_B = A_C_A
    A_D_B =  (A_D_A) - (A_A_A) * (a_ba_a) / (a_n_a)
    A_E_B = A_E_A
    A_F_B =  (A_F_A) - (A_A_A) * (a_ca_a) / (a_n_a)
    A_G_B =  (A_G_A) - (A_A_A) * (a_cn_a) / (a_n_a)
    A_H_B =  (A_H_A) - (A_A_A) * (a_da_a) / (a_n_a)
    A_I_B = A_I_A
    A_J_B =  (A_J_A) - (A_A_A) * (a_ea_a) / (a_n_a)
    A_K_B = A_K_A
    A_L_B = A_L_A
    A_C_C =  (A_C_B) - (A_B_B) * (CH2OH_CH3OH)
    A_D_C = A_D_B
    A_E_C =  (A_E_B) - (A_B_B) * (CH2GSG_CH3OH)
    A_F_C = A_F_B
    A_G_C = A_G_B
    A_H_C = A_H_B
    A_I_C = A_I_B
    A_J_C = A_J_B
    A_K_C = A_K_B
    A_L_C = A_L_B
    A_D_D = A_D_C
    A_E_D =  (A_E_C) - (A_C_C) * (a_bp_c) / (a_ap_c)
    A_F_D = A_F_C
    A_G_D = A_G_C
    A_H_D = A_H_C
    A_I_D = A_I_C
    A_J_D = A_J_C
    A_K_D = A_K_C
    A_L_D = A_L_C
    A_E_E =  (A_E_D) - (A_D_D) * (a_bq_b) / (a_bd_b)
    A_F_E =  (A_F_D) - (A_D_D) * (a_cd_b) / (a_bd_b)
    A_G_E =  (A_G_D) - (A_D_D) * (a_cq_b) / (a_bd_b)
    A_H_E =  (A_H_D) - (A_D_D) * (a_dd_b) / (a_bd_b)
    A_I_E = A_I_D
    A_J_E =  (A_J_D) - (A_D_D) * (a_ed_b) / (a_bd_b)
    A_K_E = A_K_D
    A_L_E = A_L_D
    A_F_F =  (A_F_E) - (A_E_E) * (a_ce_e) / (a_br_e)
    A_G_F =  (A_G_E) - (A_E_E) * (a_cr_e) / (a_br_e)
    A_H_F =  (A_H_E) - (A_E_E) * (a_de_e) / (a_br_e)
    A_I_F = A_I_E
    A_J_F =  (A_J_E) - (A_E_E) * (a_ee_e) / (a_br_e)
    A_K_F = A_K_E
    A_L_F =  (A_L_E) - (A_E_E) * (a_fe_e) / (a_br_e)
    A_G_G =  (A_G_F) - (A_F_F) * (a_cs_a) / (a_cf_a)
    A_H_G = A_H_F
    A_I_G = A_I_F
    A_J_G =  (A_J_F) - (A_F_F) * (a_ef_a) / (a_cf_a)
    A_K_G = A_K_F
    A_L_G = A_L_F
    A_H_H = A_H_G
    A_I_H = A_I_G
    A_J_H =  (A_J_G) - (A_G_G) * (a_eg_a) / (a_ct_a)
    A_K_H = A_K_G
    A_L_H = A_L_G
    A_I_I =  (A_I_H) - (A_H_H) * (a_du_b) / (a_dh_b)
    A_J_I =  (A_J_H) - (A_H_H) * (a_eh_b) / (a_dh_b)
    A_K_I = A_K_H
    A_L_I = A_L_H
    A_J_J =  (A_J_I) - (A_I_I) * (a_ei_i) / (a_dv_i)
    A_K_J =  (A_K_I) - (A_I_I) * (a_ev_i) / (a_dv_i)
    A_L_J = A_L_I
    A_K_K =  (A_K_J) - (A_J_J) * (a_ew_a) / (a_ej_a)
    A_L_K = A_L_J
    A_L_L =  (A_L_K) - (A_K_K) * (a_fk_k) / (a_ex_k)

    cqss(sqssHCCO) = ( A_L_L ) / ( a_fl_l )  

    cqss(sqssCH2CO) = (A_K_K - (a_ey_f) * cqss(sqssHCCO)) / (a_ex_k)  

    cqss(sqssCH2CHO) = (A_J_J - (a_el_f) * cqss(sqssHCCO) - (a_ek_j) &
                 * cqss(sqssCH2CO)) / (a_ej_a)  

    cqss(sqssC2H2) = (A_I_I - (C2H2_CH2CO) * cqss(sqssCH2CO)) / (a_dv_i)  

    cqss(sqssC2H3) = (A_H_H - (a_dl_f) * cqss(sqssHCCO) - (C2H3_C2H2) &
                 * cqss(sqssC2H2)) / (a_dh_b)  

    cqss(sqssC2H5) = (A_G_G - (a_cy_f) * cqss(sqssHCCO) - (a_cw_a) &
                 * cqss(sqssCH2CHO) - (a_cu_b) * cqss(sqssC2H3)) &
                 / (a_ct_a)  

    cqss(sqssC) = (A_F_F - (a_cl_f) * cqss(sqssHCCO) - (a_cj_a) &
                 * cqss(sqssCH2CHO) - (a_ch_b) * cqss(sqssC2H3) &
                 - (a_cg_a) * cqss(sqssC2H5)) / (a_cf_a)  

    cqss(sqssCH2GSG) = (A_E_E - (CH2GSG_HCCO) * cqss(sqssHCCO)) / (a_br_e)  

    cqss(sqssCH2) = (A_D_D - (a_bh_b) * cqss(sqssC2H3) - (a_be_c) &
                 * cqss(sqssCH2GSG)) / (a_bd_b)  

    cqss(sqssCH2OH) = (A_C_C - (a_ar_c) * cqss(sqssCH2GSG)) / (a_ap_c)  

    cqss(sqssCH3OH) = A_B_B - (CH3OH_CH2GSG) * cqss(sqssCH2GSG) &
                 - (CH3OH_CH2OH) * cqss(sqssCH2OH)  

    cqss(sqssHCO) = (A_A_A - (a_w_a) * cqss(sqssCH2CHO) - (HCO_C2H3) &
                 * cqss(sqssC2H3) - (a_t_a) * cqss(sqssC2H5) &
                 - (a_s_a) * cqss(sqssC) - (HCO_CH2) * cqss(sqssCH2)) &
                 / (a_n_a)  

    cqss(sqssO) = O_ct - (O_CH2CHO) * cqss(sqssCH2CHO) - (O_C2H5) &
                 * cqss(sqssC2H5) - (O_C) * cqss(sqssC) - (O_HCO) &
                 * cqss(sqssHCO)  

    OCHO_denom = tiny(1.0_pr) + ( 0.0_pr &
             + k(r31b)  )

    OCHO_num = ( 0.0_pr &
             + k(r31f)* c(sCO2) * c(sH)   )

    OCHO_ct = OCHO_num / OCHO_denom

    cqss(sqssOCHO) = OCHO_ct  

    cqss = max(cqss, tiny(1.0_pr))
    cqss = min(cqss, 1e03_pr)

    ! Necessary for very low concentration variations
    ! Needs to be integrated only for Cantera
    do index=1,nqss
      if (cqss(index) /= cqss(index)) then
        cqss(index) = tiny(1.0_pr)
      end if
    end do

    return
  end subroutine get_qss


  ! ----------------------------------------------- !
  ! Mass fractions to concentrations                !
  ! ----------------------------------------------- !
  subroutine y2c(y, W_sp, P, T, c)
    implicit none

    real(pr),dimension(nspec) :: W_sp
    real(pr),dimension(nspec) :: c, y
    real(pr) :: rho, P, T, inv_W_g

    integer :: k
    
    ! Gas molecular weight inverse
    inv_W_g = 0.0_pr
    do k =1, nspec
      inv_W_g = inv_W_g + y(k) / W_sp(k)
    end do

    ! Gas density
    rho = P / (Rcst * inv_W_g * T)

    ! Conversion
    c = y * rho / W_sp

    ! Concentrations clipping
    !do  k = 1, nspec
    !   if (c(k)<1.0e-20_pr) c(k) = 0.0_pr
    !end do

        return
    end subroutine y2c

end module mod_customkinetics
! ----------------------------------------------- !
! Cantera routine                                 !
! ----------------------------------------------- !
subroutine customkinetics(P, T, y, wdot)

  use mod_customkinetics
  implicit none

  real(pr), dimension(nspec) :: y, c, wdot, cdot
  real(pr), dimension(nqss) :: cqss
  real(pr), dimension(nreac + nreac_reverse) :: w,k
  real(pr), dimension(nTB + nFO) :: M
  real(pr) :: P, T, rho

  ! Convert to concentrations
  call y2c(y, W_sp, P, T, c)

  ! Evaluate QSS concentrations and reaction rates
  call get_thirdbodies(M,c)

  call get_rate_coefficients(k, M, T, P)
  call get_qss(cqss, c, k, M)

  call get_reaction_rates(w, k, M, c, cqss)

  ! Evaluate production rates
  call get_production_rates(wdot,w)


  return
end subroutine customkinetics

